// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ced,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.400000,HLS_SYN_LAT=10927,HLS_SYN_TPT=10919,HLS_SYN_MEM=0,HLS_SYN_DSP=2,HLS_SYN_FF=3063,HLS_SYN_LUT=6954,HLS_VERSION=2018_3}" *)

module ced (
        image_in_TDATA,
        image_in_TKEEP,
        image_in_TSTRB,
        image_in_TUSER,
        image_in_TLAST,
        image_in_TID,
        image_in_TDEST,
        image_out_TDATA,
        image_out_TKEEP,
        image_out_TSTRB,
        image_out_TUSER,
        image_out_TLAST,
        image_out_TID,
        image_out_TDEST,
        ap_clk,
        ap_rst_n,
        image_in_TVALID,
        image_in_TREADY,
        image_out_TVALID,
        image_out_TREADY
);


input  [23:0] image_in_TDATA;
input  [2:0] image_in_TKEEP;
input  [2:0] image_in_TSTRB;
input  [0:0] image_in_TUSER;
input  [0:0] image_in_TLAST;
input  [0:0] image_in_TID;
input  [0:0] image_in_TDEST;
output  [23:0] image_out_TDATA;
output  [2:0] image_out_TKEEP;
output  [2:0] image_out_TSTRB;
output  [0:0] image_out_TUSER;
output  [0:0] image_out_TLAST;
output  [0:0] image_out_TID;
output  [0:0] image_out_TDEST;
input   ap_clk;
input   ap_rst_n;
input   image_in_TVALID;
output   image_in_TREADY;
output   image_out_TVALID;
input   image_out_TREADY;

 reg    ap_rst_n_inv;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_image_in_TREADY;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire    RGB2Gray_U0_ap_start;
wire    RGB2Gray_U0_ap_done;
wire    RGB2Gray_U0_ap_continue;
wire    RGB2Gray_U0_ap_idle;
wire    RGB2Gray_U0_ap_ready;
wire    RGB2Gray_U0_start_out;
wire    RGB2Gray_U0_start_write;
wire    RGB2Gray_U0_img_in_data_stream_0_V_read;
wire    RGB2Gray_U0_img_in_data_stream_1_V_read;
wire    RGB2Gray_U0_img_in_data_stream_2_V_read;
wire   [7:0] RGB2Gray_U0_img_out_data_stream_0_V_din;
wire    RGB2Gray_U0_img_out_data_stream_0_V_write;
wire   [7:0] RGB2Gray_U0_img_out_data_stream_1_V_din;
wire    RGB2Gray_U0_img_out_data_stream_1_V_write;
wire   [7:0] RGB2Gray_U0_img_out_data_stream_2_V_din;
wire    RGB2Gray_U0_img_out_data_stream_2_V_write;
wire    Filter2D_1_U0_ap_start;
wire    Filter2D_1_U0_ap_done;
wire    Filter2D_1_U0_ap_continue;
wire    Filter2D_1_U0_ap_idle;
wire    Filter2D_1_U0_ap_ready;
wire    Filter2D_1_U0_start_out;
wire    Filter2D_1_U0_start_write;
wire    Filter2D_1_U0_p_src_data_stream_0_V_read;
wire    Filter2D_1_U0_p_src_data_stream_1_V_read;
wire    Filter2D_1_U0_p_src_data_stream_2_V_read;
wire   [7:0] Filter2D_1_U0_p_dst_data_stream_0_V_din;
wire    Filter2D_1_U0_p_dst_data_stream_0_V_write;
wire   [7:0] Filter2D_1_U0_p_dst_data_stream_1_V_din;
wire    Filter2D_1_U0_p_dst_data_stream_1_V_write;
wire   [7:0] Filter2D_1_U0_p_dst_data_stream_2_V_din;
wire    Filter2D_1_U0_p_dst_data_stream_2_V_write;
wire    duplicate_U0_ap_start;
wire    duplicate_U0_start_full_n;
wire    duplicate_U0_ap_done;
wire    duplicate_U0_ap_continue;
wire    duplicate_U0_ap_idle;
wire    duplicate_U0_ap_ready;
wire    duplicate_U0_start_out;
wire    duplicate_U0_start_write;
wire    duplicate_U0_img_in_data_stream_0_V_read;
wire    duplicate_U0_img_in_data_stream_1_V_read;
wire    duplicate_U0_img_in_data_stream_2_V_read;
wire   [7:0] duplicate_U0_img_outa_data_stream_0_V_din;
wire    duplicate_U0_img_outa_data_stream_0_V_write;
wire   [7:0] duplicate_U0_img_outa_data_stream_1_V_din;
wire    duplicate_U0_img_outa_data_stream_1_V_write;
wire   [7:0] duplicate_U0_img_outa_data_stream_2_V_din;
wire    duplicate_U0_img_outa_data_stream_2_V_write;
wire   [7:0] duplicate_U0_img_outb_data_stream_0_V_din;
wire    duplicate_U0_img_outb_data_stream_0_V_write;
wire   [7:0] duplicate_U0_img_outb_data_stream_1_V_din;
wire    duplicate_U0_img_outb_data_stream_1_V_write;
wire   [7:0] duplicate_U0_img_outb_data_stream_2_V_din;
wire    duplicate_U0_img_outb_data_stream_2_V_write;
wire    Filter2D93_U0_ap_start;
wire    Filter2D93_U0_ap_done;
wire    Filter2D93_U0_ap_continue;
wire    Filter2D93_U0_ap_idle;
wire    Filter2D93_U0_ap_ready;
wire    Filter2D93_U0_start_out;
wire    Filter2D93_U0_start_write;
wire    Filter2D93_U0_p_src_data_stream_V_read;
wire    Filter2D93_U0_p_src_data_stream_V1_read;
wire    Filter2D93_U0_p_src_data_stream_V2_read;
wire   [7:0] Filter2D93_U0_p_dst_data_stream_V_din;
wire    Filter2D93_U0_p_dst_data_stream_V_write;
wire   [7:0] Filter2D93_U0_p_dst_data_stream_V3_din;
wire    Filter2D93_U0_p_dst_data_stream_V3_write;
wire   [7:0] Filter2D93_U0_p_dst_data_stream_V4_din;
wire    Filter2D93_U0_p_dst_data_stream_V4_write;
wire    Filter2D_U0_ap_start;
wire    Filter2D_U0_ap_done;
wire    Filter2D_U0_ap_continue;
wire    Filter2D_U0_ap_idle;
wire    Filter2D_U0_ap_ready;
wire    Filter2D_U0_p_src_data_stream_0_V_read;
wire    Filter2D_U0_p_src_data_stream_1_V_read;
wire    Filter2D_U0_p_src_data_stream_2_V_read;
wire   [7:0] Filter2D_U0_p_dst_data_stream_0_V_din;
wire    Filter2D_U0_p_dst_data_stream_0_V_write;
wire   [7:0] Filter2D_U0_p_dst_data_stream_1_V_din;
wire    Filter2D_U0_p_dst_data_stream_1_V_write;
wire   [7:0] Filter2D_U0_p_dst_data_stream_2_V_din;
wire    Filter2D_U0_p_dst_data_stream_2_V_write;
wire    addSobel_U0_ap_start;
wire    addSobel_U0_ap_done;
wire    addSobel_U0_ap_continue;
wire    addSobel_U0_ap_idle;
wire    addSobel_U0_ap_ready;
wire    addSobel_U0_start_out;
wire    addSobel_U0_start_write;
wire    addSobel_U0_img_ina_data_stream_0_V_read;
wire    addSobel_U0_img_ina_data_stream_1_V_read;
wire    addSobel_U0_img_ina_data_stream_2_V_read;
wire    addSobel_U0_img_inb_data_stream_0_V_read;
wire    addSobel_U0_img_inb_data_stream_1_V_read;
wire    addSobel_U0_img_inb_data_stream_2_V_read;
wire   [7:0] addSobel_U0_img_out_data_stream_0_V_din;
wire    addSobel_U0_img_out_data_stream_0_V_write;
wire   [7:0] addSobel_U0_img_out_data_stream_1_V_din;
wire    addSobel_U0_img_out_data_stream_1_V_write;
wire   [7:0] addSobel_U0_img_out_data_stream_2_V_din;
wire    addSobel_U0_img_out_data_stream_2_V_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [23:0] Mat2AXIvideo_U0_image_out_TDATA;
wire    Mat2AXIvideo_U0_image_out_TVALID;
wire   [2:0] Mat2AXIvideo_U0_image_out_TKEEP;
wire   [2:0] Mat2AXIvideo_U0_image_out_TSTRB;
wire   [0:0] Mat2AXIvideo_U0_image_out_TUSER;
wire   [0:0] Mat2AXIvideo_U0_image_out_TLAST;
wire   [0:0] Mat2AXIvideo_U0_image_out_TID;
wire   [0:0] Mat2AXIvideo_U0_image_out_TDEST;
wire    ap_sync_continue;
wire    src_data_stream_0_V_full_n;
wire   [7:0] src_data_stream_0_V_dout;
wire    src_data_stream_0_V_empty_n;
wire    src_data_stream_1_V_full_n;
wire   [7:0] src_data_stream_1_V_dout;
wire    src_data_stream_1_V_empty_n;
wire    src_data_stream_2_V_full_n;
wire   [7:0] src_data_stream_2_V_dout;
wire    src_data_stream_2_V_empty_n;
wire    dsta_data_stream_0_s_full_n;
wire   [7:0] dsta_data_stream_0_s_dout;
wire    dsta_data_stream_0_s_empty_n;
wire    dsta_data_stream_1_s_full_n;
wire   [7:0] dsta_data_stream_1_s_dout;
wire    dsta_data_stream_1_s_empty_n;
wire    dsta_data_stream_2_s_full_n;
wire   [7:0] dsta_data_stream_2_s_dout;
wire    dsta_data_stream_2_s_empty_n;
wire    dstb_data_stream_0_s_full_n;
wire   [7:0] dstb_data_stream_0_s_dout;
wire    dstb_data_stream_0_s_empty_n;
wire    dstb_data_stream_1_s_full_n;
wire   [7:0] dstb_data_stream_1_s_dout;
wire    dstb_data_stream_1_s_empty_n;
wire    dstb_data_stream_2_s_full_n;
wire   [7:0] dstb_data_stream_2_s_dout;
wire    dstb_data_stream_2_s_empty_n;
wire    dup_1_data_stream_0_full_n;
wire   [7:0] dup_1_data_stream_0_dout;
wire    dup_1_data_stream_0_empty_n;
wire    dup_1_data_stream_1_full_n;
wire   [7:0] dup_1_data_stream_1_dout;
wire    dup_1_data_stream_1_empty_n;
wire    dup_1_data_stream_2_full_n;
wire   [7:0] dup_1_data_stream_2_dout;
wire    dup_1_data_stream_2_empty_n;
wire    dup_2_data_stream_0_full_n;
wire   [7:0] dup_2_data_stream_0_dout;
wire    dup_2_data_stream_0_empty_n;
wire    dup_2_data_stream_1_full_n;
wire   [7:0] dup_2_data_stream_1_dout;
wire    dup_2_data_stream_1_empty_n;
wire    dup_2_data_stream_2_full_n;
wire   [7:0] dup_2_data_stream_2_dout;
wire    dup_2_data_stream_2_empty_n;
wire    dstc_data_stream_0_s_full_n;
wire   [7:0] dstc_data_stream_0_s_dout;
wire    dstc_data_stream_0_s_empty_n;
wire    dstc_data_stream_1_s_full_n;
wire   [7:0] dstc_data_stream_1_s_dout;
wire    dstc_data_stream_1_s_empty_n;
wire    dstc_data_stream_2_s_full_n;
wire   [7:0] dstc_data_stream_2_s_dout;
wire    dstc_data_stream_2_s_empty_n;
wire    dstd_data_stream_0_s_full_n;
wire   [7:0] dstd_data_stream_0_s_dout;
wire    dstd_data_stream_0_s_empty_n;
wire    dstd_data_stream_1_s_full_n;
wire   [7:0] dstd_data_stream_1_s_dout;
wire    dstd_data_stream_1_s_empty_n;
wire    dstd_data_stream_2_s_full_n;
wire   [7:0] dstd_data_stream_2_s_dout;
wire    dstd_data_stream_2_s_empty_n;
wire    dste_data_stream_0_s_full_n;
wire   [7:0] dste_data_stream_0_s_dout;
wire    dste_data_stream_0_s_empty_n;
wire    dste_data_stream_1_s_full_n;
wire   [7:0] dste_data_stream_1_s_dout;
wire    dste_data_stream_1_s_empty_n;
wire    dste_data_stream_2_s_full_n;
wire   [7:0] dste_data_stream_2_s_dout;
wire    dste_data_stream_2_s_empty_n;
wire   [0:0] start_for_RGB2Gray_U0_din;
wire    start_for_RGB2Gray_U0_full_n;
wire   [0:0] start_for_RGB2Gray_U0_dout;
wire    start_for_RGB2Gray_U0_empty_n;
wire   [0:0] start_for_Filter2D_1_U0_din;
wire    start_for_Filter2D_1_U0_full_n;
wire   [0:0] start_for_Filter2D_1_U0_dout;
wire    start_for_Filter2D_1_U0_empty_n;
wire   [0:0] start_for_duplicate_U0_din;
wire    start_for_duplicate_U0_full_n;
wire   [0:0] start_for_duplicate_U0_dout;
wire    start_for_duplicate_U0_empty_n;
wire   [0:0] start_for_Filter2D93_U0_din;
wire    start_for_Filter2D93_U0_full_n;
wire   [0:0] start_for_Filter2D93_U0_dout;
wire    start_for_Filter2D93_U0_empty_n;
wire   [0:0] start_for_Filter2D_U0_din;
wire    start_for_Filter2D_U0_full_n;
wire   [0:0] start_for_Filter2D_U0_dout;
wire    start_for_Filter2D_U0_empty_n;
wire   [0:0] start_for_addSobel_U0_din;
wire    start_for_addSobel_U0_full_n;
wire   [0:0] start_for_addSobel_U0_dout;
wire    start_for_addSobel_U0_empty_n;
wire    Filter2D_U0_start_full_n;
wire    Filter2D_U0_start_write;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_RGB2Gray_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .image_in_TDATA(image_in_TDATA),
    .image_in_TVALID(image_in_TVALID),
    .image_in_TREADY(AXIvideo2Mat_U0_image_in_TREADY),
    .image_in_TKEEP(image_in_TKEEP),
    .image_in_TSTRB(image_in_TSTRB),
    .image_in_TUSER(image_in_TUSER),
    .image_in_TLAST(image_in_TLAST),
    .image_in_TID(image_in_TID),
    .image_in_TDEST(image_in_TDEST),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(src_data_stream_0_V_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(src_data_stream_1_V_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(src_data_stream_2_V_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write)
);

RGB2Gray RGB2Gray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(RGB2Gray_U0_ap_start),
    .start_full_n(start_for_Filter2D_1_U0_full_n),
    .ap_done(RGB2Gray_U0_ap_done),
    .ap_continue(RGB2Gray_U0_ap_continue),
    .ap_idle(RGB2Gray_U0_ap_idle),
    .ap_ready(RGB2Gray_U0_ap_ready),
    .start_out(RGB2Gray_U0_start_out),
    .start_write(RGB2Gray_U0_start_write),
    .img_in_data_stream_0_V_dout(src_data_stream_0_V_dout),
    .img_in_data_stream_0_V_empty_n(src_data_stream_0_V_empty_n),
    .img_in_data_stream_0_V_read(RGB2Gray_U0_img_in_data_stream_0_V_read),
    .img_in_data_stream_1_V_dout(src_data_stream_1_V_dout),
    .img_in_data_stream_1_V_empty_n(src_data_stream_1_V_empty_n),
    .img_in_data_stream_1_V_read(RGB2Gray_U0_img_in_data_stream_1_V_read),
    .img_in_data_stream_2_V_dout(src_data_stream_2_V_dout),
    .img_in_data_stream_2_V_empty_n(src_data_stream_2_V_empty_n),
    .img_in_data_stream_2_V_read(RGB2Gray_U0_img_in_data_stream_2_V_read),
    .img_out_data_stream_0_V_din(RGB2Gray_U0_img_out_data_stream_0_V_din),
    .img_out_data_stream_0_V_full_n(dsta_data_stream_0_s_full_n),
    .img_out_data_stream_0_V_write(RGB2Gray_U0_img_out_data_stream_0_V_write),
    .img_out_data_stream_1_V_din(RGB2Gray_U0_img_out_data_stream_1_V_din),
    .img_out_data_stream_1_V_full_n(dsta_data_stream_1_s_full_n),
    .img_out_data_stream_1_V_write(RGB2Gray_U0_img_out_data_stream_1_V_write),
    .img_out_data_stream_2_V_din(RGB2Gray_U0_img_out_data_stream_2_V_din),
    .img_out_data_stream_2_V_full_n(dsta_data_stream_2_s_full_n),
    .img_out_data_stream_2_V_write(RGB2Gray_U0_img_out_data_stream_2_V_write)
);

Filter2D_1 Filter2D_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter2D_1_U0_ap_start),
    .start_full_n(start_for_duplicate_U0_full_n),
    .ap_done(Filter2D_1_U0_ap_done),
    .ap_continue(Filter2D_1_U0_ap_continue),
    .ap_idle(Filter2D_1_U0_ap_idle),
    .ap_ready(Filter2D_1_U0_ap_ready),
    .start_out(Filter2D_1_U0_start_out),
    .start_write(Filter2D_1_U0_start_write),
    .p_src_data_stream_0_V_dout(dsta_data_stream_0_s_dout),
    .p_src_data_stream_0_V_empty_n(dsta_data_stream_0_s_empty_n),
    .p_src_data_stream_0_V_read(Filter2D_1_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(dsta_data_stream_1_s_dout),
    .p_src_data_stream_1_V_empty_n(dsta_data_stream_1_s_empty_n),
    .p_src_data_stream_1_V_read(Filter2D_1_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(dsta_data_stream_2_s_dout),
    .p_src_data_stream_2_V_empty_n(dsta_data_stream_2_s_empty_n),
    .p_src_data_stream_2_V_read(Filter2D_1_U0_p_src_data_stream_2_V_read),
    .p_dst_data_stream_0_V_din(Filter2D_1_U0_p_dst_data_stream_0_V_din),
    .p_dst_data_stream_0_V_full_n(dstb_data_stream_0_s_full_n),
    .p_dst_data_stream_0_V_write(Filter2D_1_U0_p_dst_data_stream_0_V_write),
    .p_dst_data_stream_1_V_din(Filter2D_1_U0_p_dst_data_stream_1_V_din),
    .p_dst_data_stream_1_V_full_n(dstb_data_stream_1_s_full_n),
    .p_dst_data_stream_1_V_write(Filter2D_1_U0_p_dst_data_stream_1_V_write),
    .p_dst_data_stream_2_V_din(Filter2D_1_U0_p_dst_data_stream_2_V_din),
    .p_dst_data_stream_2_V_full_n(dstb_data_stream_2_s_full_n),
    .p_dst_data_stream_2_V_write(Filter2D_1_U0_p_dst_data_stream_2_V_write)
);

duplicate duplicate_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(duplicate_U0_ap_start),
    .start_full_n(duplicate_U0_start_full_n),
    .ap_done(duplicate_U0_ap_done),
    .ap_continue(duplicate_U0_ap_continue),
    .ap_idle(duplicate_U0_ap_idle),
    .ap_ready(duplicate_U0_ap_ready),
    .start_out(duplicate_U0_start_out),
    .start_write(duplicate_U0_start_write),
    .img_in_data_stream_0_V_dout(dstb_data_stream_0_s_dout),
    .img_in_data_stream_0_V_empty_n(dstb_data_stream_0_s_empty_n),
    .img_in_data_stream_0_V_read(duplicate_U0_img_in_data_stream_0_V_read),
    .img_in_data_stream_1_V_dout(dstb_data_stream_1_s_dout),
    .img_in_data_stream_1_V_empty_n(dstb_data_stream_1_s_empty_n),
    .img_in_data_stream_1_V_read(duplicate_U0_img_in_data_stream_1_V_read),
    .img_in_data_stream_2_V_dout(dstb_data_stream_2_s_dout),
    .img_in_data_stream_2_V_empty_n(dstb_data_stream_2_s_empty_n),
    .img_in_data_stream_2_V_read(duplicate_U0_img_in_data_stream_2_V_read),
    .img_outa_data_stream_0_V_din(duplicate_U0_img_outa_data_stream_0_V_din),
    .img_outa_data_stream_0_V_full_n(dup_1_data_stream_0_full_n),
    .img_outa_data_stream_0_V_write(duplicate_U0_img_outa_data_stream_0_V_write),
    .img_outa_data_stream_1_V_din(duplicate_U0_img_outa_data_stream_1_V_din),
    .img_outa_data_stream_1_V_full_n(dup_1_data_stream_1_full_n),
    .img_outa_data_stream_1_V_write(duplicate_U0_img_outa_data_stream_1_V_write),
    .img_outa_data_stream_2_V_din(duplicate_U0_img_outa_data_stream_2_V_din),
    .img_outa_data_stream_2_V_full_n(dup_1_data_stream_2_full_n),
    .img_outa_data_stream_2_V_write(duplicate_U0_img_outa_data_stream_2_V_write),
    .img_outb_data_stream_0_V_din(duplicate_U0_img_outb_data_stream_0_V_din),
    .img_outb_data_stream_0_V_full_n(dup_2_data_stream_0_full_n),
    .img_outb_data_stream_0_V_write(duplicate_U0_img_outb_data_stream_0_V_write),
    .img_outb_data_stream_1_V_din(duplicate_U0_img_outb_data_stream_1_V_din),
    .img_outb_data_stream_1_V_full_n(dup_2_data_stream_1_full_n),
    .img_outb_data_stream_1_V_write(duplicate_U0_img_outb_data_stream_1_V_write),
    .img_outb_data_stream_2_V_din(duplicate_U0_img_outb_data_stream_2_V_din),
    .img_outb_data_stream_2_V_full_n(dup_2_data_stream_2_full_n),
    .img_outb_data_stream_2_V_write(duplicate_U0_img_outb_data_stream_2_V_write)
);

Filter2D93 Filter2D93_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter2D93_U0_ap_start),
    .start_full_n(start_for_addSobel_U0_full_n),
    .ap_done(Filter2D93_U0_ap_done),
    .ap_continue(Filter2D93_U0_ap_continue),
    .ap_idle(Filter2D93_U0_ap_idle),
    .ap_ready(Filter2D93_U0_ap_ready),
    .start_out(Filter2D93_U0_start_out),
    .start_write(Filter2D93_U0_start_write),
    .p_src_data_stream_V_dout(dup_1_data_stream_0_dout),
    .p_src_data_stream_V_empty_n(dup_1_data_stream_0_empty_n),
    .p_src_data_stream_V_read(Filter2D93_U0_p_src_data_stream_V_read),
    .p_src_data_stream_V1_dout(dup_1_data_stream_1_dout),
    .p_src_data_stream_V1_empty_n(dup_1_data_stream_1_empty_n),
    .p_src_data_stream_V1_read(Filter2D93_U0_p_src_data_stream_V1_read),
    .p_src_data_stream_V2_dout(dup_1_data_stream_2_dout),
    .p_src_data_stream_V2_empty_n(dup_1_data_stream_2_empty_n),
    .p_src_data_stream_V2_read(Filter2D93_U0_p_src_data_stream_V2_read),
    .p_dst_data_stream_V_din(Filter2D93_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(dstc_data_stream_0_s_full_n),
    .p_dst_data_stream_V_write(Filter2D93_U0_p_dst_data_stream_V_write),
    .p_dst_data_stream_V3_din(Filter2D93_U0_p_dst_data_stream_V3_din),
    .p_dst_data_stream_V3_full_n(dstc_data_stream_1_s_full_n),
    .p_dst_data_stream_V3_write(Filter2D93_U0_p_dst_data_stream_V3_write),
    .p_dst_data_stream_V4_din(Filter2D93_U0_p_dst_data_stream_V4_din),
    .p_dst_data_stream_V4_full_n(dstc_data_stream_2_s_full_n),
    .p_dst_data_stream_V4_write(Filter2D93_U0_p_dst_data_stream_V4_write)
);

Filter2D Filter2D_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter2D_U0_ap_start),
    .ap_done(Filter2D_U0_ap_done),
    .ap_continue(Filter2D_U0_ap_continue),
    .ap_idle(Filter2D_U0_ap_idle),
    .ap_ready(Filter2D_U0_ap_ready),
    .p_src_data_stream_0_V_dout(dup_2_data_stream_0_dout),
    .p_src_data_stream_0_V_empty_n(dup_2_data_stream_0_empty_n),
    .p_src_data_stream_0_V_read(Filter2D_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(dup_2_data_stream_1_dout),
    .p_src_data_stream_1_V_empty_n(dup_2_data_stream_1_empty_n),
    .p_src_data_stream_1_V_read(Filter2D_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(dup_2_data_stream_2_dout),
    .p_src_data_stream_2_V_empty_n(dup_2_data_stream_2_empty_n),
    .p_src_data_stream_2_V_read(Filter2D_U0_p_src_data_stream_2_V_read),
    .p_dst_data_stream_0_V_din(Filter2D_U0_p_dst_data_stream_0_V_din),
    .p_dst_data_stream_0_V_full_n(dstd_data_stream_0_s_full_n),
    .p_dst_data_stream_0_V_write(Filter2D_U0_p_dst_data_stream_0_V_write),
    .p_dst_data_stream_1_V_din(Filter2D_U0_p_dst_data_stream_1_V_din),
    .p_dst_data_stream_1_V_full_n(dstd_data_stream_1_s_full_n),
    .p_dst_data_stream_1_V_write(Filter2D_U0_p_dst_data_stream_1_V_write),
    .p_dst_data_stream_2_V_din(Filter2D_U0_p_dst_data_stream_2_V_din),
    .p_dst_data_stream_2_V_full_n(dstd_data_stream_2_s_full_n),
    .p_dst_data_stream_2_V_write(Filter2D_U0_p_dst_data_stream_2_V_write)
);

addSobel addSobel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(addSobel_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(addSobel_U0_ap_done),
    .ap_continue(addSobel_U0_ap_continue),
    .ap_idle(addSobel_U0_ap_idle),
    .ap_ready(addSobel_U0_ap_ready),
    .start_out(addSobel_U0_start_out),
    .start_write(addSobel_U0_start_write),
    .img_ina_data_stream_0_V_dout(dstc_data_stream_0_s_dout),
    .img_ina_data_stream_0_V_empty_n(dstc_data_stream_0_s_empty_n),
    .img_ina_data_stream_0_V_read(addSobel_U0_img_ina_data_stream_0_V_read),
    .img_ina_data_stream_1_V_dout(dstc_data_stream_1_s_dout),
    .img_ina_data_stream_1_V_empty_n(dstc_data_stream_1_s_empty_n),
    .img_ina_data_stream_1_V_read(addSobel_U0_img_ina_data_stream_1_V_read),
    .img_ina_data_stream_2_V_dout(dstc_data_stream_2_s_dout),
    .img_ina_data_stream_2_V_empty_n(dstc_data_stream_2_s_empty_n),
    .img_ina_data_stream_2_V_read(addSobel_U0_img_ina_data_stream_2_V_read),
    .img_inb_data_stream_0_V_dout(dstd_data_stream_0_s_dout),
    .img_inb_data_stream_0_V_empty_n(dstd_data_stream_0_s_empty_n),
    .img_inb_data_stream_0_V_read(addSobel_U0_img_inb_data_stream_0_V_read),
    .img_inb_data_stream_1_V_dout(dstd_data_stream_1_s_dout),
    .img_inb_data_stream_1_V_empty_n(dstd_data_stream_1_s_empty_n),
    .img_inb_data_stream_1_V_read(addSobel_U0_img_inb_data_stream_1_V_read),
    .img_inb_data_stream_2_V_dout(dstd_data_stream_2_s_dout),
    .img_inb_data_stream_2_V_empty_n(dstd_data_stream_2_s_empty_n),
    .img_inb_data_stream_2_V_read(addSobel_U0_img_inb_data_stream_2_V_read),
    .img_out_data_stream_0_V_din(addSobel_U0_img_out_data_stream_0_V_din),
    .img_out_data_stream_0_V_full_n(dste_data_stream_0_s_full_n),
    .img_out_data_stream_0_V_write(addSobel_U0_img_out_data_stream_0_V_write),
    .img_out_data_stream_1_V_din(addSobel_U0_img_out_data_stream_1_V_din),
    .img_out_data_stream_1_V_full_n(dste_data_stream_1_s_full_n),
    .img_out_data_stream_1_V_write(addSobel_U0_img_out_data_stream_1_V_write),
    .img_out_data_stream_2_V_din(addSobel_U0_img_out_data_stream_2_V_din),
    .img_out_data_stream_2_V_full_n(dste_data_stream_2_s_full_n),
    .img_out_data_stream_2_V_write(addSobel_U0_img_out_data_stream_2_V_write)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_data_stream_0_V_dout(dste_data_stream_0_s_dout),
    .img_data_stream_0_V_empty_n(dste_data_stream_0_s_empty_n),
    .img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read),
    .img_data_stream_1_V_dout(dste_data_stream_1_s_dout),
    .img_data_stream_1_V_empty_n(dste_data_stream_1_s_empty_n),
    .img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read),
    .img_data_stream_2_V_dout(dste_data_stream_2_s_dout),
    .img_data_stream_2_V_empty_n(dste_data_stream_2_s_empty_n),
    .img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read),
    .image_out_TDATA(Mat2AXIvideo_U0_image_out_TDATA),
    .image_out_TVALID(Mat2AXIvideo_U0_image_out_TVALID),
    .image_out_TREADY(image_out_TREADY),
    .image_out_TKEEP(Mat2AXIvideo_U0_image_out_TKEEP),
    .image_out_TSTRB(Mat2AXIvideo_U0_image_out_TSTRB),
    .image_out_TUSER(Mat2AXIvideo_U0_image_out_TUSER),
    .image_out_TLAST(Mat2AXIvideo_U0_image_out_TLAST),
    .image_out_TID(Mat2AXIvideo_U0_image_out_TID),
    .image_out_TDEST(Mat2AXIvideo_U0_image_out_TDEST)
);

fifo_w8_d2_A src_data_stream_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(src_data_stream_0_V_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(src_data_stream_0_V_dout),
    .if_empty_n(src_data_stream_0_V_empty_n),
    .if_read(RGB2Gray_U0_img_in_data_stream_0_V_read)
);

fifo_w8_d2_A src_data_stream_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(src_data_stream_1_V_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(src_data_stream_1_V_dout),
    .if_empty_n(src_data_stream_1_V_empty_n),
    .if_read(RGB2Gray_U0_img_in_data_stream_1_V_read)
);

fifo_w8_d2_A src_data_stream_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(src_data_stream_2_V_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(src_data_stream_2_V_dout),
    .if_empty_n(src_data_stream_2_V_empty_n),
    .if_read(RGB2Gray_U0_img_in_data_stream_2_V_read)
);

fifo_w8_d2_A dsta_data_stream_0_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(RGB2Gray_U0_img_out_data_stream_0_V_din),
    .if_full_n(dsta_data_stream_0_s_full_n),
    .if_write(RGB2Gray_U0_img_out_data_stream_0_V_write),
    .if_dout(dsta_data_stream_0_s_dout),
    .if_empty_n(dsta_data_stream_0_s_empty_n),
    .if_read(Filter2D_1_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A dsta_data_stream_1_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(RGB2Gray_U0_img_out_data_stream_1_V_din),
    .if_full_n(dsta_data_stream_1_s_full_n),
    .if_write(RGB2Gray_U0_img_out_data_stream_1_V_write),
    .if_dout(dsta_data_stream_1_s_dout),
    .if_empty_n(dsta_data_stream_1_s_empty_n),
    .if_read(Filter2D_1_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A dsta_data_stream_2_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(RGB2Gray_U0_img_out_data_stream_2_V_din),
    .if_full_n(dsta_data_stream_2_s_full_n),
    .if_write(RGB2Gray_U0_img_out_data_stream_2_V_write),
    .if_dout(dsta_data_stream_2_s_dout),
    .if_empty_n(dsta_data_stream_2_s_empty_n),
    .if_read(Filter2D_1_U0_p_src_data_stream_2_V_read)
);

fifo_w8_d2_A dstb_data_stream_0_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_1_U0_p_dst_data_stream_0_V_din),
    .if_full_n(dstb_data_stream_0_s_full_n),
    .if_write(Filter2D_1_U0_p_dst_data_stream_0_V_write),
    .if_dout(dstb_data_stream_0_s_dout),
    .if_empty_n(dstb_data_stream_0_s_empty_n),
    .if_read(duplicate_U0_img_in_data_stream_0_V_read)
);

fifo_w8_d2_A dstb_data_stream_1_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_1_U0_p_dst_data_stream_1_V_din),
    .if_full_n(dstb_data_stream_1_s_full_n),
    .if_write(Filter2D_1_U0_p_dst_data_stream_1_V_write),
    .if_dout(dstb_data_stream_1_s_dout),
    .if_empty_n(dstb_data_stream_1_s_empty_n),
    .if_read(duplicate_U0_img_in_data_stream_1_V_read)
);

fifo_w8_d2_A dstb_data_stream_2_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_1_U0_p_dst_data_stream_2_V_din),
    .if_full_n(dstb_data_stream_2_s_full_n),
    .if_write(Filter2D_1_U0_p_dst_data_stream_2_V_write),
    .if_dout(dstb_data_stream_2_s_dout),
    .if_empty_n(dstb_data_stream_2_s_empty_n),
    .if_read(duplicate_U0_img_in_data_stream_2_V_read)
);

fifo_w8_d2_A dup_1_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(duplicate_U0_img_outa_data_stream_0_V_din),
    .if_full_n(dup_1_data_stream_0_full_n),
    .if_write(duplicate_U0_img_outa_data_stream_0_V_write),
    .if_dout(dup_1_data_stream_0_dout),
    .if_empty_n(dup_1_data_stream_0_empty_n),
    .if_read(Filter2D93_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A dup_1_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(duplicate_U0_img_outa_data_stream_1_V_din),
    .if_full_n(dup_1_data_stream_1_full_n),
    .if_write(duplicate_U0_img_outa_data_stream_1_V_write),
    .if_dout(dup_1_data_stream_1_dout),
    .if_empty_n(dup_1_data_stream_1_empty_n),
    .if_read(Filter2D93_U0_p_src_data_stream_V1_read)
);

fifo_w8_d2_A dup_1_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(duplicate_U0_img_outa_data_stream_2_V_din),
    .if_full_n(dup_1_data_stream_2_full_n),
    .if_write(duplicate_U0_img_outa_data_stream_2_V_write),
    .if_dout(dup_1_data_stream_2_dout),
    .if_empty_n(dup_1_data_stream_2_empty_n),
    .if_read(Filter2D93_U0_p_src_data_stream_V2_read)
);

fifo_w8_d2_A dup_2_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(duplicate_U0_img_outb_data_stream_0_V_din),
    .if_full_n(dup_2_data_stream_0_full_n),
    .if_write(duplicate_U0_img_outb_data_stream_0_V_write),
    .if_dout(dup_2_data_stream_0_dout),
    .if_empty_n(dup_2_data_stream_0_empty_n),
    .if_read(Filter2D_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A dup_2_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(duplicate_U0_img_outb_data_stream_1_V_din),
    .if_full_n(dup_2_data_stream_1_full_n),
    .if_write(duplicate_U0_img_outb_data_stream_1_V_write),
    .if_dout(dup_2_data_stream_1_dout),
    .if_empty_n(dup_2_data_stream_1_empty_n),
    .if_read(Filter2D_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A dup_2_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(duplicate_U0_img_outb_data_stream_2_V_din),
    .if_full_n(dup_2_data_stream_2_full_n),
    .if_write(duplicate_U0_img_outb_data_stream_2_V_write),
    .if_dout(dup_2_data_stream_2_dout),
    .if_empty_n(dup_2_data_stream_2_empty_n),
    .if_read(Filter2D_U0_p_src_data_stream_2_V_read)
);

fifo_w8_d2_A dstc_data_stream_0_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D93_U0_p_dst_data_stream_V_din),
    .if_full_n(dstc_data_stream_0_s_full_n),
    .if_write(Filter2D93_U0_p_dst_data_stream_V_write),
    .if_dout(dstc_data_stream_0_s_dout),
    .if_empty_n(dstc_data_stream_0_s_empty_n),
    .if_read(addSobel_U0_img_ina_data_stream_0_V_read)
);

fifo_w8_d2_A dstc_data_stream_1_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D93_U0_p_dst_data_stream_V3_din),
    .if_full_n(dstc_data_stream_1_s_full_n),
    .if_write(Filter2D93_U0_p_dst_data_stream_V3_write),
    .if_dout(dstc_data_stream_1_s_dout),
    .if_empty_n(dstc_data_stream_1_s_empty_n),
    .if_read(addSobel_U0_img_ina_data_stream_1_V_read)
);

fifo_w8_d2_A dstc_data_stream_2_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D93_U0_p_dst_data_stream_V4_din),
    .if_full_n(dstc_data_stream_2_s_full_n),
    .if_write(Filter2D93_U0_p_dst_data_stream_V4_write),
    .if_dout(dstc_data_stream_2_s_dout),
    .if_empty_n(dstc_data_stream_2_s_empty_n),
    .if_read(addSobel_U0_img_ina_data_stream_2_V_read)
);

fifo_w8_d2_A dstd_data_stream_0_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_U0_p_dst_data_stream_0_V_din),
    .if_full_n(dstd_data_stream_0_s_full_n),
    .if_write(Filter2D_U0_p_dst_data_stream_0_V_write),
    .if_dout(dstd_data_stream_0_s_dout),
    .if_empty_n(dstd_data_stream_0_s_empty_n),
    .if_read(addSobel_U0_img_inb_data_stream_0_V_read)
);

fifo_w8_d2_A dstd_data_stream_1_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_U0_p_dst_data_stream_1_V_din),
    .if_full_n(dstd_data_stream_1_s_full_n),
    .if_write(Filter2D_U0_p_dst_data_stream_1_V_write),
    .if_dout(dstd_data_stream_1_s_dout),
    .if_empty_n(dstd_data_stream_1_s_empty_n),
    .if_read(addSobel_U0_img_inb_data_stream_1_V_read)
);

fifo_w8_d2_A dstd_data_stream_2_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_U0_p_dst_data_stream_2_V_din),
    .if_full_n(dstd_data_stream_2_s_full_n),
    .if_write(Filter2D_U0_p_dst_data_stream_2_V_write),
    .if_dout(dstd_data_stream_2_s_dout),
    .if_empty_n(dstd_data_stream_2_s_empty_n),
    .if_read(addSobel_U0_img_inb_data_stream_2_V_read)
);

fifo_w8_d2_A dste_data_stream_0_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(addSobel_U0_img_out_data_stream_0_V_din),
    .if_full_n(dste_data_stream_0_s_full_n),
    .if_write(addSobel_U0_img_out_data_stream_0_V_write),
    .if_dout(dste_data_stream_0_s_dout),
    .if_empty_n(dste_data_stream_0_s_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read)
);

fifo_w8_d2_A dste_data_stream_1_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(addSobel_U0_img_out_data_stream_1_V_din),
    .if_full_n(dste_data_stream_1_s_full_n),
    .if_write(addSobel_U0_img_out_data_stream_1_V_write),
    .if_dout(dste_data_stream_1_s_dout),
    .if_empty_n(dste_data_stream_1_s_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read)
);

fifo_w8_d2_A dste_data_stream_2_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(addSobel_U0_img_out_data_stream_2_V_din),
    .if_full_n(dste_data_stream_2_s_full_n),
    .if_write(addSobel_U0_img_out_data_stream_2_V_write),
    .if_dout(dste_data_stream_2_s_dout),
    .if_empty_n(dste_data_stream_2_s_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read)
);

start_for_RGB2GraEe0 start_for_RGB2GraEe0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_RGB2Gray_U0_din),
    .if_full_n(start_for_RGB2Gray_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_RGB2Gray_U0_dout),
    .if_empty_n(start_for_RGB2Gray_U0_empty_n),
    .if_read(RGB2Gray_U0_ap_ready)
);

start_for_Filter2Ffa start_for_Filter2Ffa_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Filter2D_1_U0_din),
    .if_full_n(start_for_Filter2D_1_U0_full_n),
    .if_write(RGB2Gray_U0_start_write),
    .if_dout(start_for_Filter2D_1_U0_dout),
    .if_empty_n(start_for_Filter2D_1_U0_empty_n),
    .if_read(Filter2D_1_U0_ap_ready)
);

start_for_duplicaGfk start_for_duplicaGfk_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_duplicate_U0_din),
    .if_full_n(start_for_duplicate_U0_full_n),
    .if_write(Filter2D_1_U0_start_write),
    .if_dout(start_for_duplicate_U0_dout),
    .if_empty_n(start_for_duplicate_U0_empty_n),
    .if_read(duplicate_U0_ap_ready)
);

start_for_Filter2Hfu start_for_Filter2Hfu_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Filter2D93_U0_din),
    .if_full_n(start_for_Filter2D93_U0_full_n),
    .if_write(duplicate_U0_start_write),
    .if_dout(start_for_Filter2D93_U0_dout),
    .if_empty_n(start_for_Filter2D93_U0_empty_n),
    .if_read(Filter2D93_U0_ap_ready)
);

start_for_Filter2IfE start_for_Filter2IfE_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Filter2D_U0_din),
    .if_full_n(start_for_Filter2D_U0_full_n),
    .if_write(duplicate_U0_start_write),
    .if_dout(start_for_Filter2D_U0_dout),
    .if_empty_n(start_for_Filter2D_U0_empty_n),
    .if_read(Filter2D_U0_ap_ready)
);

start_for_addSobeJfO start_for_addSobeJfO_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_addSobel_U0_din),
    .if_full_n(start_for_addSobel_U0_full_n),
    .if_write(Filter2D93_U0_start_write),
    .if_dout(start_for_addSobel_U0_dout),
    .if_empty_n(start_for_addSobel_U0_empty_n),
    .if_read(addSobel_U0_ap_ready)
);

start_for_Mat2AXIKfY start_for_Mat2AXIKfY_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(addSobel_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = 1'b1;

assign Filter2D93_U0_ap_continue = 1'b1;

assign Filter2D93_U0_ap_start = start_for_Filter2D93_U0_empty_n;

assign Filter2D_1_U0_ap_continue = 1'b1;

assign Filter2D_1_U0_ap_start = start_for_Filter2D_1_U0_empty_n;

assign Filter2D_U0_ap_continue = 1'b1;

assign Filter2D_U0_ap_start = start_for_Filter2D_U0_empty_n;

assign Filter2D_U0_start_full_n = 1'b1;

assign Filter2D_U0_start_write = 1'b0;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign RGB2Gray_U0_ap_continue = 1'b1;

assign RGB2Gray_U0_ap_start = start_for_RGB2Gray_U0_empty_n;

assign addSobel_U0_ap_continue = 1'b1;

assign addSobel_U0_ap_start = start_for_addSobel_U0_empty_n;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign duplicate_U0_ap_continue = 1'b1;

assign duplicate_U0_ap_start = start_for_duplicate_U0_empty_n;

assign duplicate_U0_start_full_n = (start_for_Filter2D_U0_full_n & start_for_Filter2D93_U0_full_n);

assign image_in_TREADY = AXIvideo2Mat_U0_image_in_TREADY;

assign image_out_TDATA = Mat2AXIvideo_U0_image_out_TDATA;

assign image_out_TDEST = Mat2AXIvideo_U0_image_out_TDEST;

assign image_out_TID = Mat2AXIvideo_U0_image_out_TID;

assign image_out_TKEEP = Mat2AXIvideo_U0_image_out_TKEEP;

assign image_out_TLAST = Mat2AXIvideo_U0_image_out_TLAST;

assign image_out_TSTRB = Mat2AXIvideo_U0_image_out_TSTRB;

assign image_out_TUSER = Mat2AXIvideo_U0_image_out_TUSER;

assign image_out_TVALID = Mat2AXIvideo_U0_image_out_TVALID;

assign start_for_Filter2D93_U0_din = 1'b1;

assign start_for_Filter2D_1_U0_din = 1'b1;

assign start_for_Filter2D_U0_din = 1'b1;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

assign start_for_RGB2Gray_U0_din = 1'b1;

assign start_for_addSobel_U0_din = 1'b1;

assign start_for_duplicate_U0_din = 1'b1;

endmodule //ced
