// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state8 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond461_i_reg_2330;
reg   [0:0] or_cond_i_i_reg_2339;
reg   [0:0] icmp_reg_2283;
reg   [0:0] tmp_18_reg_2274;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] or_cond_i_reg_2379;
reg   [0:0] or_cond_i_reg_2379_pp0_iter2_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [6:0] t_V_3_reg_588;
wire   [1:0] tmp_13_fu_599_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond462_i_fu_611_p2;
wire    ap_CS_fsm_state3;
wire   [6:0] i_V_fu_617_p2;
reg   [6:0] i_V_reg_2269;
wire   [0:0] tmp_18_fu_623_p2;
wire   [0:0] tmp_58_0_0_not_fu_629_p2;
reg   [0:0] tmp_58_0_0_not_reg_2278;
wire   [0:0] icmp_fu_645_p2;
wire   [0:0] tmp_20_fu_651_p2;
reg   [0:0] tmp_20_reg_2288;
wire   [0:0] tmp_102_0_1_fu_657_p2;
reg   [0:0] tmp_102_0_1_reg_2292;
wire   [0:0] tmp_21_fu_663_p2;
reg   [0:0] tmp_21_reg_2296;
wire   [1:0] tmp_100_fu_669_p1;
reg   [1:0] tmp_100_reg_2309;
wire   [1:0] row_assign_8_0_1_t_fu_673_p2;
reg   [1:0] row_assign_8_0_1_t_reg_2316;
wire   [1:0] row_assign_8_0_2_t_fu_679_p2;
reg   [1:0] row_assign_8_0_2_t_reg_2323;
wire   [0:0] exitcond461_i_fu_689_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_predicate_op177_read_state5;
reg    ap_predicate_op189_read_state5;
reg    ap_predicate_op219_read_state5;
reg    ap_predicate_op231_read_state5;
reg    ap_predicate_op258_read_state5;
reg    ap_predicate_op267_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond461_i_reg_2330_pp0_iter1_reg;
wire   [6:0] j_V_fu_695_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_743_p2;
wire   [1:0] tmp_104_fu_799_p1;
reg   [1:0] tmp_104_reg_2343;
wire   [0:0] brmerge_fu_807_p2;
reg   [0:0] brmerge_reg_2348;
reg   [6:0] k_buf_0_val_3_addr_reg_2361;
reg   [6:0] k_buf_0_val_4_addr_reg_2367;
reg   [6:0] k_buf_0_val_5_addr_reg_2373;
wire   [0:0] or_cond_i_fu_825_p2;
reg   [0:0] or_cond_i_reg_2379_pp0_iter1_reg;
reg   [6:0] k_buf_1_val_3_addr_reg_2383;
reg   [6:0] k_buf_1_val_4_addr_reg_2389;
reg   [6:0] k_buf_1_val_5_addr_reg_2395;
reg   [6:0] k_buf_2_val_3_addr_reg_2401;
reg   [6:0] k_buf_2_val_4_addr_reg_2407;
reg   [6:0] k_buf_2_val_5_addr_reg_2413;
wire   [7:0] src_kernel_win_0_va_34_fu_969_p3;
reg   [7:0] src_kernel_win_0_va_34_reg_2419;
wire   [7:0] src_kernel_win_0_va_35_fu_987_p3;
reg   [7:0] src_kernel_win_0_va_35_reg_2426;
wire   [7:0] src_kernel_win_0_va_36_fu_1005_p3;
reg   [7:0] src_kernel_win_0_va_36_reg_2433;
wire   [7:0] src_kernel_win_1_va_34_fu_1137_p3;
reg   [7:0] src_kernel_win_1_va_34_reg_2439;
wire   [7:0] src_kernel_win_1_va_35_fu_1155_p3;
reg   [7:0] src_kernel_win_1_va_35_reg_2446;
wire   [7:0] src_kernel_win_1_va_36_fu_1173_p3;
reg   [7:0] src_kernel_win_1_va_36_reg_2453;
wire   [7:0] src_kernel_win_2_va_37_fu_1287_p3;
reg   [7:0] src_kernel_win_2_va_37_reg_2459;
wire   [7:0] src_kernel_win_2_va_38_fu_1305_p3;
reg   [7:0] src_kernel_win_2_va_38_reg_2466;
wire   [7:0] src_kernel_win_2_va_39_fu_1323_p3;
reg   [7:0] src_kernel_win_2_va_39_reg_2473;
reg   [0:0] p_Result_s_reg_2479;
wire   [7:0] p_Val2_26_fu_1476_p2;
reg   [7:0] p_Val2_26_reg_2485;
wire   [0:0] not_i_i_fu_1492_p2;
reg   [0:0] not_i_i_reg_2490;
reg   [0:0] p_Result_3_reg_2495;
wire   [7:0] p_Val2_29_fu_1644_p2;
reg   [7:0] p_Val2_29_reg_2501;
wire   [0:0] not_i_i3_fu_1660_p2;
reg   [0:0] not_i_i3_reg_2506;
reg   [0:0] p_Result_4_reg_2511;
wire   [7:0] p_Val2_32_fu_1812_p2;
reg   [7:0] p_Val2_32_reg_2517;
wire   [0:0] not_i_i4_fu_1828_p2;
reg   [0:0] not_i_i4_reg_2522;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state5;
wire   [6:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [6:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [6:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [6:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [6:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [6:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [6:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
wire   [6:0] k_buf_1_val_3_address1;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [6:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
wire   [6:0] k_buf_1_val_4_address1;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [6:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
wire   [6:0] k_buf_1_val_5_address1;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [6:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
wire   [6:0] k_buf_2_val_3_address1;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [6:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
wire   [6:0] k_buf_2_val_4_address1;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [6:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
wire   [6:0] k_buf_2_val_5_address1;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_12_reg_566;
wire   [0:0] tmp_15_fu_605_p2;
reg    ap_block_state1;
reg   [6:0] t_V_reg_577;
wire    ap_CS_fsm_state8;
wire   [63:0] tmp_28_fu_812_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_224;
reg   [7:0] src_kernel_win_0_va_29_fu_228;
reg   [7:0] src_kernel_win_0_va_30_fu_232;
reg   [7:0] src_kernel_win_0_va_31_fu_236;
reg   [7:0] src_kernel_win_0_va_32_fu_240;
reg   [7:0] src_kernel_win_0_va_33_fu_244;
reg   [7:0] src_kernel_win_1_va_fu_248;
reg   [7:0] src_kernel_win_1_va_29_fu_252;
reg   [7:0] src_kernel_win_1_va_30_fu_256;
reg   [7:0] src_kernel_win_1_va_31_fu_260;
reg   [7:0] src_kernel_win_1_va_32_fu_264;
reg   [7:0] src_kernel_win_1_va_33_fu_268;
reg   [7:0] src_kernel_win_2_va_fu_272;
reg   [7:0] src_kernel_win_2_va_29_fu_276;
reg   [7:0] src_kernel_win_2_va_30_fu_280;
reg   [7:0] src_kernel_win_2_va_31_fu_284;
reg   [7:0] src_kernel_win_2_va_32_fu_288;
reg   [7:0] src_kernel_win_2_va_33_fu_292;
reg   [7:0] right_border_buf_0_s_fu_296;
wire   [7:0] col_buf_0_val_0_0_fu_874_p3;
reg   [7:0] right_border_buf_0_29_fu_300;
reg   [7:0] right_border_buf_2_s_fu_304;
reg   [7:0] right_border_buf_0_30_fu_308;
wire   [7:0] col_buf_0_val_1_0_fu_893_p3;
reg   [7:0] right_border_buf_0_31_fu_312;
reg   [7:0] right_border_buf_2_23_fu_316;
wire   [7:0] col_buf_2_val_2_0_fu_1239_p3;
reg   [7:0] right_border_buf_0_32_fu_320;
wire   [7:0] col_buf_0_val_2_0_fu_912_p3;
reg   [7:0] right_border_buf_0_33_fu_324;
reg   [7:0] right_border_buf_2_24_fu_328;
reg   [7:0] right_border_buf_1_s_fu_332;
wire   [7:0] col_buf_1_val_0_0_fu_1042_p3;
reg   [7:0] right_border_buf_1_29_fu_336;
reg   [7:0] right_border_buf_2_25_fu_340;
wire   [7:0] col_buf_2_val_1_0_fu_1220_p3;
reg   [7:0] right_border_buf_1_30_fu_344;
wire   [7:0] col_buf_1_val_1_0_fu_1061_p3;
reg   [7:0] right_border_buf_1_31_fu_348;
reg   [7:0] right_border_buf_2_26_fu_352;
reg   [7:0] right_border_buf_1_32_fu_356;
wire   [7:0] col_buf_1_val_2_0_fu_1080_p3;
reg   [7:0] right_border_buf_1_33_fu_360;
reg   [7:0] right_border_buf_2_27_fu_364;
wire   [7:0] col_buf_2_val_0_0_fu_1201_p3;
wire   [5:0] tmp_fu_635_p4;
wire   [5:0] tmp_101_fu_701_p4;
wire   [7:0] t_V_3_cast_fu_685_p1;
wire   [7:0] ImagLoc_x_fu_717_p2;
wire   [0:0] tmp_102_fu_723_p3;
wire   [0:0] tmp_25_fu_737_p2;
wire   [0:0] rev_fu_731_p2;
wire   [0:0] tmp_103_fu_749_p3;
wire   [7:0] p_assign_1_fu_757_p2;
wire   [7:0] p_p2_i_i_fu_763_p3;
wire   [0:0] tmp_27_fu_771_p2;
wire   [7:0] p_assign_2_fu_777_p2;
wire   [7:0] p_p2_i_i_0_p_assign_2_fu_783_p3;
wire  signed [7:0] x_fu_791_p3;
wire  signed [31:0] x_cast_fu_803_p1;
wire   [0:0] icmp3_fu_711_p2;
wire   [1:0] col_assign_1_fu_857_p2;
wire   [7:0] tmp_57_fu_862_p5;
wire   [7:0] tmp_58_fu_881_p5;
wire   [7:0] tmp_59_fu_900_p5;
wire   [7:0] tmp_60_fu_958_p5;
wire   [7:0] tmp_61_fu_976_p5;
wire   [7:0] tmp_62_fu_994_p5;
wire   [7:0] tmp_64_fu_1030_p5;
wire   [7:0] tmp_65_fu_1049_p5;
wire   [7:0] tmp_66_fu_1068_p5;
wire   [7:0] tmp_67_fu_1126_p5;
wire   [7:0] tmp_68_fu_1144_p5;
wire   [7:0] tmp_69_fu_1162_p5;
wire   [7:0] tmp_71_fu_1189_p5;
wire   [7:0] tmp_72_fu_1208_p5;
wire   [7:0] tmp_73_fu_1227_p5;
wire   [7:0] tmp_74_fu_1276_p5;
wire   [7:0] tmp_75_fu_1294_p5;
wire   [7:0] tmp_76_fu_1312_p5;
wire   [8:0] tmp_144_0_0_2_cast_fu_1343_p1;
wire   [8:0] r_V_0_0_cast_fu_1339_p1;
wire  signed [8:0] sum_V_0_0_2_fu_1346_p2;
wire   [8:0] p_shl_fu_1356_p3;
wire   [9:0] p_shl_cast_fu_1364_p1;
wire  signed [9:0] r_V_2_0_1_fu_1368_p2;
wire   [8:0] r_V_2_0_1_2_fu_1386_p3;
wire   [8:0] r_V_0_2_cast_fu_1402_p1;
wire  signed [8:0] r_V_2_0_2_fu_1406_p2;
wire  signed [10:0] tmp_144_0_2_cast_fu_1412_p1;
wire  signed [10:0] tmp_144_0_1_cast_fu_1374_p1;
wire   [9:0] tmp_144_0_2_2_cast_c_fu_1420_p1;
wire  signed [9:0] sum_V_0_0_2_cast_cas_fu_1352_p1;
wire   [9:0] tmp24_fu_1429_p2;
wire   [10:0] tmp_144_0_1_cast_91_fu_1393_p1;
wire  signed [10:0] tmp24_cast_fu_1435_p1;
wire   [10:0] tmp22_fu_1423_p2;
wire   [10:0] tmp23_fu_1439_p2;
wire   [10:0] p_Val2_s_fu_1445_p2;
wire   [7:0] tmp_108_fu_1382_p1;
wire   [7:0] tmp_107_fu_1378_p1;
wire   [7:0] tmp_110_fu_1416_p1;
wire   [7:0] tmp_109_fu_1397_p2;
wire   [7:0] tmp27_fu_1465_p2;
wire   [7:0] tmp25_fu_1459_p2;
wire   [7:0] tmp26_fu_1470_p2;
wire   [2:0] tmp_63_fu_1482_p4;
wire   [8:0] tmp_144_1_0_2_cast_fu_1511_p1;
wire   [8:0] r_V_1_0_cast_fu_1507_p1;
wire  signed [8:0] sum_V_1_0_2_fu_1514_p2;
wire   [8:0] p_shl3_fu_1524_p3;
wire   [9:0] p_shl3_cast_fu_1532_p1;
wire  signed [9:0] r_V_2_1_1_fu_1536_p2;
wire   [8:0] r_V_2_1_1_2_fu_1554_p3;
wire   [8:0] r_V_1_2_cast_fu_1570_p1;
wire  signed [8:0] r_V_2_1_2_fu_1574_p2;
wire  signed [10:0] tmp_144_1_2_cast_fu_1580_p1;
wire  signed [10:0] tmp_144_1_1_cast_fu_1542_p1;
wire   [9:0] tmp_144_1_2_2_cast_c_fu_1588_p1;
wire  signed [9:0] sum_V_1_0_2_cast_cas_fu_1520_p1;
wire   [9:0] tmp32_fu_1597_p2;
wire   [10:0] tmp_144_1_1_cast_92_fu_1561_p1;
wire  signed [10:0] tmp32_cast_fu_1603_p1;
wire   [10:0] tmp30_fu_1591_p2;
wire   [10:0] tmp31_fu_1607_p2;
wire   [10:0] p_Val2_28_fu_1613_p2;
wire   [7:0] tmp_116_fu_1550_p1;
wire   [7:0] tmp_115_fu_1546_p1;
wire   [7:0] tmp_118_fu_1584_p1;
wire   [7:0] tmp_117_fu_1565_p2;
wire   [7:0] tmp35_fu_1633_p2;
wire   [7:0] tmp33_fu_1627_p2;
wire   [7:0] tmp34_fu_1638_p2;
wire   [2:0] tmp_70_fu_1650_p4;
wire   [8:0] tmp_144_2_0_2_cast_fu_1679_p1;
wire   [8:0] r_V_212_0_cast_fu_1675_p1;
wire  signed [8:0] sum_V_2_0_2_fu_1682_p2;
wire   [8:0] p_shl4_fu_1692_p3;
wire   [9:0] p_shl4_cast_fu_1700_p1;
wire  signed [9:0] r_V_2_2_1_fu_1704_p2;
wire   [8:0] r_V_2_2_1_2_fu_1722_p3;
wire   [8:0] r_V_212_2_cast_fu_1738_p1;
wire  signed [8:0] r_V_2_2_2_fu_1742_p2;
wire  signed [10:0] tmp_144_2_2_cast_fu_1748_p1;
wire  signed [10:0] tmp_144_2_1_cast_fu_1710_p1;
wire   [9:0] tmp_144_2_2_2_cast_c_fu_1756_p1;
wire  signed [9:0] sum_V_2_0_2_cast_cas_fu_1688_p1;
wire   [9:0] tmp40_fu_1765_p2;
wire   [10:0] tmp_144_2_1_cast_93_fu_1729_p1;
wire  signed [10:0] tmp40_cast_fu_1771_p1;
wire   [10:0] tmp38_fu_1759_p2;
wire   [10:0] tmp39_fu_1775_p2;
wire   [10:0] p_Val2_31_fu_1781_p2;
wire   [7:0] tmp_124_fu_1718_p1;
wire   [7:0] tmp_123_fu_1714_p1;
wire   [7:0] tmp_126_fu_1752_p1;
wire   [7:0] tmp_125_fu_1733_p2;
wire   [7:0] tmp43_fu_1801_p2;
wire   [7:0] tmp41_fu_1795_p2;
wire   [7:0] tmp42_fu_1806_p2;
wire   [2:0] tmp_77_fu_1818_p4;
wire   [0:0] tmp_i_i_fu_1942_p2;
wire   [0:0] overflow_fu_1947_p2;
wire   [0:0] tmp_1_i_i_fu_1960_p2;
wire   [7:0] p_mux_i_i_cast_fu_1952_p3;
wire   [0:0] tmp_i_i3_fu_1973_p2;
wire   [0:0] overflow_3_fu_1978_p2;
wire   [0:0] tmp_1_i_i3_fu_1991_p2;
wire   [7:0] p_mux_i_i30_cast_fu_1983_p3;
wire   [0:0] tmp_i_i4_fu_2004_p2;
wire   [0:0] overflow_4_fu_2009_p2;
wire   [0:0] tmp_1_i_i4_fu_2022_p2;
wire   [7:0] p_mux_i_i39_cast_fu_2014_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_111;
reg    ap_enable_state4_pp0_iter0_stage0;
reg    ap_enable_operation_168;
reg    ap_enable_state5_pp0_iter1_stage0;
reg    ap_predicate_op182_store_state5;
reg    ap_enable_operation_182;
reg    ap_predicate_op190_store_state5;
reg    ap_enable_operation_190;
reg    ap_enable_operation_113;
reg    ap_enable_operation_171;
reg    ap_predicate_op180_store_state5;
reg    ap_enable_operation_180;
reg    ap_predicate_op188_store_state5;
reg    ap_enable_operation_188;
reg    ap_enable_operation_115;
reg    ap_enable_operation_174;
reg    ap_predicate_op178_store_state5;
reg    ap_enable_operation_178;
reg    ap_predicate_op187_store_state5;
reg    ap_enable_operation_187;
reg    ap_enable_operation_126;
reg    ap_enable_operation_210;
reg    ap_predicate_op224_store_state5;
reg    ap_enable_operation_224;
reg    ap_predicate_op232_store_state5;
reg    ap_enable_operation_232;
reg    ap_enable_operation_128;
reg    ap_enable_operation_213;
reg    ap_predicate_op222_store_state5;
reg    ap_enable_operation_222;
reg    ap_predicate_op230_store_state5;
reg    ap_enable_operation_230;
reg    ap_enable_operation_130;
reg    ap_enable_operation_216;
reg    ap_predicate_op220_store_state5;
reg    ap_enable_operation_220;
reg    ap_predicate_op229_store_state5;
reg    ap_enable_operation_229;
reg    ap_enable_operation_140;
reg    ap_enable_operation_249;
reg    ap_predicate_op263_store_state5;
reg    ap_enable_operation_263;
reg    ap_predicate_op268_store_state5;
reg    ap_enable_operation_268;
reg    ap_enable_operation_142;
reg    ap_enable_operation_252;
reg    ap_predicate_op261_store_state5;
reg    ap_enable_operation_261;
reg    ap_predicate_op266_store_state5;
reg    ap_enable_operation_266;
reg    ap_enable_operation_144;
reg    ap_enable_operation_255;
reg    ap_predicate_op259_store_state5;
reg    ap_enable_operation_259;
reg    ap_predicate_op265_store_state5;
reg    ap_enable_operation_265;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1426;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_address1),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_address1),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_address1),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_address1),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_address1),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_address1),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U77(
    .din0(right_border_buf_0_s_fu_296),
    .din1(right_border_buf_0_29_fu_300),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_57_fu_862_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U78(
    .din0(right_border_buf_0_30_fu_308),
    .din1(right_border_buf_0_31_fu_312),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_58_fu_881_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U79(
    .din0(right_border_buf_0_32_fu_320),
    .din1(right_border_buf_0_33_fu_324),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_59_fu_900_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U80(
    .din0(col_buf_0_val_0_0_fu_874_p3),
    .din1(col_buf_0_val_1_0_fu_893_p3),
    .din2(col_buf_0_val_2_0_fu_912_p3),
    .din3(tmp_100_reg_2309),
    .dout(tmp_60_fu_958_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U81(
    .din0(col_buf_0_val_0_0_fu_874_p3),
    .din1(col_buf_0_val_1_0_fu_893_p3),
    .din2(col_buf_0_val_2_0_fu_912_p3),
    .din3(row_assign_8_0_1_t_reg_2316),
    .dout(tmp_61_fu_976_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U82(
    .din0(col_buf_0_val_0_0_fu_874_p3),
    .din1(col_buf_0_val_1_0_fu_893_p3),
    .din2(col_buf_0_val_2_0_fu_912_p3),
    .din3(row_assign_8_0_2_t_reg_2323),
    .dout(tmp_62_fu_994_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U83(
    .din0(right_border_buf_1_s_fu_332),
    .din1(right_border_buf_1_29_fu_336),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_64_fu_1030_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U84(
    .din0(right_border_buf_1_30_fu_344),
    .din1(right_border_buf_1_31_fu_348),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_65_fu_1049_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U85(
    .din0(right_border_buf_1_32_fu_356),
    .din1(right_border_buf_1_33_fu_360),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_66_fu_1068_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U86(
    .din0(col_buf_1_val_0_0_fu_1042_p3),
    .din1(col_buf_1_val_1_0_fu_1061_p3),
    .din2(col_buf_1_val_2_0_fu_1080_p3),
    .din3(tmp_100_reg_2309),
    .dout(tmp_67_fu_1126_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U87(
    .din0(col_buf_1_val_0_0_fu_1042_p3),
    .din1(col_buf_1_val_1_0_fu_1061_p3),
    .din2(col_buf_1_val_2_0_fu_1080_p3),
    .din3(row_assign_8_0_1_t_reg_2316),
    .dout(tmp_68_fu_1144_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U88(
    .din0(col_buf_1_val_0_0_fu_1042_p3),
    .din1(col_buf_1_val_1_0_fu_1061_p3),
    .din2(col_buf_1_val_2_0_fu_1080_p3),
    .din3(row_assign_8_0_2_t_reg_2323),
    .dout(tmp_69_fu_1162_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U89(
    .din0(right_border_buf_2_27_fu_364),
    .din1(right_border_buf_2_26_fu_352),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_71_fu_1189_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U90(
    .din0(right_border_buf_2_25_fu_340),
    .din1(right_border_buf_2_24_fu_328),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_72_fu_1208_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U91(
    .din0(right_border_buf_2_23_fu_316),
    .din1(right_border_buf_2_s_fu_304),
    .din2(8'd0),
    .din3(col_assign_1_fu_857_p2),
    .dout(tmp_73_fu_1227_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U92(
    .din0(col_buf_2_val_0_0_fu_1201_p3),
    .din1(col_buf_2_val_1_0_fu_1220_p3),
    .din2(col_buf_2_val_2_0_fu_1239_p3),
    .din3(tmp_100_reg_2309),
    .dout(tmp_74_fu_1276_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U93(
    .din0(col_buf_2_val_0_0_fu_1201_p3),
    .din1(col_buf_2_val_1_0_fu_1220_p3),
    .din2(col_buf_2_val_2_0_fu_1239_p3),
    .din3(row_assign_8_0_1_t_reg_2316),
    .dout(tmp_75_fu_1294_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U94(
    .din0(col_buf_2_val_0_0_fu_1201_p3),
    .din1(col_buf_2_val_1_0_fu_1220_p3),
    .din2(col_buf_2_val_2_0_fu_1239_p3),
    .din3(row_assign_8_0_2_t_reg_2323),
    .dout(tmp_76_fu_1312_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond462_i_fu_611_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond461_i_fu_689_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond462_i_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state5)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((exitcond462_i_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_689_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_3_reg_588 <= j_V_fu_695_p2;
    end else if (((exitcond462_i_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_3_reg_588 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_15_fu_605_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_577 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        t_V_reg_577 <= i_V_reg_2269;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_12_reg_566 <= 2'd0;
    end else if (((tmp_15_fu_605_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_12_reg_566 <= tmp_13_fu_599_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_689_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2348 <= brmerge_fu_807_p2;
        k_buf_0_val_3_addr_reg_2361 <= tmp_28_fu_812_p1;
        k_buf_0_val_4_addr_reg_2367 <= tmp_28_fu_812_p1;
        k_buf_0_val_5_addr_reg_2373 <= tmp_28_fu_812_p1;
        k_buf_1_val_3_addr_reg_2383 <= tmp_28_fu_812_p1;
        k_buf_1_val_4_addr_reg_2389 <= tmp_28_fu_812_p1;
        k_buf_1_val_5_addr_reg_2395 <= tmp_28_fu_812_p1;
        k_buf_2_val_3_addr_reg_2401 <= tmp_28_fu_812_p1;
        k_buf_2_val_4_addr_reg_2407 <= tmp_28_fu_812_p1;
        k_buf_2_val_5_addr_reg_2413 <= tmp_28_fu_812_p1;
        or_cond_i_i_reg_2339 <= or_cond_i_i_fu_743_p2;
        or_cond_i_reg_2379 <= or_cond_i_fu_825_p2;
        tmp_104_reg_2343 <= tmp_104_fu_799_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond461_i_reg_2330 <= exitcond461_i_fu_689_p2;
        exitcond461_i_reg_2330_pp0_iter1_reg <= exitcond461_i_reg_2330;
        or_cond_i_reg_2379_pp0_iter1_reg <= or_cond_i_reg_2379;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2269 <= i_V_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond462_i_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2283 <= icmp_fu_645_p2;
        row_assign_8_0_1_t_reg_2316 <= row_assign_8_0_1_t_fu_673_p2;
        row_assign_8_0_2_t_reg_2323 <= row_assign_8_0_2_t_fu_679_p2;
        tmp_100_reg_2309 <= tmp_100_fu_669_p1;
        tmp_102_0_1_reg_2292 <= tmp_102_0_1_fu_657_p2;
        tmp_18_reg_2274 <= tmp_18_fu_623_p2;
        tmp_20_reg_2288 <= tmp_20_fu_651_p2;
        tmp_21_reg_2296 <= tmp_21_fu_663_p2;
        tmp_58_0_0_not_reg_2278 <= tmp_58_0_0_not_fu_629_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2379_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        not_i_i3_reg_2506 <= not_i_i3_fu_1660_p2;
        not_i_i4_reg_2522 <= not_i_i4_fu_1828_p2;
        not_i_i_reg_2490 <= not_i_i_fu_1492_p2;
        p_Result_3_reg_2495 <= p_Val2_28_fu_1613_p2[32'd10];
        p_Result_4_reg_2511 <= p_Val2_31_fu_1781_p2[32'd10];
        p_Result_s_reg_2479 <= p_Val2_s_fu_1445_p2[32'd10];
        p_Val2_26_reg_2485 <= p_Val2_26_fu_1476_p2;
        p_Val2_29_reg_2501 <= p_Val2_29_fu_1644_p2;
        p_Val2_32_reg_2517 <= p_Val2_32_fu_1812_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond_i_reg_2379_pp0_iter2_reg <= or_cond_i_reg_2379_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_29_fu_300 <= right_border_buf_0_s_fu_296;
        right_border_buf_0_30_fu_308 <= col_buf_0_val_1_0_fu_893_p3;
        right_border_buf_0_31_fu_312 <= right_border_buf_0_30_fu_308;
        right_border_buf_0_32_fu_320 <= col_buf_0_val_2_0_fu_912_p3;
        right_border_buf_0_33_fu_324 <= right_border_buf_0_32_fu_320;
        right_border_buf_0_s_fu_296 <= col_buf_0_val_0_0_fu_874_p3;
        right_border_buf_1_29_fu_336 <= right_border_buf_1_s_fu_332;
        right_border_buf_1_30_fu_344 <= col_buf_1_val_1_0_fu_1061_p3;
        right_border_buf_1_31_fu_348 <= right_border_buf_1_30_fu_344;
        right_border_buf_1_32_fu_356 <= col_buf_1_val_2_0_fu_1080_p3;
        right_border_buf_1_33_fu_360 <= right_border_buf_1_32_fu_356;
        right_border_buf_1_s_fu_332 <= col_buf_1_val_0_0_fu_1042_p3;
        right_border_buf_2_23_fu_316 <= col_buf_2_val_2_0_fu_1239_p3;
        right_border_buf_2_24_fu_328 <= right_border_buf_2_25_fu_340;
        right_border_buf_2_25_fu_340 <= col_buf_2_val_1_0_fu_1220_p3;
        right_border_buf_2_26_fu_352 <= right_border_buf_2_27_fu_364;
        right_border_buf_2_27_fu_364 <= col_buf_2_val_0_0_fu_1201_p3;
        right_border_buf_2_s_fu_304 <= right_border_buf_2_23_fu_316;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2330_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_29_fu_228 <= src_kernel_win_0_va_fu_224;
        src_kernel_win_0_va_30_fu_232 <= src_kernel_win_0_va_35_reg_2426;
        src_kernel_win_0_va_31_fu_236 <= src_kernel_win_0_va_30_fu_232;
        src_kernel_win_0_va_32_fu_240 <= src_kernel_win_0_va_36_reg_2433;
        src_kernel_win_0_va_33_fu_244 <= src_kernel_win_0_va_32_fu_240;
        src_kernel_win_0_va_fu_224 <= src_kernel_win_0_va_34_reg_2419;
        src_kernel_win_1_va_29_fu_252 <= src_kernel_win_1_va_fu_248;
        src_kernel_win_1_va_30_fu_256 <= src_kernel_win_1_va_35_reg_2446;
        src_kernel_win_1_va_31_fu_260 <= src_kernel_win_1_va_30_fu_256;
        src_kernel_win_1_va_32_fu_264 <= src_kernel_win_1_va_36_reg_2453;
        src_kernel_win_1_va_33_fu_268 <= src_kernel_win_1_va_32_fu_264;
        src_kernel_win_1_va_fu_248 <= src_kernel_win_1_va_34_reg_2439;
        src_kernel_win_2_va_29_fu_276 <= src_kernel_win_2_va_fu_272;
        src_kernel_win_2_va_30_fu_280 <= src_kernel_win_2_va_38_reg_2466;
        src_kernel_win_2_va_31_fu_284 <= src_kernel_win_2_va_30_fu_280;
        src_kernel_win_2_va_32_fu_288 <= src_kernel_win_2_va_39_reg_2473;
        src_kernel_win_2_va_33_fu_292 <= src_kernel_win_2_va_32_fu_288;
        src_kernel_win_2_va_fu_272 <= src_kernel_win_2_va_37_reg_2459;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2330 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_34_reg_2419 <= src_kernel_win_0_va_34_fu_969_p3;
        src_kernel_win_0_va_35_reg_2426 <= src_kernel_win_0_va_35_fu_987_p3;
        src_kernel_win_0_va_36_reg_2433 <= src_kernel_win_0_va_36_fu_1005_p3;
        src_kernel_win_1_va_34_reg_2439 <= src_kernel_win_1_va_34_fu_1137_p3;
        src_kernel_win_1_va_35_reg_2446 <= src_kernel_win_1_va_35_fu_1155_p3;
        src_kernel_win_1_va_36_reg_2453 <= src_kernel_win_1_va_36_fu_1173_p3;
        src_kernel_win_2_va_37_reg_2459 <= src_kernel_win_2_va_37_fu_1287_p3;
        src_kernel_win_2_va_38_reg_2466 <= src_kernel_win_2_va_38_fu_1305_p3;
        src_kernel_win_2_va_39_reg_2473 <= src_kernel_win_2_va_39_fu_1323_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond462_i_fu_611_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond462_i_fu_611_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1426)) begin
        if (((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_102_0_1_reg_2292 == 1'd1) & (icmp_reg_2283 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1426)) begin
        if (((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_20_reg_2288 == 1'd1) & (icmp_reg_2283 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1426)) begin
        if (((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1))) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if (((tmp_102_0_1_reg_2292 == 1'd1) & (icmp_reg_2283 == 1'd0))) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1426)) begin
        if (((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1))) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if (((tmp_20_reg_2288 == 1'd1) & (icmp_reg_2283 == 1'd0))) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1426)) begin
        if (((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1))) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if (((tmp_102_0_1_reg_2292 == 1'd1) & (icmp_reg_2283 == 1'd0))) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1426)) begin
        if (((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1))) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if (((tmp_20_reg_2288 == 1'd1) & (icmp_reg_2283 == 1'd0))) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op189_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op177_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op231_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op219_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op267_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op258_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_15_fu_605_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond462_i_fu_611_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_717_p2 = ($signed(8'd255) + $signed(t_V_3_cast_fu_685_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op267_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op258_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op231_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op219_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op189_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op177_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op267_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op258_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op231_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op219_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op189_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op177_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op267_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op258_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op231_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op219_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op189_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op177_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op267_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op258_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op231_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op219_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op189_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op177_read_state5 == 1'b1)));
end

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter3 = (((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2379_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1426 = ((or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_operation_111 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_113 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_115 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_126 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_128 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_130 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_140 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_142 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_144 = (exitcond461_i_fu_689_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_168 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_171 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_174 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_178 = (ap_predicate_op178_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_180 = (ap_predicate_op180_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_182 = (ap_predicate_op182_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_187 = (ap_predicate_op187_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_188 = (ap_predicate_op188_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_190 = (ap_predicate_op190_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_210 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_213 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_216 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_220 = (ap_predicate_op220_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_222 = (ap_predicate_op222_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_224 = (ap_predicate_op224_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_229 = (ap_predicate_op229_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_230 = (ap_predicate_op230_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_232 = (ap_predicate_op232_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_249 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_252 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_255 = (exitcond461_i_reg_2330 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_259 = (ap_predicate_op259_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_261 = (ap_predicate_op261_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_263 = (ap_predicate_op263_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_265 = (ap_predicate_op265_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_266 = (ap_predicate_op266_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_268 = (ap_predicate_op268_store_state5 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter0_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op177_read_state5 = ((or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op178_store_state5 = ((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_store_state5 = ((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op182_store_state5 = ((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op187_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op188_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op189_read_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op190_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op219_read_state5 = ((or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op220_store_state5 = ((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op222_store_state5 = ((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op224_store_state5 = ((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op229_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op230_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op231_read_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op232_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op258_read_state5 = ((or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op259_store_state5 = ((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op261_store_state5 = ((tmp_102_0_1_reg_2292 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op263_store_state5 = ((tmp_20_reg_2288 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (icmp_reg_2283 == 1'd0) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op265_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op266_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op267_read_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

always @ (*) begin
    ap_predicate_op268_store_state5 = ((tmp_18_reg_2274 == 1'd1) & (icmp_reg_2283 == 1'd1) & (or_cond_i_i_reg_2339 == 1'd1) & (exitcond461_i_reg_2330 == 1'd0));
end

assign brmerge_fu_807_p2 = (tmp_58_0_0_not_reg_2278 | tmp_25_fu_737_p2);

assign col_assign_1_fu_857_p2 = (tmp_104_reg_2343 ^ 2'd3);

assign col_buf_0_val_0_0_fu_874_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_57_fu_862_p5);

assign col_buf_0_val_1_0_fu_893_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_58_fu_881_p5);

assign col_buf_0_val_2_0_fu_912_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_59_fu_900_p5);

assign col_buf_1_val_0_0_fu_1042_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_64_fu_1030_p5);

assign col_buf_1_val_1_0_fu_1061_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_65_fu_1049_p5);

assign col_buf_1_val_2_0_fu_1080_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_66_fu_1068_p5);

assign col_buf_2_val_0_0_fu_1201_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_71_fu_1189_p5);

assign col_buf_2_val_1_0_fu_1220_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_72_fu_1208_p5);

assign col_buf_2_val_2_0_fu_1239_p3 = ((brmerge_reg_2348[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_73_fu_1227_p5);

assign exitcond461_i_fu_689_p2 = ((t_V_3_reg_588 == 7'd102) ? 1'b1 : 1'b0);

assign exitcond462_i_fu_611_p2 = ((t_V_reg_577 == 7'd102) ? 1'b1 : 1'b0);

assign i_V_fu_617_p2 = (t_V_reg_577 + 7'd1);

assign icmp3_fu_711_p2 = ((tmp_101_fu_701_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_fu_645_p2 = ((tmp_fu_635_p4 != 6'd0) ? 1'b1 : 1'b0);

assign j_V_fu_695_p2 = (t_V_3_reg_588 + 7'd1);

assign k_buf_0_val_3_address0 = tmp_28_fu_812_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_2361;

assign k_buf_0_val_4_address0 = tmp_28_fu_812_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_2367;

assign k_buf_0_val_5_address0 = tmp_28_fu_812_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_2373;

assign k_buf_1_val_3_address0 = tmp_28_fu_812_p1;

assign k_buf_1_val_3_address1 = k_buf_1_val_3_addr_reg_2383;

assign k_buf_1_val_4_address0 = tmp_28_fu_812_p1;

assign k_buf_1_val_4_address1 = k_buf_1_val_4_addr_reg_2389;

assign k_buf_1_val_5_address0 = tmp_28_fu_812_p1;

assign k_buf_1_val_5_address1 = k_buf_1_val_5_addr_reg_2395;

assign k_buf_2_val_3_address0 = tmp_28_fu_812_p1;

assign k_buf_2_val_3_address1 = k_buf_2_val_3_addr_reg_2401;

assign k_buf_2_val_4_address0 = tmp_28_fu_812_p1;

assign k_buf_2_val_4_address1 = k_buf_2_val_4_addr_reg_2407;

assign k_buf_2_val_5_address0 = tmp_28_fu_812_p1;

assign k_buf_2_val_5_address1 = k_buf_2_val_5_addr_reg_2413;

assign not_i_i3_fu_1660_p2 = ((tmp_70_fu_1650_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i4_fu_1828_p2 = ((tmp_77_fu_1818_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_fu_1492_p2 = ((tmp_63_fu_1482_p4 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i_fu_825_p2 = (icmp_reg_2283 & icmp3_fu_711_p2);

assign or_cond_i_i_fu_743_p2 = (tmp_25_fu_737_p2 & rev_fu_731_p2);

assign overflow_3_fu_1978_p2 = (tmp_i_i3_fu_1973_p2 & not_i_i3_reg_2506);

assign overflow_4_fu_2009_p2 = (tmp_i_i4_fu_2004_p2 & not_i_i4_reg_2522);

assign overflow_fu_1947_p2 = (tmp_i_i_fu_1942_p2 & not_i_i_reg_2490);

assign p_Val2_26_fu_1476_p2 = (tmp25_fu_1459_p2 + tmp26_fu_1470_p2);

assign p_Val2_28_fu_1613_p2 = (tmp30_fu_1591_p2 + tmp31_fu_1607_p2);

assign p_Val2_29_fu_1644_p2 = (tmp33_fu_1627_p2 + tmp34_fu_1638_p2);

assign p_Val2_31_fu_1781_p2 = (tmp38_fu_1759_p2 + tmp39_fu_1775_p2);

assign p_Val2_32_fu_1812_p2 = (tmp41_fu_1795_p2 + tmp42_fu_1806_p2);

assign p_Val2_s_fu_1445_p2 = (tmp22_fu_1423_p2 + tmp23_fu_1439_p2);

assign p_assign_1_fu_757_p2 = (8'd1 - t_V_3_cast_fu_685_p1);

assign p_assign_2_fu_777_p2 = ($signed(8'd198) - $signed(p_p2_i_i_fu_763_p3));

assign p_dst_data_stream_0_V_din = ((tmp_1_i_i_fu_1960_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1952_p3 : p_Val2_26_reg_2485);

assign p_dst_data_stream_1_V_din = ((tmp_1_i_i3_fu_1991_p2[0:0] === 1'b1) ? p_mux_i_i30_cast_fu_1983_p3 : p_Val2_29_reg_2501);

assign p_dst_data_stream_2_V_din = ((tmp_1_i_i4_fu_2022_p2[0:0] === 1'b1) ? p_mux_i_i39_cast_fu_2014_p3 : p_Val2_32_reg_2517);

assign p_mux_i_i30_cast_fu_1983_p3 = ((tmp_i_i3_fu_1973_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i39_cast_fu_2014_p3 = ((tmp_i_i4_fu_2004_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_1952_p3 = ((tmp_i_i_fu_1942_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i_i_0_p_assign_2_fu_783_p3 = ((tmp_27_fu_771_p2[0:0] === 1'b1) ? p_p2_i_i_fu_763_p3 : p_assign_2_fu_777_p2);

assign p_p2_i_i_fu_763_p3 = ((tmp_103_fu_749_p3[0:0] === 1'b1) ? p_assign_1_fu_757_p2 : ImagLoc_x_fu_717_p2);

assign p_shl3_cast_fu_1532_p1 = p_shl3_fu_1524_p3;

assign p_shl3_fu_1524_p3 = {{src_kernel_win_1_va_31_fu_260}, {1'd0}};

assign p_shl4_cast_fu_1700_p1 = p_shl4_fu_1692_p3;

assign p_shl4_fu_1692_p3 = {{src_kernel_win_2_va_31_fu_284}, {1'd0}};

assign p_shl_cast_fu_1364_p1 = p_shl_fu_1356_p3;

assign p_shl_fu_1356_p3 = {{src_kernel_win_0_va_31_fu_236}, {1'd0}};

assign r_V_0_0_cast_fu_1339_p1 = src_kernel_win_0_va_33_fu_244;

assign r_V_0_2_cast_fu_1402_p1 = src_kernel_win_0_va_29_fu_228;

assign r_V_1_0_cast_fu_1507_p1 = src_kernel_win_1_va_33_fu_268;

assign r_V_1_2_cast_fu_1570_p1 = src_kernel_win_1_va_29_fu_252;

assign r_V_212_0_cast_fu_1675_p1 = src_kernel_win_2_va_33_fu_292;

assign r_V_212_2_cast_fu_1738_p1 = src_kernel_win_2_va_29_fu_276;

assign r_V_2_0_1_2_fu_1386_p3 = {{src_kernel_win_0_va_35_reg_2426}, {1'd0}};

assign r_V_2_0_1_fu_1368_p2 = (10'd0 - p_shl_cast_fu_1364_p1);

assign r_V_2_0_2_fu_1406_p2 = (9'd0 - r_V_0_2_cast_fu_1402_p1);

assign r_V_2_1_1_2_fu_1554_p3 = {{src_kernel_win_1_va_35_reg_2446}, {1'd0}};

assign r_V_2_1_1_fu_1536_p2 = (10'd0 - p_shl3_cast_fu_1532_p1);

assign r_V_2_1_2_fu_1574_p2 = (9'd0 - r_V_1_2_cast_fu_1570_p1);

assign r_V_2_2_1_2_fu_1722_p3 = {{src_kernel_win_2_va_38_reg_2466}, {1'd0}};

assign r_V_2_2_1_fu_1704_p2 = (10'd0 - p_shl4_cast_fu_1700_p1);

assign r_V_2_2_2_fu_1742_p2 = (9'd0 - r_V_212_2_cast_fu_1738_p1);

assign rev_fu_731_p2 = (tmp_102_fu_723_p3 ^ 1'd1);

assign row_assign_8_0_1_t_fu_673_p2 = (tmp_100_fu_669_p1 ^ 2'd1);

assign row_assign_8_0_2_t_fu_679_p2 = ($signed(2'd2) - $signed(tmp_100_fu_669_p1));

assign src_kernel_win_0_va_34_fu_969_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_60_fu_958_p5 : col_buf_0_val_0_0_fu_874_p3);

assign src_kernel_win_0_va_35_fu_987_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_61_fu_976_p5 : col_buf_0_val_1_0_fu_893_p3);

assign src_kernel_win_0_va_36_fu_1005_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_62_fu_994_p5 : col_buf_0_val_2_0_fu_912_p3);

assign src_kernel_win_1_va_34_fu_1137_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_67_fu_1126_p5 : col_buf_1_val_0_0_fu_1042_p3);

assign src_kernel_win_1_va_35_fu_1155_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_68_fu_1144_p5 : col_buf_1_val_1_0_fu_1061_p3);

assign src_kernel_win_1_va_36_fu_1173_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_69_fu_1162_p5 : col_buf_1_val_2_0_fu_1080_p3);

assign src_kernel_win_2_va_37_fu_1287_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_74_fu_1276_p5 : col_buf_2_val_0_0_fu_1201_p3);

assign src_kernel_win_2_va_38_fu_1305_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_75_fu_1294_p5 : col_buf_2_val_1_0_fu_1220_p3);

assign src_kernel_win_2_va_39_fu_1323_p3 = ((tmp_21_reg_2296[0:0] === 1'b1) ? tmp_76_fu_1312_p5 : col_buf_2_val_2_0_fu_1239_p3);

assign sum_V_0_0_2_cast_cas_fu_1352_p1 = sum_V_0_0_2_fu_1346_p2;

assign sum_V_0_0_2_fu_1346_p2 = (tmp_144_0_0_2_cast_fu_1343_p1 - r_V_0_0_cast_fu_1339_p1);

assign sum_V_1_0_2_cast_cas_fu_1520_p1 = sum_V_1_0_2_fu_1514_p2;

assign sum_V_1_0_2_fu_1514_p2 = (tmp_144_1_0_2_cast_fu_1511_p1 - r_V_1_0_cast_fu_1507_p1);

assign sum_V_2_0_2_cast_cas_fu_1688_p1 = sum_V_2_0_2_fu_1682_p2;

assign sum_V_2_0_2_fu_1682_p2 = (tmp_144_2_0_2_cast_fu_1679_p1 - r_V_212_0_cast_fu_1675_p1);

assign t_V_3_cast_fu_685_p1 = t_V_3_reg_588;

assign tmp22_fu_1423_p2 = ($signed(tmp_144_0_2_cast_fu_1412_p1) + $signed(tmp_144_0_1_cast_fu_1374_p1));

assign tmp23_fu_1439_p2 = ($signed(tmp_144_0_1_cast_91_fu_1393_p1) + $signed(tmp24_cast_fu_1435_p1));

assign tmp24_cast_fu_1435_p1 = $signed(tmp24_fu_1429_p2);

assign tmp24_fu_1429_p2 = ($signed(tmp_144_0_2_2_cast_c_fu_1420_p1) + $signed(sum_V_0_0_2_cast_cas_fu_1352_p1));

assign tmp25_fu_1459_p2 = (tmp_108_fu_1382_p1 + tmp_107_fu_1378_p1);

assign tmp26_fu_1470_p2 = (tmp_109_fu_1397_p2 + tmp27_fu_1465_p2);

assign tmp27_fu_1465_p2 = (src_kernel_win_0_va_34_reg_2419 + tmp_110_fu_1416_p1);

assign tmp30_fu_1591_p2 = ($signed(tmp_144_1_2_cast_fu_1580_p1) + $signed(tmp_144_1_1_cast_fu_1542_p1));

assign tmp31_fu_1607_p2 = ($signed(tmp_144_1_1_cast_92_fu_1561_p1) + $signed(tmp32_cast_fu_1603_p1));

assign tmp32_cast_fu_1603_p1 = $signed(tmp32_fu_1597_p2);

assign tmp32_fu_1597_p2 = ($signed(tmp_144_1_2_2_cast_c_fu_1588_p1) + $signed(sum_V_1_0_2_cast_cas_fu_1520_p1));

assign tmp33_fu_1627_p2 = (tmp_116_fu_1550_p1 + tmp_115_fu_1546_p1);

assign tmp34_fu_1638_p2 = (tmp_117_fu_1565_p2 + tmp35_fu_1633_p2);

assign tmp35_fu_1633_p2 = (src_kernel_win_1_va_34_reg_2439 + tmp_118_fu_1584_p1);

assign tmp38_fu_1759_p2 = ($signed(tmp_144_2_2_cast_fu_1748_p1) + $signed(tmp_144_2_1_cast_fu_1710_p1));

assign tmp39_fu_1775_p2 = ($signed(tmp_144_2_1_cast_93_fu_1729_p1) + $signed(tmp40_cast_fu_1771_p1));

assign tmp40_cast_fu_1771_p1 = $signed(tmp40_fu_1765_p2);

assign tmp40_fu_1765_p2 = ($signed(tmp_144_2_2_2_cast_c_fu_1756_p1) + $signed(sum_V_2_0_2_cast_cas_fu_1688_p1));

assign tmp41_fu_1795_p2 = (tmp_124_fu_1718_p1 + tmp_123_fu_1714_p1);

assign tmp42_fu_1806_p2 = (tmp_125_fu_1733_p2 + tmp43_fu_1801_p2);

assign tmp43_fu_1801_p2 = (src_kernel_win_2_va_37_reg_2459 + tmp_126_fu_1752_p1);

assign tmp_100_fu_669_p1 = t_V_reg_577[1:0];

assign tmp_101_fu_701_p4 = {{t_V_3_reg_588[6:1]}};

assign tmp_102_0_1_fu_657_p2 = ((t_V_reg_577 == 7'd0) ? 1'b1 : 1'b0);

assign tmp_102_fu_723_p3 = ImagLoc_x_fu_717_p2[32'd7];

assign tmp_103_fu_749_p3 = ImagLoc_x_fu_717_p2[32'd7];

assign tmp_104_fu_799_p1 = x_fu_791_p3[1:0];

assign tmp_107_fu_1378_p1 = sum_V_0_0_2_fu_1346_p2[7:0];

assign tmp_108_fu_1382_p1 = r_V_2_0_1_fu_1368_p2[7:0];

assign tmp_109_fu_1397_p2 = src_kernel_win_0_va_35_reg_2426 << 8'd1;

assign tmp_110_fu_1416_p1 = r_V_2_0_2_fu_1406_p2[7:0];

assign tmp_115_fu_1546_p1 = sum_V_1_0_2_fu_1514_p2[7:0];

assign tmp_116_fu_1550_p1 = r_V_2_1_1_fu_1536_p2[7:0];

assign tmp_117_fu_1565_p2 = src_kernel_win_1_va_35_reg_2446 << 8'd1;

assign tmp_118_fu_1584_p1 = r_V_2_1_2_fu_1574_p2[7:0];

assign tmp_123_fu_1714_p1 = sum_V_2_0_2_fu_1682_p2[7:0];

assign tmp_124_fu_1718_p1 = r_V_2_2_1_fu_1704_p2[7:0];

assign tmp_125_fu_1733_p2 = src_kernel_win_2_va_38_reg_2466 << 8'd1;

assign tmp_126_fu_1752_p1 = r_V_2_2_2_fu_1742_p2[7:0];

assign tmp_13_fu_599_p2 = (tmp_12_reg_566 + 2'd1);

assign tmp_144_0_0_2_cast_fu_1343_p1 = src_kernel_win_0_va_36_reg_2433;

assign tmp_144_0_1_cast_91_fu_1393_p1 = r_V_2_0_1_2_fu_1386_p3;

assign tmp_144_0_1_cast_fu_1374_p1 = r_V_2_0_1_fu_1368_p2;

assign tmp_144_0_2_2_cast_c_fu_1420_p1 = src_kernel_win_0_va_34_reg_2419;

assign tmp_144_0_2_cast_fu_1412_p1 = r_V_2_0_2_fu_1406_p2;

assign tmp_144_1_0_2_cast_fu_1511_p1 = src_kernel_win_1_va_36_reg_2453;

assign tmp_144_1_1_cast_92_fu_1561_p1 = r_V_2_1_1_2_fu_1554_p3;

assign tmp_144_1_1_cast_fu_1542_p1 = r_V_2_1_1_fu_1536_p2;

assign tmp_144_1_2_2_cast_c_fu_1588_p1 = src_kernel_win_1_va_34_reg_2439;

assign tmp_144_1_2_cast_fu_1580_p1 = r_V_2_1_2_fu_1574_p2;

assign tmp_144_2_0_2_cast_fu_1679_p1 = src_kernel_win_2_va_39_reg_2473;

assign tmp_144_2_1_cast_93_fu_1729_p1 = r_V_2_2_1_2_fu_1722_p3;

assign tmp_144_2_1_cast_fu_1710_p1 = r_V_2_2_1_fu_1704_p2;

assign tmp_144_2_2_2_cast_c_fu_1756_p1 = src_kernel_win_2_va_37_reg_2459;

assign tmp_144_2_2_cast_fu_1748_p1 = r_V_2_2_2_fu_1742_p2;

assign tmp_15_fu_605_p2 = ((tmp_12_reg_566 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_18_fu_623_p2 = ((t_V_reg_577 < 7'd100) ? 1'b1 : 1'b0);

assign tmp_1_i_i3_fu_1991_p2 = (p_Result_3_reg_2495 | overflow_3_fu_1978_p2);

assign tmp_1_i_i4_fu_2022_p2 = (p_Result_4_reg_2511 | overflow_4_fu_2009_p2);

assign tmp_1_i_i_fu_1960_p2 = (p_Result_s_reg_2479 | overflow_fu_1947_p2);

assign tmp_20_fu_651_p2 = ((t_V_reg_577 == 7'd1) ? 1'b1 : 1'b0);

assign tmp_21_fu_663_p2 = ((t_V_reg_577 > 7'd100) ? 1'b1 : 1'b0);

assign tmp_25_fu_737_p2 = (($signed(ImagLoc_x_fu_717_p2) < $signed(8'd100)) ? 1'b1 : 1'b0);

assign tmp_27_fu_771_p2 = (($signed(p_p2_i_i_fu_763_p3) < $signed(8'd100)) ? 1'b1 : 1'b0);

assign tmp_28_fu_812_p1 = $unsigned(x_cast_fu_803_p1);

assign tmp_58_0_0_not_fu_629_p2 = (tmp_18_fu_623_p2 ^ 1'd1);

assign tmp_63_fu_1482_p4 = {{p_Val2_s_fu_1445_p2[10:8]}};

assign tmp_70_fu_1650_p4 = {{p_Val2_28_fu_1613_p2[10:8]}};

assign tmp_77_fu_1818_p4 = {{p_Val2_31_fu_1781_p2[10:8]}};

assign tmp_fu_635_p4 = {{t_V_reg_577[6:1]}};

assign tmp_i_i3_fu_1973_p2 = (p_Result_3_reg_2495 ^ 1'd1);

assign tmp_i_i4_fu_2004_p2 = (p_Result_4_reg_2511 ^ 1'd1);

assign tmp_i_i_fu_1942_p2 = (p_Result_s_reg_2479 ^ 1'd1);

assign x_cast_fu_803_p1 = x_fu_791_p3;

assign x_fu_791_p3 = ((or_cond_i_i_fu_743_p2[0:0] === 1'b1) ? ImagLoc_x_fu_717_p2 : p_p2_i_i_0_p_assign_2_fu_783_p3);

endmodule //Filter2D
