// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D93 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_src_data_stream_V1_dout,
        p_src_data_stream_V1_empty_n,
        p_src_data_stream_V1_read,
        p_src_data_stream_V2_dout,
        p_src_data_stream_V2_empty_n,
        p_src_data_stream_V2_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_dst_data_stream_V3_din,
        p_dst_data_stream_V3_full_n,
        p_dst_data_stream_V3_write,
        p_dst_data_stream_V4_din,
        p_dst_data_stream_V4_full_n,
        p_dst_data_stream_V4_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state8 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
input  [7:0] p_src_data_stream_V1_dout;
input   p_src_data_stream_V1_empty_n;
output   p_src_data_stream_V1_read;
input  [7:0] p_src_data_stream_V2_dout;
input   p_src_data_stream_V2_empty_n;
output   p_src_data_stream_V2_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
output  [7:0] p_dst_data_stream_V3_din;
input   p_dst_data_stream_V3_full_n;
output   p_dst_data_stream_V3_write;
output  [7:0] p_dst_data_stream_V4_din;
input   p_dst_data_stream_V4_full_n;
output   p_dst_data_stream_V4_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg p_src_data_stream_V_read;
reg p_src_data_stream_V1_read;
reg p_src_data_stream_V2_read;
reg p_dst_data_stream_V_write;
reg p_dst_data_stream_V3_write;
reg p_dst_data_stream_V4_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    p_src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond461_i_reg_2239;
reg   [0:0] or_cond_i_i_reg_2248;
reg   [0:0] icmp_reg_2202;
reg   [0:0] tmp_1_reg_2193;
reg    p_src_data_stream_V1_blk_n;
reg    p_src_data_stream_V2_blk_n;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] or_cond_i_reg_2288;
reg   [0:0] or_cond_i_reg_2288_pp0_iter2_reg;
reg    p_dst_data_stream_V3_blk_n;
reg    p_dst_data_stream_V4_blk_n;
reg   [6:0] t_V_2_reg_564;
wire   [1:0] tmp_6_fu_575_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond462_i_fu_587_p2;
wire    ap_CS_fsm_state3;
wire   [6:0] i_V_fu_593_p2;
reg   [6:0] i_V_reg_2188;
wire   [0:0] tmp_1_fu_599_p2;
wire   [0:0] tmp_58_0_0_not_fu_605_p2;
reg   [0:0] tmp_58_0_0_not_reg_2197;
wire   [0:0] icmp_fu_621_p2;
wire   [0:0] tmp_9_fu_627_p2;
reg   [0:0] tmp_9_reg_2207;
wire   [0:0] tmp_102_0_1_fu_633_p2;
reg   [0:0] tmp_102_0_1_reg_2211;
wire   [0:0] tmp_8_fu_639_p2;
reg   [0:0] tmp_8_reg_2215;
wire   [1:0] tmp_37_fu_645_p1;
reg   [1:0] tmp_37_reg_2225;
wire   [1:0] row_assign_8_0_2_t_fu_649_p2;
reg   [1:0] row_assign_8_0_2_t_reg_2232;
wire   [0:0] exitcond461_i_fu_659_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_predicate_op170_read_state5;
reg    ap_predicate_op182_read_state5;
reg    ap_predicate_op210_read_state5;
reg    ap_predicate_op222_read_state5;
reg    ap_predicate_op247_read_state5;
reg    ap_predicate_op256_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond461_i_reg_2239_pp0_iter1_reg;
wire   [6:0] j_V_fu_665_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_713_p2;
wire   [1:0] tmp_49_fu_769_p1;
reg   [1:0] tmp_49_reg_2252;
wire   [0:0] brmerge_fu_777_p2;
reg   [0:0] brmerge_reg_2257;
reg   [6:0] k_buf_0_val_3_addr_reg_2270;
reg   [6:0] k_buf_0_val_4_addr_reg_2276;
reg   [6:0] k_buf_0_val_5_addr_reg_2282;
wire   [0:0] or_cond_i_fu_795_p2;
reg   [0:0] or_cond_i_reg_2288_pp0_iter1_reg;
reg   [6:0] k_buf_1_val_3_addr_reg_2292;
reg   [6:0] k_buf_1_val_4_addr_reg_2298;
reg   [6:0] k_buf_1_val_5_addr_reg_2304;
reg   [6:0] k_buf_2_val_3_addr_reg_2310;
reg   [6:0] k_buf_2_val_4_addr_reg_2316;
reg   [6:0] k_buf_2_val_5_addr_reg_2322;
wire   [7:0] src_kernel_win_0_va_4_fu_939_p3;
reg   [7:0] src_kernel_win_0_va_4_reg_2328;
wire   [7:0] src_kernel_win_0_va_5_fu_957_p3;
reg   [7:0] src_kernel_win_0_va_5_reg_2334;
wire   [7:0] src_kernel_win_1_va_4_fu_1089_p3;
reg   [7:0] src_kernel_win_1_va_4_reg_2341;
wire   [7:0] src_kernel_win_1_va_5_fu_1107_p3;
reg   [7:0] src_kernel_win_1_va_5_reg_2347;
wire   [7:0] src_kernel_win_2_va_6_fu_1221_p3;
reg   [7:0] src_kernel_win_2_va_6_reg_2354;
wire   [7:0] src_kernel_win_2_va_7_fu_1239_p3;
reg   [7:0] src_kernel_win_2_va_7_reg_2360;
wire   [7:0] tmp_56_fu_1354_p1;
reg   [7:0] tmp_56_reg_2367;
wire   [7:0] tmp_58_fu_1371_p1;
reg   [7:0] tmp_58_reg_2372;
reg   [0:0] p_Result_s_reg_2377;
wire   [7:0] tmp24_fu_1405_p2;
reg   [7:0] tmp24_reg_2383;
wire   [0:0] not_i_i_fu_1421_p2;
reg   [0:0] not_i_i_reg_2388;
wire   [7:0] tmp_65_fu_1535_p1;
reg   [7:0] tmp_65_reg_2393;
wire   [7:0] tmp_66_fu_1552_p1;
reg   [7:0] tmp_66_reg_2398;
reg   [0:0] p_Result_1_reg_2403;
wire   [7:0] tmp30_fu_1586_p2;
reg   [7:0] tmp30_reg_2409;
wire   [0:0] not_i_i1_fu_1602_p2;
reg   [0:0] not_i_i1_reg_2414;
wire   [7:0] tmp_73_fu_1716_p1;
reg   [7:0] tmp_73_reg_2419;
wire   [7:0] tmp_74_fu_1733_p1;
reg   [7:0] tmp_74_reg_2424;
reg   [0:0] p_Result_2_reg_2429;
wire   [7:0] tmp36_fu_1767_p2;
reg   [7:0] tmp36_reg_2435;
wire   [0:0] not_i_i2_fu_1783_p2;
reg   [0:0] not_i_i2_reg_2440;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state5;
wire   [6:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [6:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [6:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [6:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [6:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [6:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [6:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
wire   [6:0] k_buf_1_val_3_address1;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [6:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
wire   [6:0] k_buf_1_val_4_address1;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [6:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
wire   [6:0] k_buf_1_val_5_address1;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [6:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
wire   [6:0] k_buf_2_val_3_address1;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [6:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
wire   [6:0] k_buf_2_val_4_address1;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [6:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
wire   [6:0] k_buf_2_val_5_address1;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_5_reg_542;
wire   [0:0] tmp_7_fu_581_p2;
reg    ap_block_state1;
reg   [6:0] t_V_reg_553;
wire    ap_CS_fsm_state8;
wire   [63:0] tmp_13_fu_782_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_224;
reg   [7:0] src_kernel_win_0_va_1_fu_228;
reg   [7:0] src_kernel_win_0_va_2_fu_232;
reg   [7:0] src_kernel_win_0_va_3_fu_236;
reg   [7:0] src_kernel_win_1_va_fu_240;
reg   [7:0] src_kernel_win_1_va_1_fu_244;
reg   [7:0] src_kernel_win_1_va_2_fu_248;
reg   [7:0] src_kernel_win_1_va_3_fu_252;
reg   [7:0] src_kernel_win_2_va_fu_256;
reg   [7:0] src_kernel_win_2_va_1_fu_260;
reg   [7:0] src_kernel_win_2_va_2_fu_264;
reg   [7:0] src_kernel_win_2_va_3_fu_268;
reg   [7:0] right_border_buf_0_s_fu_272;
wire   [7:0] col_buf_0_val_0_0_fu_844_p3;
reg   [7:0] right_border_buf_0_1_fu_276;
reg   [7:0] right_border_buf_2_s_fu_280;
reg   [7:0] right_border_buf_0_2_fu_284;
wire   [7:0] col_buf_0_val_1_0_fu_863_p3;
reg   [7:0] right_border_buf_0_3_fu_288;
reg   [7:0] right_border_buf_2_1_fu_292;
wire   [7:0] col_buf_2_val_2_0_fu_1173_p3;
reg   [7:0] right_border_buf_0_4_fu_296;
wire   [7:0] col_buf_0_val_2_0_fu_882_p3;
reg   [7:0] right_border_buf_0_5_fu_300;
reg   [7:0] right_border_buf_2_2_fu_304;
reg   [7:0] right_border_buf_1_s_fu_308;
wire   [7:0] col_buf_1_val_0_0_fu_994_p3;
reg   [7:0] right_border_buf_1_1_fu_312;
reg   [7:0] right_border_buf_2_3_fu_316;
wire   [7:0] col_buf_2_val_1_0_fu_1154_p3;
reg   [7:0] right_border_buf_1_2_fu_320;
wire   [7:0] col_buf_1_val_1_0_fu_1013_p3;
reg   [7:0] right_border_buf_1_3_fu_324;
reg   [7:0] right_border_buf_2_4_fu_328;
reg   [7:0] right_border_buf_1_4_fu_332;
wire   [7:0] col_buf_1_val_2_0_fu_1032_p3;
reg   [7:0] right_border_buf_1_5_fu_336;
reg   [7:0] right_border_buf_2_5_fu_340;
wire   [7:0] col_buf_2_val_0_0_fu_1135_p3;
wire   [5:0] tmp_fu_611_p4;
wire   [5:0] tmp_38_fu_671_p4;
wire   [7:0] t_V_2_cast_fu_655_p1;
wire   [7:0] ImagLoc_x_fu_687_p2;
wire   [0:0] tmp_40_fu_693_p3;
wire   [0:0] tmp_11_fu_707_p2;
wire   [0:0] rev_fu_701_p2;
wire   [0:0] tmp_41_fu_719_p3;
wire   [7:0] p_assign_1_fu_727_p2;
wire   [7:0] p_p2_i_i_fu_733_p3;
wire   [0:0] tmp_12_fu_741_p2;
wire   [7:0] p_assign_2_fu_747_p2;
wire   [7:0] p_p2_i_i_0_p_assign_2_fu_753_p3;
wire  signed [7:0] x_fu_761_p3;
wire  signed [31:0] x_cast_fu_773_p1;
wire   [0:0] icmp1_fu_681_p2;
wire   [1:0] col_assign_1_fu_827_p2;
wire   [7:0] tmp_14_fu_832_p5;
wire   [7:0] tmp_15_fu_851_p5;
wire   [7:0] tmp_16_fu_870_p5;
wire   [7:0] tmp_17_fu_928_p5;
wire   [7:0] tmp_18_fu_946_p5;
wire   [7:0] tmp_22_fu_982_p5;
wire   [7:0] tmp_23_fu_1001_p5;
wire   [7:0] tmp_24_fu_1020_p5;
wire   [7:0] tmp_25_fu_1078_p5;
wire   [7:0] tmp_26_fu_1096_p5;
wire   [7:0] tmp_30_fu_1123_p5;
wire   [7:0] tmp_31_fu_1142_p5;
wire   [7:0] tmp_32_fu_1161_p5;
wire   [7:0] tmp_33_fu_1210_p5;
wire   [7:0] tmp_34_fu_1228_p5;
wire   [8:0] r_V_2_0_0_1_fu_1262_p3;
wire   [8:0] tmp_144_0_0_2_cast_c_fu_1274_p1;
wire   [8:0] tmp_144_0_0_cast_cas_fu_1258_p1;
wire   [8:0] tmp20_fu_1282_p2;
wire   [9:0] tmp_144_0_0_cast_fu_1270_p1;
wire   [9:0] tmp20_cast_fu_1288_p1;
wire   [9:0] sum_V_0_1_2_fu_1298_p2;
wire   [8:0] r_V_0_2_cast_fu_1308_p1;
wire  signed [8:0] r_V_2_0_2_fu_1312_p2;
wire   [7:0] tmp_19_fu_1277_p2;
wire   [7:0] tmp_53_fu_1292_p2;
wire   [8:0] p_shl_fu_1332_p3;
wire   [9:0] p_shl_cast_fu_1340_p1;
wire  signed [9:0] r_V_2_0_2_1_fu_1344_p2;
wire   [8:0] r_V_0_2_2_cast_fu_1358_p1;
wire  signed [8:0] r_V_2_0_2_2_fu_1361_p2;
wire   [10:0] sum_V_0_1_2_cast_fu_1304_p1;
wire  signed [10:0] tmp_144_0_2_1_cast_fu_1350_p1;
wire  signed [9:0] tmp_144_0_2_cast_cas_fu_1318_p1;
wire  signed [9:0] tmp_144_0_2_2_cast_c_fu_1367_p1;
wire   [9:0] tmp23_fu_1381_p2;
wire   [10:0] tmp22_fu_1375_p2;
wire  signed [10:0] tmp23_cast_fu_1387_p1;
wire   [10:0] p_Val2_s_fu_1391_p2;
wire   [7:0] tmp_20_fu_1326_p2;
wire   [7:0] tmp_54_fu_1322_p1;
wire   [2:0] tmp_21_fu_1411_p4;
wire   [8:0] r_V_2_1_0_1_fu_1443_p3;
wire   [8:0] tmp_144_1_0_2_cast_c_fu_1455_p1;
wire   [8:0] tmp_144_1_0_cast_cas_fu_1439_p1;
wire   [8:0] tmp26_fu_1463_p2;
wire   [9:0] tmp_144_1_0_cast_fu_1451_p1;
wire   [9:0] tmp26_cast_fu_1469_p1;
wire   [9:0] sum_V_1_1_2_fu_1479_p2;
wire   [8:0] r_V_1_2_cast_fu_1489_p1;
wire  signed [8:0] r_V_2_1_2_fu_1493_p2;
wire   [7:0] tmp_27_fu_1458_p2;
wire   [7:0] tmp_63_fu_1473_p2;
wire   [8:0] p_shl1_fu_1513_p3;
wire   [9:0] p_shl1_cast_fu_1521_p1;
wire  signed [9:0] r_V_2_1_2_1_fu_1525_p2;
wire   [8:0] r_V_1_2_2_cast_fu_1539_p1;
wire  signed [8:0] r_V_2_1_2_2_fu_1542_p2;
wire   [10:0] sum_V_1_1_2_cast_fu_1485_p1;
wire  signed [10:0] tmp_144_1_2_1_cast_fu_1531_p1;
wire  signed [9:0] tmp_144_1_2_cast_cas_fu_1499_p1;
wire  signed [9:0] tmp_144_1_2_2_cast_c_fu_1548_p1;
wire   [9:0] tmp29_fu_1562_p2;
wire   [10:0] tmp28_fu_1556_p2;
wire  signed [10:0] tmp29_cast_fu_1568_p1;
wire   [10:0] p_Val2_3_fu_1572_p2;
wire   [7:0] tmp_28_fu_1507_p2;
wire   [7:0] tmp_64_fu_1503_p1;
wire   [2:0] tmp_29_fu_1592_p4;
wire   [8:0] r_V_2_2_0_1_fu_1624_p3;
wire   [8:0] tmp_144_2_0_2_cast_c_fu_1636_p1;
wire   [8:0] tmp_144_2_0_cast_cas_fu_1620_p1;
wire   [8:0] tmp32_fu_1644_p2;
wire   [9:0] tmp_144_2_0_cast_fu_1632_p1;
wire   [9:0] tmp32_cast_fu_1650_p1;
wire   [9:0] sum_V_2_1_2_fu_1660_p2;
wire   [8:0] r_V_212_2_cast_fu_1670_p1;
wire  signed [8:0] r_V_2_2_2_fu_1674_p2;
wire   [7:0] tmp_35_fu_1639_p2;
wire   [7:0] tmp_71_fu_1654_p2;
wire   [8:0] p_shl2_fu_1694_p3;
wire   [9:0] p_shl2_cast_fu_1702_p1;
wire  signed [9:0] r_V_2_2_2_1_fu_1706_p2;
wire   [8:0] r_V_212_2_2_cast_fu_1720_p1;
wire  signed [8:0] r_V_2_2_2_2_fu_1723_p2;
wire   [10:0] sum_V_2_1_2_cast_fu_1666_p1;
wire  signed [10:0] tmp_144_2_2_1_cast_fu_1712_p1;
wire  signed [9:0] tmp_144_2_2_cast_cas_fu_1680_p1;
wire  signed [9:0] tmp_144_2_2_2_cast_c_fu_1729_p1;
wire   [9:0] tmp35_fu_1743_p2;
wire   [10:0] tmp34_fu_1737_p2;
wire  signed [10:0] tmp35_cast_fu_1749_p1;
wire   [10:0] p_Val2_6_fu_1753_p2;
wire   [7:0] tmp_36_fu_1688_p2;
wire   [7:0] tmp_72_fu_1684_p1;
wire   [2:0] tmp_39_fu_1773_p4;
wire   [7:0] tmp25_fu_1861_p2;
wire   [0:0] tmp_i_i_fu_1870_p2;
wire   [0:0] overflow_fu_1875_p2;
wire   [0:0] tmp_1_i_i_fu_1888_p2;
wire   [7:0] p_mux_i_i_cast_fu_1880_p3;
wire   [7:0] p_Val2_1_fu_1865_p2;
wire   [7:0] tmp31_fu_1902_p2;
wire   [0:0] tmp_i_i1_fu_1911_p2;
wire   [0:0] overflow_1_fu_1916_p2;
wire   [0:0] tmp_1_i_i1_fu_1929_p2;
wire   [7:0] p_mux_i_i30_cast_fu_1921_p3;
wire   [7:0] p_Val2_4_fu_1906_p2;
wire   [7:0] tmp37_fu_1943_p2;
wire   [0:0] tmp_i_i2_fu_1952_p2;
wire   [0:0] overflow_2_fu_1957_p2;
wire   [0:0] tmp_1_i_i2_fu_1970_p2;
wire   [7:0] p_mux_i_i39_cast_fu_1962_p3;
wire   [7:0] p_Val2_7_fu_1947_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_104;
reg    ap_enable_state4_pp0_iter0_stage0;
reg    ap_enable_operation_161;
reg    ap_enable_state5_pp0_iter1_stage0;
reg    ap_predicate_op175_store_state5;
reg    ap_enable_operation_175;
reg    ap_predicate_op183_store_state5;
reg    ap_enable_operation_183;
reg    ap_enable_operation_106;
reg    ap_enable_operation_164;
reg    ap_predicate_op173_store_state5;
reg    ap_enable_operation_173;
reg    ap_predicate_op181_store_state5;
reg    ap_enable_operation_181;
reg    ap_enable_operation_108;
reg    ap_enable_operation_167;
reg    ap_predicate_op171_store_state5;
reg    ap_enable_operation_171;
reg    ap_predicate_op180_store_state5;
reg    ap_enable_operation_180;
reg    ap_enable_operation_119;
reg    ap_enable_operation_201;
reg    ap_predicate_op215_store_state5;
reg    ap_enable_operation_215;
reg    ap_predicate_op223_store_state5;
reg    ap_enable_operation_223;
reg    ap_enable_operation_121;
reg    ap_enable_operation_204;
reg    ap_predicate_op213_store_state5;
reg    ap_enable_operation_213;
reg    ap_predicate_op221_store_state5;
reg    ap_enable_operation_221;
reg    ap_enable_operation_123;
reg    ap_enable_operation_207;
reg    ap_predicate_op211_store_state5;
reg    ap_enable_operation_211;
reg    ap_predicate_op220_store_state5;
reg    ap_enable_operation_220;
reg    ap_enable_operation_133;
reg    ap_enable_operation_238;
reg    ap_predicate_op252_store_state5;
reg    ap_enable_operation_252;
reg    ap_predicate_op257_store_state5;
reg    ap_enable_operation_257;
reg    ap_enable_operation_135;
reg    ap_enable_operation_241;
reg    ap_predicate_op250_store_state5;
reg    ap_enable_operation_250;
reg    ap_predicate_op255_store_state5;
reg    ap_enable_operation_255;
reg    ap_enable_operation_137;
reg    ap_enable_operation_244;
reg    ap_predicate_op248_store_state5;
reg    ap_enable_operation_248;
reg    ap_predicate_op254_store_state5;
reg    ap_enable_operation_254;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1434;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_address1),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_V1_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_address1),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_address1),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_address1),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_V2_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_address1),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_address1),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U56(
    .din0(right_border_buf_0_s_fu_272),
    .din1(right_border_buf_0_1_fu_276),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_14_fu_832_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U57(
    .din0(right_border_buf_0_2_fu_284),
    .din1(right_border_buf_0_3_fu_288),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_15_fu_851_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U58(
    .din0(right_border_buf_0_4_fu_296),
    .din1(right_border_buf_0_5_fu_300),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_16_fu_870_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U59(
    .din0(col_buf_0_val_0_0_fu_844_p3),
    .din1(col_buf_0_val_1_0_fu_863_p3),
    .din2(col_buf_0_val_2_0_fu_882_p3),
    .din3(tmp_37_reg_2225),
    .dout(tmp_17_fu_928_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U60(
    .din0(col_buf_0_val_0_0_fu_844_p3),
    .din1(col_buf_0_val_1_0_fu_863_p3),
    .din2(col_buf_0_val_2_0_fu_882_p3),
    .din3(row_assign_8_0_2_t_reg_2232),
    .dout(tmp_18_fu_946_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U61(
    .din0(right_border_buf_1_s_fu_308),
    .din1(right_border_buf_1_1_fu_312),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_22_fu_982_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U62(
    .din0(right_border_buf_1_2_fu_320),
    .din1(right_border_buf_1_3_fu_324),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_23_fu_1001_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U63(
    .din0(right_border_buf_1_4_fu_332),
    .din1(right_border_buf_1_5_fu_336),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_24_fu_1020_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U64(
    .din0(col_buf_1_val_0_0_fu_994_p3),
    .din1(col_buf_1_val_1_0_fu_1013_p3),
    .din2(col_buf_1_val_2_0_fu_1032_p3),
    .din3(tmp_37_reg_2225),
    .dout(tmp_25_fu_1078_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U65(
    .din0(col_buf_1_val_0_0_fu_994_p3),
    .din1(col_buf_1_val_1_0_fu_1013_p3),
    .din2(col_buf_1_val_2_0_fu_1032_p3),
    .din3(row_assign_8_0_2_t_reg_2232),
    .dout(tmp_26_fu_1096_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U66(
    .din0(right_border_buf_2_5_fu_340),
    .din1(right_border_buf_2_4_fu_328),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_30_fu_1123_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U67(
    .din0(right_border_buf_2_3_fu_316),
    .din1(right_border_buf_2_2_fu_304),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_31_fu_1142_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U68(
    .din0(right_border_buf_2_1_fu_292),
    .din1(right_border_buf_2_s_fu_280),
    .din2(8'd0),
    .din3(col_assign_1_fu_827_p2),
    .dout(tmp_32_fu_1161_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U69(
    .din0(col_buf_2_val_0_0_fu_1135_p3),
    .din1(col_buf_2_val_1_0_fu_1154_p3),
    .din2(col_buf_2_val_2_0_fu_1173_p3),
    .din3(tmp_37_reg_2225),
    .dout(tmp_33_fu_1210_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U70(
    .din0(col_buf_2_val_0_0_fu_1135_p3),
    .din1(col_buf_2_val_1_0_fu_1154_p3),
    .din2(col_buf_2_val_2_0_fu_1173_p3),
    .din3(row_assign_8_0_2_t_reg_2232),
    .dout(tmp_34_fu_1228_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond462_i_fu_587_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond461_i_fu_659_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond462_i_fu_587_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state5)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((exitcond462_i_fu_587_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_659_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_564 <= j_V_fu_665_p2;
    end else if (((exitcond462_i_fu_587_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_2_reg_564 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_581_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_553 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        t_V_reg_553 <= i_V_reg_2188;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_5_reg_542 <= 2'd0;
    end else if (((tmp_7_fu_581_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_5_reg_542 <= tmp_6_fu_575_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_659_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2257 <= brmerge_fu_777_p2;
        k_buf_0_val_3_addr_reg_2270 <= tmp_13_fu_782_p1;
        k_buf_0_val_4_addr_reg_2276 <= tmp_13_fu_782_p1;
        k_buf_0_val_5_addr_reg_2282 <= tmp_13_fu_782_p1;
        k_buf_1_val_3_addr_reg_2292 <= tmp_13_fu_782_p1;
        k_buf_1_val_4_addr_reg_2298 <= tmp_13_fu_782_p1;
        k_buf_1_val_5_addr_reg_2304 <= tmp_13_fu_782_p1;
        k_buf_2_val_3_addr_reg_2310 <= tmp_13_fu_782_p1;
        k_buf_2_val_4_addr_reg_2316 <= tmp_13_fu_782_p1;
        k_buf_2_val_5_addr_reg_2322 <= tmp_13_fu_782_p1;
        or_cond_i_i_reg_2248 <= or_cond_i_i_fu_713_p2;
        or_cond_i_reg_2288 <= or_cond_i_fu_795_p2;
        tmp_49_reg_2252 <= tmp_49_fu_769_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond461_i_reg_2239 <= exitcond461_i_fu_659_p2;
        exitcond461_i_reg_2239_pp0_iter1_reg <= exitcond461_i_reg_2239;
        or_cond_i_reg_2288_pp0_iter1_reg <= or_cond_i_reg_2288;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2188 <= i_V_fu_593_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond462_i_fu_587_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2202 <= icmp_fu_621_p2;
        row_assign_8_0_2_t_reg_2232 <= row_assign_8_0_2_t_fu_649_p2;
        tmp_102_0_1_reg_2211 <= tmp_102_0_1_fu_633_p2;
        tmp_1_reg_2193 <= tmp_1_fu_599_p2;
        tmp_37_reg_2225 <= tmp_37_fu_645_p1;
        tmp_58_0_0_not_reg_2197 <= tmp_58_0_0_not_fu_605_p2;
        tmp_8_reg_2215 <= tmp_8_fu_639_p2;
        tmp_9_reg_2207 <= tmp_9_fu_627_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2288_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        not_i_i1_reg_2414 <= not_i_i1_fu_1602_p2;
        not_i_i2_reg_2440 <= not_i_i2_fu_1783_p2;
        not_i_i_reg_2388 <= not_i_i_fu_1421_p2;
        p_Result_1_reg_2403 <= p_Val2_3_fu_1572_p2[32'd10];
        p_Result_2_reg_2429 <= p_Val2_6_fu_1753_p2[32'd10];
        p_Result_s_reg_2377 <= p_Val2_s_fu_1391_p2[32'd10];
        tmp24_reg_2383 <= tmp24_fu_1405_p2;
        tmp30_reg_2409 <= tmp30_fu_1586_p2;
        tmp36_reg_2435 <= tmp36_fu_1767_p2;
        tmp_56_reg_2367[7 : 1] <= tmp_56_fu_1354_p1[7 : 1];
        tmp_58_reg_2372 <= tmp_58_fu_1371_p1;
        tmp_65_reg_2393[7 : 1] <= tmp_65_fu_1535_p1[7 : 1];
        tmp_66_reg_2398 <= tmp_66_fu_1552_p1;
        tmp_73_reg_2419[7 : 1] <= tmp_73_fu_1716_p1[7 : 1];
        tmp_74_reg_2424 <= tmp_74_fu_1733_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond_i_reg_2288_pp0_iter2_reg <= or_cond_i_reg_2288_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_1_fu_276 <= right_border_buf_0_s_fu_272;
        right_border_buf_0_2_fu_284 <= col_buf_0_val_1_0_fu_863_p3;
        right_border_buf_0_3_fu_288 <= right_border_buf_0_2_fu_284;
        right_border_buf_0_4_fu_296 <= col_buf_0_val_2_0_fu_882_p3;
        right_border_buf_0_5_fu_300 <= right_border_buf_0_4_fu_296;
        right_border_buf_0_s_fu_272 <= col_buf_0_val_0_0_fu_844_p3;
        right_border_buf_1_1_fu_312 <= right_border_buf_1_s_fu_308;
        right_border_buf_1_2_fu_320 <= col_buf_1_val_1_0_fu_1013_p3;
        right_border_buf_1_3_fu_324 <= right_border_buf_1_2_fu_320;
        right_border_buf_1_4_fu_332 <= col_buf_1_val_2_0_fu_1032_p3;
        right_border_buf_1_5_fu_336 <= right_border_buf_1_4_fu_332;
        right_border_buf_1_s_fu_308 <= col_buf_1_val_0_0_fu_994_p3;
        right_border_buf_2_1_fu_292 <= col_buf_2_val_2_0_fu_1173_p3;
        right_border_buf_2_2_fu_304 <= right_border_buf_2_3_fu_316;
        right_border_buf_2_3_fu_316 <= col_buf_2_val_1_0_fu_1154_p3;
        right_border_buf_2_4_fu_328 <= right_border_buf_2_5_fu_340;
        right_border_buf_2_5_fu_340 <= col_buf_2_val_0_0_fu_1135_p3;
        right_border_buf_2_s_fu_280 <= right_border_buf_2_1_fu_292;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2239_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_228 <= src_kernel_win_0_va_fu_224;
        src_kernel_win_0_va_2_fu_232 <= src_kernel_win_0_va_5_reg_2334;
        src_kernel_win_0_va_3_fu_236 <= src_kernel_win_0_va_2_fu_232;
        src_kernel_win_0_va_fu_224 <= src_kernel_win_0_va_4_reg_2328;
        src_kernel_win_1_va_1_fu_244 <= src_kernel_win_1_va_fu_240;
        src_kernel_win_1_va_2_fu_248 <= src_kernel_win_1_va_5_reg_2347;
        src_kernel_win_1_va_3_fu_252 <= src_kernel_win_1_va_2_fu_248;
        src_kernel_win_1_va_fu_240 <= src_kernel_win_1_va_4_reg_2341;
        src_kernel_win_2_va_1_fu_260 <= src_kernel_win_2_va_fu_256;
        src_kernel_win_2_va_2_fu_264 <= src_kernel_win_2_va_7_reg_2360;
        src_kernel_win_2_va_3_fu_268 <= src_kernel_win_2_va_2_fu_264;
        src_kernel_win_2_va_fu_256 <= src_kernel_win_2_va_6_reg_2354;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2239 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_4_reg_2328 <= src_kernel_win_0_va_4_fu_939_p3;
        src_kernel_win_0_va_5_reg_2334 <= src_kernel_win_0_va_5_fu_957_p3;
        src_kernel_win_1_va_4_reg_2341 <= src_kernel_win_1_va_4_fu_1089_p3;
        src_kernel_win_1_va_5_reg_2347 <= src_kernel_win_1_va_5_fu_1107_p3;
        src_kernel_win_2_va_6_reg_2354 <= src_kernel_win_2_va_6_fu_1221_p3;
        src_kernel_win_2_va_7_reg_2360 <= src_kernel_win_2_va_7_fu_1239_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond462_i_fu_587_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond462_i_fu_587_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1434)) begin
        if (((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_102_0_1_reg_2211 == 1'd1) & (icmp_reg_2202 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1434)) begin
        if (((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_9_reg_2207 == 1'd1) & (icmp_reg_2202 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1434)) begin
        if (((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1))) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if (((tmp_102_0_1_reg_2211 == 1'd1) & (icmp_reg_2202 == 1'd0))) begin
            k_buf_1_val_4_d1 = p_src_data_stream_V1_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1434)) begin
        if (((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1))) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if (((tmp_9_reg_2207 == 1'd1) & (icmp_reg_2202 == 1'd0))) begin
            k_buf_1_val_5_d1 = p_src_data_stream_V1_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1434)) begin
        if (((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1))) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if (((tmp_102_0_1_reg_2211 == 1'd1) & (icmp_reg_2202 == 1'd0))) begin
            k_buf_2_val_4_d1 = p_src_data_stream_V2_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1434)) begin
        if (((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1))) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if (((tmp_9_reg_2207 == 1'd1) & (icmp_reg_2202 == 1'd0))) begin
            k_buf_2_val_5_d1 = p_src_data_stream_V2_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_V3_blk_n = p_dst_data_stream_V3_full_n;
    end else begin
        p_dst_data_stream_V3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V3_write = 1'b1;
    end else begin
        p_dst_data_stream_V3_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_V4_blk_n = p_dst_data_stream_V4_full_n;
    end else begin
        p_dst_data_stream_V4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V4_write = 1'b1;
    end else begin
        p_dst_data_stream_V4_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V1_blk_n = p_src_data_stream_V1_empty_n;
    end else begin
        p_src_data_stream_V1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op210_read_state5 == 1'b1)))) begin
        p_src_data_stream_V1_read = 1'b1;
    end else begin
        p_src_data_stream_V1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V2_blk_n = p_src_data_stream_V2_empty_n;
    end else begin
        p_src_data_stream_V2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op256_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op247_read_state5 == 1'b1)))) begin
        p_src_data_stream_V2_read = 1'b1;
    end else begin
        p_src_data_stream_V2_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op182_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state5 == 1'b1)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_7_fu_581_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond462_i_fu_587_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_687_p2 = ($signed(8'd255) + $signed(t_V_2_cast_fu_655_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V2_empty_n == 1'b0) & (ap_predicate_op256_read_state5 == 1'b1)) | ((p_src_data_stream_V2_empty_n == 1'b0) & (ap_predicate_op247_read_state5 == 1'b1)) | ((p_src_data_stream_V1_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_V1_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op182_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op170_read_state5 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V4_full_n == 1'b0)) | ((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V3_full_n == 1'b0)) | ((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V2_empty_n == 1'b0) & (ap_predicate_op256_read_state5 == 1'b1)) | ((p_src_data_stream_V2_empty_n == 1'b0) & (ap_predicate_op247_read_state5 == 1'b1)) | ((p_src_data_stream_V1_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_V1_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op182_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op170_read_state5 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V4_full_n == 1'b0)) | ((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V3_full_n == 1'b0)) | ((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V2_empty_n == 1'b0) & (ap_predicate_op256_read_state5 == 1'b1)) | ((p_src_data_stream_V2_empty_n == 1'b0) & (ap_predicate_op247_read_state5 == 1'b1)) | ((p_src_data_stream_V1_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_V1_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op182_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op170_read_state5 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V4_full_n == 1'b0)) | ((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V3_full_n == 1'b0)) | ((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (((p_src_data_stream_V2_empty_n == 1'b0) & (ap_predicate_op256_read_state5 == 1'b1)) | ((p_src_data_stream_V2_empty_n == 1'b0) & (ap_predicate_op247_read_state5 == 1'b1)) | ((p_src_data_stream_V1_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_V1_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op182_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op170_read_state5 == 1'b1)));
end

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter3 = (((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V4_full_n == 1'b0)) | ((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V3_full_n == 1'b0)) | ((or_cond_i_reg_2288_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1434 = ((or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_operation_104 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_106 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_108 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_119 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_121 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_123 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_133 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_135 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_137 = (exitcond461_i_fu_659_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_161 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_164 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_167 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_171 = (ap_predicate_op171_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_173 = (ap_predicate_op173_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_175 = (ap_predicate_op175_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_180 = (ap_predicate_op180_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_181 = (ap_predicate_op181_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_183 = (ap_predicate_op183_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_201 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_204 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_207 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_211 = (ap_predicate_op211_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_213 = (ap_predicate_op213_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_215 = (ap_predicate_op215_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_220 = (ap_predicate_op220_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_221 = (ap_predicate_op221_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_223 = (ap_predicate_op223_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_238 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_241 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_244 = (exitcond461_i_reg_2239 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_248 = (ap_predicate_op248_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_250 = (ap_predicate_op250_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_252 = (ap_predicate_op252_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_254 = (ap_predicate_op254_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_255 = (ap_predicate_op255_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_257 = (ap_predicate_op257_store_state5 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter0_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op170_read_state5 = ((or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op171_store_state5 = ((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op173_store_state5 = ((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op175_store_state5 = ((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op181_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op182_read_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op183_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op210_read_state5 = ((or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op211_store_state5 = ((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op213_store_state5 = ((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op215_store_state5 = ((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op220_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op221_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op222_read_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op223_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op247_read_state5 = ((or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op248_store_state5 = ((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op250_store_state5 = ((tmp_102_0_1_reg_2211 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op252_store_state5 = ((tmp_9_reg_2207 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (icmp_reg_2202 == 1'd0) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op254_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op255_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op256_read_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

always @ (*) begin
    ap_predicate_op257_store_state5 = ((tmp_1_reg_2193 == 1'd1) & (icmp_reg_2202 == 1'd1) & (or_cond_i_i_reg_2248 == 1'd1) & (exitcond461_i_reg_2239 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign brmerge_fu_777_p2 = (tmp_58_0_0_not_reg_2197 | tmp_11_fu_707_p2);

assign col_assign_1_fu_827_p2 = (tmp_49_reg_2252 ^ 2'd3);

assign col_buf_0_val_0_0_fu_844_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_14_fu_832_p5);

assign col_buf_0_val_1_0_fu_863_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_15_fu_851_p5);

assign col_buf_0_val_2_0_fu_882_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_16_fu_870_p5);

assign col_buf_1_val_0_0_fu_994_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_22_fu_982_p5);

assign col_buf_1_val_1_0_fu_1013_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_23_fu_1001_p5);

assign col_buf_1_val_2_0_fu_1032_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_24_fu_1020_p5);

assign col_buf_2_val_0_0_fu_1135_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_30_fu_1123_p5);

assign col_buf_2_val_1_0_fu_1154_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_31_fu_1142_p5);

assign col_buf_2_val_2_0_fu_1173_p3 = ((brmerge_reg_2257[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_32_fu_1161_p5);

assign exitcond461_i_fu_659_p2 = ((t_V_2_reg_564 == 7'd102) ? 1'b1 : 1'b0);

assign exitcond462_i_fu_587_p2 = ((t_V_reg_553 == 7'd102) ? 1'b1 : 1'b0);

assign i_V_fu_593_p2 = (t_V_reg_553 + 7'd1);

assign icmp1_fu_681_p2 = ((tmp_38_fu_671_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_fu_621_p2 = ((tmp_fu_611_p4 != 6'd0) ? 1'b1 : 1'b0);

assign j_V_fu_665_p2 = (t_V_2_reg_564 + 7'd1);

assign k_buf_0_val_3_address0 = tmp_13_fu_782_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_2270;

assign k_buf_0_val_4_address0 = tmp_13_fu_782_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_2276;

assign k_buf_0_val_5_address0 = tmp_13_fu_782_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_2282;

assign k_buf_1_val_3_address0 = tmp_13_fu_782_p1;

assign k_buf_1_val_3_address1 = k_buf_1_val_3_addr_reg_2292;

assign k_buf_1_val_4_address0 = tmp_13_fu_782_p1;

assign k_buf_1_val_4_address1 = k_buf_1_val_4_addr_reg_2298;

assign k_buf_1_val_5_address0 = tmp_13_fu_782_p1;

assign k_buf_1_val_5_address1 = k_buf_1_val_5_addr_reg_2304;

assign k_buf_2_val_3_address0 = tmp_13_fu_782_p1;

assign k_buf_2_val_3_address1 = k_buf_2_val_3_addr_reg_2310;

assign k_buf_2_val_4_address0 = tmp_13_fu_782_p1;

assign k_buf_2_val_4_address1 = k_buf_2_val_4_addr_reg_2316;

assign k_buf_2_val_5_address0 = tmp_13_fu_782_p1;

assign k_buf_2_val_5_address1 = k_buf_2_val_5_addr_reg_2322;

assign not_i_i1_fu_1602_p2 = ((tmp_29_fu_1592_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i2_fu_1783_p2 = ((tmp_39_fu_1773_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_fu_1421_p2 = ((tmp_21_fu_1411_p4 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i_fu_795_p2 = (icmp_reg_2202 & icmp1_fu_681_p2);

assign or_cond_i_i_fu_713_p2 = (tmp_11_fu_707_p2 & rev_fu_701_p2);

assign overflow_1_fu_1916_p2 = (tmp_i_i1_fu_1911_p2 & not_i_i1_reg_2414);

assign overflow_2_fu_1957_p2 = (tmp_i_i2_fu_1952_p2 & not_i_i2_reg_2440);

assign overflow_fu_1875_p2 = (tmp_i_i_fu_1870_p2 & not_i_i_reg_2388);

assign p_Val2_1_fu_1865_p2 = (tmp24_reg_2383 + tmp25_fu_1861_p2);

assign p_Val2_3_fu_1572_p2 = ($signed(tmp28_fu_1556_p2) + $signed(tmp29_cast_fu_1568_p1));

assign p_Val2_4_fu_1906_p2 = (tmp30_reg_2409 + tmp31_fu_1902_p2);

assign p_Val2_6_fu_1753_p2 = ($signed(tmp34_fu_1737_p2) + $signed(tmp35_cast_fu_1749_p1));

assign p_Val2_7_fu_1947_p2 = (tmp36_reg_2435 + tmp37_fu_1943_p2);

assign p_Val2_s_fu_1391_p2 = ($signed(tmp22_fu_1375_p2) + $signed(tmp23_cast_fu_1387_p1));

assign p_assign_1_fu_727_p2 = (8'd1 - t_V_2_cast_fu_655_p1);

assign p_assign_2_fu_747_p2 = ($signed(8'd198) - $signed(p_p2_i_i_fu_733_p3));

assign p_dst_data_stream_V3_din = ((tmp_1_i_i1_fu_1929_p2[0:0] === 1'b1) ? p_mux_i_i30_cast_fu_1921_p3 : p_Val2_4_fu_1906_p2);

assign p_dst_data_stream_V4_din = ((tmp_1_i_i2_fu_1970_p2[0:0] === 1'b1) ? p_mux_i_i39_cast_fu_1962_p3 : p_Val2_7_fu_1947_p2);

assign p_dst_data_stream_V_din = ((tmp_1_i_i_fu_1888_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1880_p3 : p_Val2_1_fu_1865_p2);

assign p_mux_i_i30_cast_fu_1921_p3 = ((tmp_i_i1_fu_1911_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i39_cast_fu_1962_p3 = ((tmp_i_i2_fu_1952_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_1880_p3 = ((tmp_i_i_fu_1870_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i_i_0_p_assign_2_fu_753_p3 = ((tmp_12_fu_741_p2[0:0] === 1'b1) ? p_p2_i_i_fu_733_p3 : p_assign_2_fu_747_p2);

assign p_p2_i_i_fu_733_p3 = ((tmp_41_fu_719_p3[0:0] === 1'b1) ? p_assign_1_fu_727_p2 : ImagLoc_x_fu_687_p2);

assign p_shl1_cast_fu_1521_p1 = p_shl1_fu_1513_p3;

assign p_shl1_fu_1513_p3 = {{src_kernel_win_1_va_fu_240}, {1'd0}};

assign p_shl2_cast_fu_1702_p1 = p_shl2_fu_1694_p3;

assign p_shl2_fu_1694_p3 = {{src_kernel_win_2_va_fu_256}, {1'd0}};

assign p_shl_cast_fu_1340_p1 = p_shl_fu_1332_p3;

assign p_shl_fu_1332_p3 = {{src_kernel_win_0_va_fu_224}, {1'd0}};

assign r_V_0_2_2_cast_fu_1358_p1 = src_kernel_win_0_va_4_reg_2328;

assign r_V_0_2_cast_fu_1308_p1 = src_kernel_win_0_va_1_fu_228;

assign r_V_1_2_2_cast_fu_1539_p1 = src_kernel_win_1_va_4_reg_2341;

assign r_V_1_2_cast_fu_1489_p1 = src_kernel_win_1_va_1_fu_244;

assign r_V_212_2_2_cast_fu_1720_p1 = src_kernel_win_2_va_6_reg_2354;

assign r_V_212_2_cast_fu_1670_p1 = src_kernel_win_2_va_1_fu_260;

assign r_V_2_0_0_1_fu_1262_p3 = {{src_kernel_win_0_va_2_fu_232}, {1'd0}};

assign r_V_2_0_2_1_fu_1344_p2 = (10'd0 - p_shl_cast_fu_1340_p1);

assign r_V_2_0_2_2_fu_1361_p2 = (9'd0 - r_V_0_2_2_cast_fu_1358_p1);

assign r_V_2_0_2_fu_1312_p2 = (9'd0 - r_V_0_2_cast_fu_1308_p1);

assign r_V_2_1_0_1_fu_1443_p3 = {{src_kernel_win_1_va_2_fu_248}, {1'd0}};

assign r_V_2_1_2_1_fu_1525_p2 = (10'd0 - p_shl1_cast_fu_1521_p1);

assign r_V_2_1_2_2_fu_1542_p2 = (9'd0 - r_V_1_2_2_cast_fu_1539_p1);

assign r_V_2_1_2_fu_1493_p2 = (9'd0 - r_V_1_2_cast_fu_1489_p1);

assign r_V_2_2_0_1_fu_1624_p3 = {{src_kernel_win_2_va_2_fu_264}, {1'd0}};

assign r_V_2_2_2_1_fu_1706_p2 = (10'd0 - p_shl2_cast_fu_1702_p1);

assign r_V_2_2_2_2_fu_1723_p2 = (9'd0 - r_V_212_2_2_cast_fu_1720_p1);

assign r_V_2_2_2_fu_1674_p2 = (9'd0 - r_V_212_2_cast_fu_1670_p1);

assign rev_fu_701_p2 = (tmp_40_fu_693_p3 ^ 1'd1);

assign row_assign_8_0_2_t_fu_649_p2 = ($signed(2'd2) - $signed(tmp_37_fu_645_p1));

assign src_kernel_win_0_va_4_fu_939_p3 = ((tmp_8_reg_2215[0:0] === 1'b1) ? tmp_17_fu_928_p5 : col_buf_0_val_0_0_fu_844_p3);

assign src_kernel_win_0_va_5_fu_957_p3 = ((tmp_8_reg_2215[0:0] === 1'b1) ? tmp_18_fu_946_p5 : col_buf_0_val_2_0_fu_882_p3);

assign src_kernel_win_1_va_4_fu_1089_p3 = ((tmp_8_reg_2215[0:0] === 1'b1) ? tmp_25_fu_1078_p5 : col_buf_1_val_0_0_fu_994_p3);

assign src_kernel_win_1_va_5_fu_1107_p3 = ((tmp_8_reg_2215[0:0] === 1'b1) ? tmp_26_fu_1096_p5 : col_buf_1_val_2_0_fu_1032_p3);

assign src_kernel_win_2_va_6_fu_1221_p3 = ((tmp_8_reg_2215[0:0] === 1'b1) ? tmp_33_fu_1210_p5 : col_buf_2_val_0_0_fu_1135_p3);

assign src_kernel_win_2_va_7_fu_1239_p3 = ((tmp_8_reg_2215[0:0] === 1'b1) ? tmp_34_fu_1228_p5 : col_buf_2_val_2_0_fu_1173_p3);

assign start_out = real_start;

assign sum_V_0_1_2_cast_fu_1304_p1 = sum_V_0_1_2_fu_1298_p2;

assign sum_V_0_1_2_fu_1298_p2 = (tmp_144_0_0_cast_fu_1270_p1 + tmp20_cast_fu_1288_p1);

assign sum_V_1_1_2_cast_fu_1485_p1 = sum_V_1_1_2_fu_1479_p2;

assign sum_V_1_1_2_fu_1479_p2 = (tmp_144_1_0_cast_fu_1451_p1 + tmp26_cast_fu_1469_p1);

assign sum_V_2_1_2_cast_fu_1666_p1 = sum_V_2_1_2_fu_1660_p2;

assign sum_V_2_1_2_fu_1660_p2 = (tmp_144_2_0_cast_fu_1632_p1 + tmp32_cast_fu_1650_p1);

assign t_V_2_cast_fu_655_p1 = t_V_2_reg_564;

assign tmp20_cast_fu_1288_p1 = tmp20_fu_1282_p2;

assign tmp20_fu_1282_p2 = (tmp_144_0_0_2_cast_c_fu_1274_p1 + tmp_144_0_0_cast_cas_fu_1258_p1);

assign tmp22_fu_1375_p2 = ($signed(sum_V_0_1_2_cast_fu_1304_p1) + $signed(tmp_144_0_2_1_cast_fu_1350_p1));

assign tmp23_cast_fu_1387_p1 = $signed(tmp23_fu_1381_p2);

assign tmp23_fu_1381_p2 = ($signed(tmp_144_0_2_cast_cas_fu_1318_p1) + $signed(tmp_144_0_2_2_cast_c_fu_1367_p1));

assign tmp24_fu_1405_p2 = (tmp_20_fu_1326_p2 + tmp_54_fu_1322_p1);

assign tmp25_fu_1861_p2 = (tmp_58_reg_2372 + tmp_56_reg_2367);

assign tmp26_cast_fu_1469_p1 = tmp26_fu_1463_p2;

assign tmp26_fu_1463_p2 = (tmp_144_1_0_2_cast_c_fu_1455_p1 + tmp_144_1_0_cast_cas_fu_1439_p1);

assign tmp28_fu_1556_p2 = ($signed(sum_V_1_1_2_cast_fu_1485_p1) + $signed(tmp_144_1_2_1_cast_fu_1531_p1));

assign tmp29_cast_fu_1568_p1 = $signed(tmp29_fu_1562_p2);

assign tmp29_fu_1562_p2 = ($signed(tmp_144_1_2_cast_cas_fu_1499_p1) + $signed(tmp_144_1_2_2_cast_c_fu_1548_p1));

assign tmp30_fu_1586_p2 = (tmp_28_fu_1507_p2 + tmp_64_fu_1503_p1);

assign tmp31_fu_1902_p2 = (tmp_66_reg_2398 + tmp_65_reg_2393);

assign tmp32_cast_fu_1650_p1 = tmp32_fu_1644_p2;

assign tmp32_fu_1644_p2 = (tmp_144_2_0_2_cast_c_fu_1636_p1 + tmp_144_2_0_cast_cas_fu_1620_p1);

assign tmp34_fu_1737_p2 = ($signed(sum_V_2_1_2_cast_fu_1666_p1) + $signed(tmp_144_2_2_1_cast_fu_1712_p1));

assign tmp35_cast_fu_1749_p1 = $signed(tmp35_fu_1743_p2);

assign tmp35_fu_1743_p2 = ($signed(tmp_144_2_2_cast_cas_fu_1680_p1) + $signed(tmp_144_2_2_2_cast_c_fu_1729_p1));

assign tmp36_fu_1767_p2 = (tmp_36_fu_1688_p2 + tmp_72_fu_1684_p1);

assign tmp37_fu_1943_p2 = (tmp_74_reg_2424 + tmp_73_reg_2419);

assign tmp_102_0_1_fu_633_p2 = ((t_V_reg_553 == 7'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_707_p2 = (($signed(ImagLoc_x_fu_687_p2) < $signed(8'd100)) ? 1'b1 : 1'b0);

assign tmp_12_fu_741_p2 = (($signed(p_p2_i_i_fu_733_p3) < $signed(8'd100)) ? 1'b1 : 1'b0);

assign tmp_13_fu_782_p1 = $unsigned(x_cast_fu_773_p1);

assign tmp_144_0_0_2_cast_c_fu_1274_p1 = src_kernel_win_0_va_5_reg_2334;

assign tmp_144_0_0_cast_cas_fu_1258_p1 = src_kernel_win_0_va_3_fu_236;

assign tmp_144_0_0_cast_fu_1270_p1 = r_V_2_0_0_1_fu_1262_p3;

assign tmp_144_0_2_1_cast_fu_1350_p1 = r_V_2_0_2_1_fu_1344_p2;

assign tmp_144_0_2_2_cast_c_fu_1367_p1 = r_V_2_0_2_2_fu_1361_p2;

assign tmp_144_0_2_cast_cas_fu_1318_p1 = r_V_2_0_2_fu_1312_p2;

assign tmp_144_1_0_2_cast_c_fu_1455_p1 = src_kernel_win_1_va_5_reg_2347;

assign tmp_144_1_0_cast_cas_fu_1439_p1 = src_kernel_win_1_va_3_fu_252;

assign tmp_144_1_0_cast_fu_1451_p1 = r_V_2_1_0_1_fu_1443_p3;

assign tmp_144_1_2_1_cast_fu_1531_p1 = r_V_2_1_2_1_fu_1525_p2;

assign tmp_144_1_2_2_cast_c_fu_1548_p1 = r_V_2_1_2_2_fu_1542_p2;

assign tmp_144_1_2_cast_cas_fu_1499_p1 = r_V_2_1_2_fu_1493_p2;

assign tmp_144_2_0_2_cast_c_fu_1636_p1 = src_kernel_win_2_va_7_reg_2360;

assign tmp_144_2_0_cast_cas_fu_1620_p1 = src_kernel_win_2_va_3_fu_268;

assign tmp_144_2_0_cast_fu_1632_p1 = r_V_2_2_0_1_fu_1624_p3;

assign tmp_144_2_2_1_cast_fu_1712_p1 = r_V_2_2_2_1_fu_1706_p2;

assign tmp_144_2_2_2_cast_c_fu_1729_p1 = r_V_2_2_2_2_fu_1723_p2;

assign tmp_144_2_2_cast_cas_fu_1680_p1 = r_V_2_2_2_fu_1674_p2;

assign tmp_19_fu_1277_p2 = (src_kernel_win_0_va_3_fu_236 + src_kernel_win_0_va_5_reg_2334);

assign tmp_1_fu_599_p2 = ((t_V_reg_553 < 7'd100) ? 1'b1 : 1'b0);

assign tmp_1_i_i1_fu_1929_p2 = (p_Result_1_reg_2403 | overflow_1_fu_1916_p2);

assign tmp_1_i_i2_fu_1970_p2 = (p_Result_2_reg_2429 | overflow_2_fu_1957_p2);

assign tmp_1_i_i_fu_1888_p2 = (p_Result_s_reg_2377 | overflow_fu_1875_p2);

assign tmp_20_fu_1326_p2 = (tmp_19_fu_1277_p2 + tmp_53_fu_1292_p2);

assign tmp_21_fu_1411_p4 = {{p_Val2_s_fu_1391_p2[10:8]}};

assign tmp_27_fu_1458_p2 = (src_kernel_win_1_va_3_fu_252 + src_kernel_win_1_va_5_reg_2347);

assign tmp_28_fu_1507_p2 = (tmp_27_fu_1458_p2 + tmp_63_fu_1473_p2);

assign tmp_29_fu_1592_p4 = {{p_Val2_3_fu_1572_p2[10:8]}};

assign tmp_35_fu_1639_p2 = (src_kernel_win_2_va_3_fu_268 + src_kernel_win_2_va_7_reg_2360);

assign tmp_36_fu_1688_p2 = (tmp_35_fu_1639_p2 + tmp_71_fu_1654_p2);

assign tmp_37_fu_645_p1 = t_V_reg_553[1:0];

assign tmp_38_fu_671_p4 = {{t_V_2_reg_564[6:1]}};

assign tmp_39_fu_1773_p4 = {{p_Val2_6_fu_1753_p2[10:8]}};

assign tmp_40_fu_693_p3 = ImagLoc_x_fu_687_p2[32'd7];

assign tmp_41_fu_719_p3 = ImagLoc_x_fu_687_p2[32'd7];

assign tmp_49_fu_769_p1 = x_fu_761_p3[1:0];

assign tmp_53_fu_1292_p2 = src_kernel_win_0_va_2_fu_232 << 8'd1;

assign tmp_54_fu_1322_p1 = r_V_2_0_2_fu_1312_p2[7:0];

assign tmp_56_fu_1354_p1 = r_V_2_0_2_1_fu_1344_p2[7:0];

assign tmp_58_0_0_not_fu_605_p2 = (tmp_1_fu_599_p2 ^ 1'd1);

assign tmp_58_fu_1371_p1 = r_V_2_0_2_2_fu_1361_p2[7:0];

assign tmp_63_fu_1473_p2 = src_kernel_win_1_va_2_fu_248 << 8'd1;

assign tmp_64_fu_1503_p1 = r_V_2_1_2_fu_1493_p2[7:0];

assign tmp_65_fu_1535_p1 = r_V_2_1_2_1_fu_1525_p2[7:0];

assign tmp_66_fu_1552_p1 = r_V_2_1_2_2_fu_1542_p2[7:0];

assign tmp_6_fu_575_p2 = (tmp_5_reg_542 + 2'd1);

assign tmp_71_fu_1654_p2 = src_kernel_win_2_va_2_fu_264 << 8'd1;

assign tmp_72_fu_1684_p1 = r_V_2_2_2_fu_1674_p2[7:0];

assign tmp_73_fu_1716_p1 = r_V_2_2_2_1_fu_1706_p2[7:0];

assign tmp_74_fu_1733_p1 = r_V_2_2_2_2_fu_1723_p2[7:0];

assign tmp_7_fu_581_p2 = ((tmp_5_reg_542 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_8_fu_639_p2 = ((t_V_reg_553 > 7'd100) ? 1'b1 : 1'b0);

assign tmp_9_fu_627_p2 = ((t_V_reg_553 == 7'd1) ? 1'b1 : 1'b0);

assign tmp_fu_611_p4 = {{t_V_reg_553[6:1]}};

assign tmp_i_i1_fu_1911_p2 = (p_Result_1_reg_2403 ^ 1'd1);

assign tmp_i_i2_fu_1952_p2 = (p_Result_2_reg_2429 ^ 1'd1);

assign tmp_i_i_fu_1870_p2 = (p_Result_s_reg_2377 ^ 1'd1);

assign x_cast_fu_773_p1 = x_fu_761_p3;

assign x_fu_761_p3 = ((or_cond_i_i_fu_713_p2[0:0] === 1'b1) ? ImagLoc_x_fu_687_p2 : p_p2_i_i_0_p_assign_2_fu_753_p3);

always @ (posedge ap_clk) begin
    tmp_56_reg_2367[0] <= 1'b0;
    tmp_65_reg_2393[0] <= 1'b0;
    tmp_73_reg_2419[0] <= 1'b0;
end

endmodule //Filter2D93
