// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D_1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state8 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond461_i_reg_2507;
reg   [0:0] or_cond_i_i_reg_2516;
reg   [0:0] icmp_reg_2460;
reg   [0:0] tmp_29_reg_2451;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] or_cond_i_reg_2564;
reg   [0:0] or_cond_i_reg_2564_pp0_iter2_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [6:0] t_V_3_reg_590;
wire   [1:0] tmp_26_fu_601_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond462_i_fu_613_p2;
wire    ap_CS_fsm_state3;
wire   [6:0] i_V_fu_619_p2;
reg   [6:0] i_V_reg_2446;
wire   [0:0] tmp_29_fu_625_p2;
wire   [0:0] tmp_199_0_0_not_fu_631_p2;
reg   [0:0] tmp_199_0_0_not_reg_2455;
wire   [0:0] icmp_fu_647_p2;
wire   [0:0] tmp_31_fu_653_p2;
reg   [0:0] tmp_31_reg_2465;
wire   [0:0] tmp_243_0_1_fu_659_p2;
reg   [0:0] tmp_243_0_1_reg_2469;
wire   [0:0] tmp_32_fu_665_p2;
reg   [0:0] tmp_32_reg_2473;
wire   [1:0] tmp_77_fu_671_p1;
reg   [1:0] tmp_77_reg_2486;
wire   [1:0] row_assign_12_0_1_t_fu_675_p2;
reg   [1:0] row_assign_12_0_1_t_reg_2493;
wire   [1:0] row_assign_12_0_2_t_fu_681_p2;
reg   [1:0] row_assign_12_0_2_t_reg_2500;
wire   [0:0] exitcond461_i_fu_691_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_predicate_op177_read_state5;
reg    ap_predicate_op189_read_state5;
reg    ap_predicate_op226_read_state5;
reg    ap_predicate_op238_read_state5;
reg    ap_predicate_op272_read_state5;
reg    ap_predicate_op281_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond461_i_reg_2507_pp0_iter1_reg;
wire   [6:0] j_V_fu_697_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_745_p2;
wire   [1:0] col_assign_4_fu_809_p2;
reg   [1:0] col_assign_4_reg_2520;
wire   [0:0] brmerge_fu_815_p2;
reg   [0:0] brmerge_reg_2533;
reg   [6:0] k_buf_0_val_3_addr_reg_2546;
reg   [6:0] k_buf_0_val_4_addr_reg_2552;
reg   [6:0] k_buf_0_val_5_addr_reg_2558;
wire   [0:0] or_cond_i_fu_833_p2;
reg   [0:0] or_cond_i_reg_2564_pp0_iter1_reg;
reg   [6:0] k_buf_1_val_3_addr_reg_2568;
reg   [6:0] k_buf_1_val_4_addr_reg_2574;
reg   [6:0] k_buf_1_val_5_addr_reg_2580;
reg   [6:0] k_buf_2_val_3_addr_reg_2586;
reg   [6:0] k_buf_2_val_4_addr_reg_2592;
reg   [6:0] k_buf_2_val_5_addr_reg_2598;
wire   [7:0] src_kernel_win_0_va_17_fu_969_p3;
reg   [7:0] src_kernel_win_0_va_17_reg_2604;
wire   [7:0] src_kernel_win_0_va_18_fu_987_p3;
reg   [7:0] src_kernel_win_0_va_18_reg_2610;
reg   [7:0] src_kernel_win_0_va_24_reg_2616;
wire   [18:0] tmp40_fu_1042_p2;
reg   [18:0] tmp40_reg_2621;
wire   [7:0] src_kernel_win_1_va_17_fu_1170_p3;
reg   [7:0] src_kernel_win_1_va_17_reg_2626;
wire   [7:0] src_kernel_win_1_va_18_fu_1188_p3;
reg   [7:0] src_kernel_win_1_va_18_reg_2632;
reg   [7:0] src_kernel_win_1_va_24_reg_2638;
wire   [18:0] tmp48_fu_1243_p2;
reg   [18:0] tmp48_reg_2643;
wire   [7:0] src_kernel_win_2_va_20_fu_1353_p3;
reg   [7:0] src_kernel_win_2_va_20_reg_2648;
wire   [7:0] src_kernel_win_2_va_21_fu_1371_p3;
reg   [7:0] src_kernel_win_2_va_21_reg_2654;
reg   [7:0] src_kernel_win_2_va_27_reg_2660;
wire   [18:0] tmp56_fu_1426_p2;
reg   [18:0] tmp56_reg_2665;
wire   [21:0] p_Val2_s_fu_1623_p2;
reg   [21:0] p_Val2_s_reg_2670;
reg   [7:0] p_Val2_12_reg_2675;
reg   [0:0] tmp_84_reg_2680;
wire   [21:0] p_Val2_15_fu_1799_p2;
reg   [21:0] p_Val2_15_reg_2685;
reg   [7:0] p_Val2_16_reg_2690;
reg   [0:0] tmp_90_reg_2695;
wire   [21:0] p_Val2_19_fu_1975_p2;
reg   [21:0] p_Val2_19_reg_2700;
reg   [7:0] p_Val2_20_reg_2705;
reg   [0:0] tmp_96_reg_2710;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state5;
wire   [6:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [6:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [6:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [6:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [6:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [6:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [6:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
wire   [6:0] k_buf_1_val_3_address1;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [6:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
wire   [6:0] k_buf_1_val_4_address1;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [6:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
wire   [6:0] k_buf_1_val_5_address1;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [6:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
wire   [6:0] k_buf_2_val_3_address1;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [6:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
wire   [6:0] k_buf_2_val_4_address1;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [6:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
wire   [6:0] k_buf_2_val_5_address1;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_25_reg_568;
wire   [0:0] tmp_27_fu_607_p2;
reg    ap_block_state1;
reg   [6:0] t_V_reg_579;
wire    ap_CS_fsm_state8;
wire   [63:0] tmp_39_fu_820_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_226;
reg   [7:0] src_kernel_win_0_va_12_fu_230;
reg   [7:0] src_kernel_win_0_va_13_fu_234;
reg   [7:0] src_kernel_win_0_va_14_fu_238;
reg   [7:0] src_kernel_win_0_va_15_fu_242;
wire   [7:0] src_kernel_win_0_va_19_fu_1005_p3;
reg   [7:0] src_kernel_win_0_va_16_fu_246;
reg   [7:0] src_kernel_win_1_va_fu_250;
reg   [7:0] src_kernel_win_1_va_12_fu_254;
reg   [7:0] src_kernel_win_1_va_13_fu_258;
reg   [7:0] src_kernel_win_1_va_14_fu_262;
reg   [7:0] src_kernel_win_1_va_15_fu_266;
wire   [7:0] src_kernel_win_1_va_19_fu_1206_p3;
reg   [7:0] src_kernel_win_1_va_16_fu_270;
reg   [7:0] src_kernel_win_2_va_fu_274;
reg   [7:0] src_kernel_win_2_va_12_fu_278;
reg   [7:0] src_kernel_win_2_va_13_fu_282;
reg   [7:0] src_kernel_win_2_va_14_fu_286;
reg   [7:0] src_kernel_win_2_va_15_fu_290;
wire   [7:0] src_kernel_win_2_va_22_fu_1389_p3;
reg   [7:0] src_kernel_win_2_va_16_fu_294;
reg   [7:0] right_border_buf_0_s_fu_298;
wire   [7:0] col_buf_0_val_0_0_fu_876_p3;
reg   [7:0] right_border_buf_0_15_fu_302;
reg   [7:0] right_border_buf_2_s_fu_306;
reg   [7:0] right_border_buf_0_16_fu_310;
wire   [7:0] col_buf_0_val_1_0_fu_894_p3;
reg   [7:0] right_border_buf_0_17_fu_314;
reg   [7:0] right_border_buf_2_12_fu_318;
wire   [7:0] col_buf_2_val_2_0_fu_1305_p3;
reg   [7:0] right_border_buf_0_18_fu_322;
wire   [7:0] col_buf_0_val_2_0_fu_912_p3;
reg   [7:0] right_border_buf_0_19_fu_326;
reg   [7:0] right_border_buf_2_13_fu_330;
reg   [7:0] right_border_buf_1_s_fu_334;
wire   [7:0] col_buf_1_val_0_0_fu_1077_p3;
reg   [7:0] right_border_buf_1_15_fu_338;
reg   [7:0] right_border_buf_2_14_fu_342;
wire   [7:0] col_buf_2_val_1_0_fu_1287_p3;
reg   [7:0] right_border_buf_1_16_fu_346;
wire   [7:0] col_buf_1_val_1_0_fu_1095_p3;
reg   [7:0] right_border_buf_1_17_fu_350;
reg   [7:0] right_border_buf_2_15_fu_354;
reg   [7:0] right_border_buf_1_18_fu_358;
wire   [7:0] col_buf_1_val_2_0_fu_1113_p3;
reg   [7:0] right_border_buf_1_19_fu_362;
reg   [7:0] right_border_buf_2_16_fu_366;
wire   [7:0] col_buf_2_val_0_0_fu_1269_p3;
wire   [5:0] tmp_fu_637_p4;
wire   [5:0] tmp_78_fu_703_p4;
wire   [7:0] t_V_4_cast_fu_687_p1;
wire   [7:0] ImagLoc_x_fu_719_p2;
wire   [0:0] tmp_79_fu_725_p3;
wire   [0:0] tmp_36_fu_739_p2;
wire   [0:0] rev_fu_733_p2;
wire   [0:0] tmp_80_fu_751_p3;
wire   [7:0] p_assign_9_fu_759_p2;
wire   [7:0] p_p2_i_i_fu_765_p3;
wire   [0:0] tmp_38_fu_773_p2;
wire   [7:0] p_assign_s_fu_779_p2;
wire   [7:0] p_p2_i_i_0_p_assign_s_fu_785_p3;
wire  signed [7:0] x_fu_793_p3;
wire   [1:0] tmp_81_fu_801_p1;
wire  signed [31:0] x_cast_fu_805_p1;
wire   [0:0] icmp2_fu_713_p2;
wire   [7:0] tmp_40_fu_865_p5;
wire   [7:0] tmp_41_fu_883_p5;
wire   [7:0] tmp_42_fu_901_p5;
wire   [7:0] tmp_43_fu_958_p5;
wire   [7:0] tmp_44_fu_976_p5;
wire   [7:0] tmp_45_fu_994_p5;
wire   [17:0] r_V_4_fu_1018_p3;
wire   [17:0] r_V_4_0_0_2_fu_1030_p3;
wire   [18:0] tmp_285_0_0_cast_ca_fu_1026_p1;
wire   [18:0] tmp_285_0_0_2_cast_c_fu_1038_p1;
wire   [7:0] tmp_46_fu_1066_p5;
wire   [7:0] tmp_47_fu_1084_p5;
wire   [7:0] tmp_48_fu_1102_p5;
wire   [7:0] tmp_49_fu_1159_p5;
wire   [7:0] tmp_50_fu_1177_p5;
wire   [7:0] tmp_51_fu_1195_p5;
wire   [17:0] r_V_4_1_fu_1219_p3;
wire   [17:0] r_V_4_1_0_2_fu_1231_p3;
wire   [18:0] tmp_285_1_0_cast_ca_fu_1227_p1;
wire   [18:0] tmp_285_1_0_2_cast_c_fu_1239_p1;
wire   [7:0] tmp_52_fu_1258_p5;
wire   [7:0] tmp_53_fu_1276_p5;
wire   [7:0] tmp_54_fu_1294_p5;
wire   [7:0] tmp_55_fu_1342_p5;
wire   [7:0] tmp_56_fu_1360_p5;
wire   [7:0] tmp_57_fu_1378_p5;
wire   [17:0] r_V_4_2_fu_1402_p3;
wire   [17:0] r_V_4_2_0_2_fu_1414_p3;
wire   [18:0] tmp_285_2_0_cast_ca_fu_1410_p1;
wire   [18:0] tmp_285_2_0_2_cast_c_fu_1422_p1;
wire   [18:0] r_V_4_0_0_1_fu_1483_p3;
wire   [19:0] tmp40_cast_fu_1494_p1;
wire   [19:0] tmp_285_0_0_1_cast_fu_1490_p1;
wire   [19:0] sum_V_0_0_2_fu_1497_p2;
wire   [18:0] r_V_4_0_1_fu_1507_p3;
wire   [20:0] sum_V_0_0_2_cast_fu_1503_p1;
wire   [20:0] tmp_285_0_1_cast_fu_1515_p1;
wire   [20:0] sum_V_0_1_fu_1519_p2;
wire   [19:0] r_V_4_0_1_1_fu_1529_p3;
wire   [18:0] r_V_4_0_1_2_fu_1541_p3;
wire   [17:0] r_V_4_0_2_fu_1552_p3;
wire   [18:0] r_V_4_0_2_1_fu_1564_p3;
wire   [17:0] r_V_4_0_2_2_fu_1576_p3;
wire   [20:0] tmp_285_0_1_1_cast_c_fu_1537_p1;
wire   [20:0] tmp_285_0_2_1_cast_c_fu_1572_p1;
wire   [20:0] tmp45_fu_1587_p2;
wire   [21:0] tmp45_cast_fu_1593_p1;
wire   [21:0] sum_V_0_1_cast_fu_1525_p1;
wire   [18:0] tmp_285_0_2_cast_ca_fu_1560_p1;
wire   [18:0] tmp_285_0_2_2_cast_c_fu_1583_p1;
wire   [18:0] tmp47_fu_1603_p2;
wire   [19:0] tmp47_cast_fu_1609_p1;
wire   [19:0] tmp_285_0_1_2_cast_c_fu_1548_p1;
wire   [19:0] tmp46_fu_1613_p2;
wire   [21:0] tmp46_cast_fu_1619_p1;
wire   [21:0] tmp44_fu_1597_p2;
wire   [18:0] r_V_4_1_0_1_fu_1659_p3;
wire   [19:0] tmp48_cast_fu_1670_p1;
wire   [19:0] tmp_285_1_0_1_cast_fu_1666_p1;
wire   [19:0] sum_V_1_0_2_fu_1673_p2;
wire   [18:0] r_V_4_1_1_fu_1683_p3;
wire   [20:0] sum_V_1_0_2_cast_fu_1679_p1;
wire   [20:0] tmp_285_1_1_cast_fu_1691_p1;
wire   [20:0] sum_V_1_1_fu_1695_p2;
wire   [19:0] r_V_4_1_1_1_fu_1705_p3;
wire   [18:0] r_V_4_1_1_2_fu_1717_p3;
wire   [17:0] r_V_4_1_2_fu_1728_p3;
wire   [18:0] r_V_4_1_2_1_fu_1740_p3;
wire   [17:0] r_V_4_1_2_2_fu_1752_p3;
wire   [20:0] tmp_285_1_1_1_cast_c_fu_1713_p1;
wire   [20:0] tmp_285_1_2_1_cast_c_fu_1748_p1;
wire   [20:0] tmp53_fu_1763_p2;
wire   [21:0] tmp53_cast_fu_1769_p1;
wire   [21:0] sum_V_1_1_cast_fu_1701_p1;
wire   [18:0] tmp_285_1_2_cast_ca_fu_1736_p1;
wire   [18:0] tmp_285_1_2_2_cast_c_fu_1759_p1;
wire   [18:0] tmp55_fu_1779_p2;
wire   [19:0] tmp55_cast_fu_1785_p1;
wire   [19:0] tmp_285_1_1_2_cast_c_fu_1724_p1;
wire   [19:0] tmp54_fu_1789_p2;
wire   [21:0] tmp54_cast_fu_1795_p1;
wire   [21:0] tmp52_fu_1773_p2;
wire   [18:0] r_V_4_2_0_1_fu_1835_p3;
wire   [19:0] tmp56_cast_fu_1846_p1;
wire   [19:0] tmp_285_2_0_1_cast_fu_1842_p1;
wire   [19:0] sum_V_2_0_2_fu_1849_p2;
wire   [18:0] r_V_4_2_1_fu_1859_p3;
wire   [20:0] sum_V_2_0_2_cast_fu_1855_p1;
wire   [20:0] tmp_285_2_1_cast_fu_1867_p1;
wire   [20:0] sum_V_2_1_fu_1871_p2;
wire   [19:0] r_V_4_2_1_1_fu_1881_p3;
wire   [18:0] r_V_4_2_1_2_fu_1893_p3;
wire   [17:0] r_V_4_2_2_fu_1904_p3;
wire   [18:0] r_V_4_2_2_1_fu_1916_p3;
wire   [17:0] r_V_4_2_2_2_fu_1928_p3;
wire   [20:0] tmp_285_2_1_1_cast_c_fu_1889_p1;
wire   [20:0] tmp_285_2_2_1_cast_c_fu_1924_p1;
wire   [20:0] tmp61_fu_1939_p2;
wire   [21:0] tmp61_cast_fu_1945_p1;
wire   [21:0] sum_V_2_1_cast_fu_1877_p1;
wire   [18:0] tmp_285_2_2_cast_ca_fu_1912_p1;
wire   [18:0] tmp_285_2_2_2_cast_c_fu_1935_p1;
wire   [18:0] tmp63_fu_1955_p2;
wire   [19:0] tmp63_cast_fu_1961_p1;
wire   [19:0] tmp_285_2_1_2_cast_c_fu_1900_p1;
wire   [19:0] tmp62_fu_1965_p2;
wire   [21:0] tmp62_cast_fu_1971_p1;
wire   [21:0] tmp60_fu_1949_p2;
wire   [7:0] tmp_i_cast_i_fu_2071_p1;
wire   [0:0] tmp_85_fu_2079_p3;
wire   [7:0] p_Val2_13_fu_2074_p2;
wire   [0:0] tmp_86_fu_2092_p3;
wire   [0:0] rev1_fu_2086_p2;
wire   [0:0] deleted_zeros_fu_2100_p2;
wire   [7:0] tmp_i_cast_i1_fu_2115_p1;
wire   [0:0] tmp_91_fu_2123_p3;
wire   [7:0] p_Val2_17_fu_2118_p2;
wire   [0:0] tmp_92_fu_2136_p3;
wire   [0:0] rev2_fu_2130_p2;
wire   [0:0] deleted_zeros_1_fu_2144_p2;
wire   [7:0] tmp_i_cast_i2_fu_2159_p1;
wire   [0:0] tmp_97_fu_2167_p3;
wire   [7:0] p_Val2_21_fu_2162_p2;
wire   [0:0] tmp_98_fu_2180_p3;
wire   [0:0] rev3_fu_2174_p2;
wire   [0:0] deleted_zeros_2_fu_2188_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_112;
reg    ap_enable_state4_pp0_iter0_stage0;
reg    ap_enable_operation_168;
reg    ap_enable_state5_pp0_iter1_stage0;
reg    ap_predicate_op182_store_state5;
reg    ap_enable_operation_182;
reg    ap_predicate_op190_store_state5;
reg    ap_enable_operation_190;
reg    ap_enable_operation_114;
reg    ap_enable_operation_171;
reg    ap_predicate_op180_store_state5;
reg    ap_enable_operation_180;
reg    ap_predicate_op188_store_state5;
reg    ap_enable_operation_188;
reg    ap_enable_operation_116;
reg    ap_enable_operation_174;
reg    ap_predicate_op178_store_state5;
reg    ap_enable_operation_178;
reg    ap_predicate_op187_store_state5;
reg    ap_enable_operation_187;
reg    ap_enable_operation_127;
reg    ap_enable_operation_217;
reg    ap_predicate_op231_store_state5;
reg    ap_enable_operation_231;
reg    ap_predicate_op239_store_state5;
reg    ap_enable_operation_239;
reg    ap_enable_operation_129;
reg    ap_enable_operation_220;
reg    ap_predicate_op229_store_state5;
reg    ap_enable_operation_229;
reg    ap_predicate_op237_store_state5;
reg    ap_enable_operation_237;
reg    ap_enable_operation_131;
reg    ap_enable_operation_223;
reg    ap_predicate_op227_store_state5;
reg    ap_enable_operation_227;
reg    ap_predicate_op236_store_state5;
reg    ap_enable_operation_236;
reg    ap_enable_operation_141;
reg    ap_enable_operation_263;
reg    ap_predicate_op277_store_state5;
reg    ap_enable_operation_277;
reg    ap_predicate_op282_store_state5;
reg    ap_enable_operation_282;
reg    ap_enable_operation_143;
reg    ap_enable_operation_266;
reg    ap_predicate_op275_store_state5;
reg    ap_enable_operation_275;
reg    ap_predicate_op280_store_state5;
reg    ap_enable_operation_280;
reg    ap_enable_operation_145;
reg    ap_enable_operation_269;
reg    ap_predicate_op273_store_state5;
reg    ap_enable_operation_273;
reg    ap_predicate_op279_store_state5;
reg    ap_enable_operation_279;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1525;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_address1),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_address1),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_address1),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_address1),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_address1),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_1_k_buf_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_address1),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U21(
    .din0(right_border_buf_0_s_fu_298),
    .din1(right_border_buf_0_15_fu_302),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_40_fu_865_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U22(
    .din0(right_border_buf_0_16_fu_310),
    .din1(right_border_buf_0_17_fu_314),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_41_fu_883_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U23(
    .din0(right_border_buf_0_18_fu_322),
    .din1(right_border_buf_0_19_fu_326),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_42_fu_901_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U24(
    .din0(col_buf_0_val_0_0_fu_876_p3),
    .din1(col_buf_0_val_1_0_fu_894_p3),
    .din2(col_buf_0_val_2_0_fu_912_p3),
    .din3(tmp_77_reg_2486),
    .dout(tmp_43_fu_958_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U25(
    .din0(col_buf_0_val_0_0_fu_876_p3),
    .din1(col_buf_0_val_1_0_fu_894_p3),
    .din2(col_buf_0_val_2_0_fu_912_p3),
    .din3(row_assign_12_0_1_t_reg_2493),
    .dout(tmp_44_fu_976_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U26(
    .din0(col_buf_0_val_0_0_fu_876_p3),
    .din1(col_buf_0_val_1_0_fu_894_p3),
    .din2(col_buf_0_val_2_0_fu_912_p3),
    .din3(row_assign_12_0_2_t_reg_2500),
    .dout(tmp_45_fu_994_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U27(
    .din0(right_border_buf_1_s_fu_334),
    .din1(right_border_buf_1_15_fu_338),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_46_fu_1066_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U28(
    .din0(right_border_buf_1_16_fu_346),
    .din1(right_border_buf_1_17_fu_350),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_47_fu_1084_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U29(
    .din0(right_border_buf_1_18_fu_358),
    .din1(right_border_buf_1_19_fu_362),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_48_fu_1102_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U30(
    .din0(col_buf_1_val_0_0_fu_1077_p3),
    .din1(col_buf_1_val_1_0_fu_1095_p3),
    .din2(col_buf_1_val_2_0_fu_1113_p3),
    .din3(tmp_77_reg_2486),
    .dout(tmp_49_fu_1159_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U31(
    .din0(col_buf_1_val_0_0_fu_1077_p3),
    .din1(col_buf_1_val_1_0_fu_1095_p3),
    .din2(col_buf_1_val_2_0_fu_1113_p3),
    .din3(row_assign_12_0_1_t_reg_2493),
    .dout(tmp_50_fu_1177_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U32(
    .din0(col_buf_1_val_0_0_fu_1077_p3),
    .din1(col_buf_1_val_1_0_fu_1095_p3),
    .din2(col_buf_1_val_2_0_fu_1113_p3),
    .din3(row_assign_12_0_2_t_reg_2500),
    .dout(tmp_51_fu_1195_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U33(
    .din0(right_border_buf_2_16_fu_366),
    .din1(right_border_buf_2_15_fu_354),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_52_fu_1258_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U34(
    .din0(right_border_buf_2_14_fu_342),
    .din1(right_border_buf_2_13_fu_330),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_53_fu_1276_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U35(
    .din0(right_border_buf_2_12_fu_318),
    .din1(right_border_buf_2_s_fu_306),
    .din2(8'd0),
    .din3(col_assign_4_reg_2520),
    .dout(tmp_54_fu_1294_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U36(
    .din0(col_buf_2_val_0_0_fu_1269_p3),
    .din1(col_buf_2_val_1_0_fu_1287_p3),
    .din2(col_buf_2_val_2_0_fu_1305_p3),
    .din3(tmp_77_reg_2486),
    .dout(tmp_55_fu_1342_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U37(
    .din0(col_buf_2_val_0_0_fu_1269_p3),
    .din1(col_buf_2_val_1_0_fu_1287_p3),
    .din2(col_buf_2_val_2_0_fu_1305_p3),
    .din3(row_assign_12_0_1_t_reg_2493),
    .dout(tmp_56_fu_1360_p5)
);

ced_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ced_mux_32_8_1_1_U38(
    .din0(col_buf_2_val_0_0_fu_1269_p3),
    .din1(col_buf_2_val_1_0_fu_1287_p3),
    .din2(col_buf_2_val_2_0_fu_1305_p3),
    .din3(row_assign_12_0_2_t_reg_2500),
    .dout(tmp_57_fu_1378_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond462_i_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond461_i_fu_691_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond462_i_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state5)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((exitcond462_i_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_3_reg_590 <= j_V_fu_697_p2;
    end else if (((exitcond462_i_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_3_reg_590 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_27_fu_607_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_579 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        t_V_reg_579 <= i_V_reg_2446;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_25_reg_568 <= 2'd0;
    end else if (((tmp_27_fu_607_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_25_reg_568 <= tmp_26_fu_601_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2533 <= brmerge_fu_815_p2;
        col_assign_4_reg_2520 <= col_assign_4_fu_809_p2;
        k_buf_0_val_3_addr_reg_2546 <= tmp_39_fu_820_p1;
        k_buf_0_val_4_addr_reg_2552 <= tmp_39_fu_820_p1;
        k_buf_0_val_5_addr_reg_2558 <= tmp_39_fu_820_p1;
        k_buf_1_val_3_addr_reg_2568 <= tmp_39_fu_820_p1;
        k_buf_1_val_4_addr_reg_2574 <= tmp_39_fu_820_p1;
        k_buf_1_val_5_addr_reg_2580 <= tmp_39_fu_820_p1;
        k_buf_2_val_3_addr_reg_2586 <= tmp_39_fu_820_p1;
        k_buf_2_val_4_addr_reg_2592 <= tmp_39_fu_820_p1;
        k_buf_2_val_5_addr_reg_2598 <= tmp_39_fu_820_p1;
        or_cond_i_i_reg_2516 <= or_cond_i_i_fu_745_p2;
        or_cond_i_reg_2564 <= or_cond_i_fu_833_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond461_i_reg_2507 <= exitcond461_i_fu_691_p2;
        exitcond461_i_reg_2507_pp0_iter1_reg <= exitcond461_i_reg_2507;
        or_cond_i_reg_2564_pp0_iter1_reg <= or_cond_i_reg_2564;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2446 <= i_V_fu_619_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond462_i_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2460 <= icmp_fu_647_p2;
        row_assign_12_0_1_t_reg_2493 <= row_assign_12_0_1_t_fu_675_p2;
        row_assign_12_0_2_t_reg_2500 <= row_assign_12_0_2_t_fu_681_p2;
        tmp_199_0_0_not_reg_2455 <= tmp_199_0_0_not_fu_631_p2;
        tmp_243_0_1_reg_2469 <= tmp_243_0_1_fu_659_p2;
        tmp_29_reg_2451 <= tmp_29_fu_625_p2;
        tmp_31_reg_2465 <= tmp_31_fu_653_p2;
        tmp_32_reg_2473 <= tmp_32_fu_665_p2;
        tmp_77_reg_2486 <= tmp_77_fu_671_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond_i_reg_2564_pp0_iter2_reg <= or_cond_i_reg_2564_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2564_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_12_reg_2675 <= {{p_Val2_s_fu_1623_p2[21:14]}};
        p_Val2_15_reg_2685[21 : 10] <= p_Val2_15_fu_1799_p2[21 : 10];
        p_Val2_16_reg_2690 <= {{p_Val2_15_fu_1799_p2[21:14]}};
        p_Val2_19_reg_2700[21 : 10] <= p_Val2_19_fu_1975_p2[21 : 10];
        p_Val2_20_reg_2705 <= {{p_Val2_19_fu_1975_p2[21:14]}};
        p_Val2_s_reg_2670[21 : 10] <= p_Val2_s_fu_1623_p2[21 : 10];
        tmp_84_reg_2680 <= p_Val2_s_fu_1623_p2[32'd13];
        tmp_90_reg_2695 <= p_Val2_15_fu_1799_p2[32'd13];
        tmp_96_reg_2710 <= p_Val2_19_fu_1975_p2[32'd13];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_15_fu_302 <= right_border_buf_0_s_fu_298;
        right_border_buf_0_16_fu_310 <= col_buf_0_val_1_0_fu_894_p3;
        right_border_buf_0_17_fu_314 <= right_border_buf_0_16_fu_310;
        right_border_buf_0_18_fu_322 <= col_buf_0_val_2_0_fu_912_p3;
        right_border_buf_0_19_fu_326 <= right_border_buf_0_18_fu_322;
        right_border_buf_0_s_fu_298 <= col_buf_0_val_0_0_fu_876_p3;
        right_border_buf_1_15_fu_338 <= right_border_buf_1_s_fu_334;
        right_border_buf_1_16_fu_346 <= col_buf_1_val_1_0_fu_1095_p3;
        right_border_buf_1_17_fu_350 <= right_border_buf_1_16_fu_346;
        right_border_buf_1_18_fu_358 <= col_buf_1_val_2_0_fu_1113_p3;
        right_border_buf_1_19_fu_362 <= right_border_buf_1_18_fu_358;
        right_border_buf_1_s_fu_334 <= col_buf_1_val_0_0_fu_1077_p3;
        right_border_buf_2_12_fu_318 <= col_buf_2_val_2_0_fu_1305_p3;
        right_border_buf_2_13_fu_330 <= right_border_buf_2_14_fu_342;
        right_border_buf_2_14_fu_342 <= col_buf_2_val_1_0_fu_1287_p3;
        right_border_buf_2_15_fu_354 <= right_border_buf_2_16_fu_366;
        right_border_buf_2_16_fu_366 <= col_buf_2_val_0_0_fu_1269_p3;
        right_border_buf_2_s_fu_306 <= right_border_buf_2_12_fu_318;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2507_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_12_fu_230 <= src_kernel_win_0_va_fu_226;
        src_kernel_win_0_va_13_fu_234 <= src_kernel_win_0_va_18_reg_2610;
        src_kernel_win_0_va_14_fu_238 <= src_kernel_win_0_va_13_fu_234;
        src_kernel_win_0_va_fu_226 <= src_kernel_win_0_va_17_reg_2604;
        src_kernel_win_1_va_12_fu_254 <= src_kernel_win_1_va_fu_250;
        src_kernel_win_1_va_13_fu_258 <= src_kernel_win_1_va_18_reg_2632;
        src_kernel_win_1_va_14_fu_262 <= src_kernel_win_1_va_13_fu_258;
        src_kernel_win_1_va_fu_250 <= src_kernel_win_1_va_17_reg_2626;
        src_kernel_win_2_va_12_fu_278 <= src_kernel_win_2_va_fu_274;
        src_kernel_win_2_va_13_fu_282 <= src_kernel_win_2_va_21_reg_2654;
        src_kernel_win_2_va_14_fu_286 <= src_kernel_win_2_va_13_fu_282;
        src_kernel_win_2_va_fu_274 <= src_kernel_win_2_va_20_reg_2648;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_15_fu_242 <= src_kernel_win_0_va_19_fu_1005_p3;
        src_kernel_win_0_va_16_fu_246 <= src_kernel_win_0_va_15_fu_242;
        src_kernel_win_1_va_15_fu_266 <= src_kernel_win_1_va_19_fu_1206_p3;
        src_kernel_win_1_va_16_fu_270 <= src_kernel_win_1_va_15_fu_266;
        src_kernel_win_2_va_15_fu_290 <= src_kernel_win_2_va_22_fu_1389_p3;
        src_kernel_win_2_va_16_fu_294 <= src_kernel_win_2_va_15_fu_290;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2507 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_17_reg_2604 <= src_kernel_win_0_va_17_fu_969_p3;
        src_kernel_win_0_va_18_reg_2610 <= src_kernel_win_0_va_18_fu_987_p3;
        src_kernel_win_1_va_17_reg_2626 <= src_kernel_win_1_va_17_fu_1170_p3;
        src_kernel_win_1_va_18_reg_2632 <= src_kernel_win_1_va_18_fu_1188_p3;
        src_kernel_win_2_va_20_reg_2648 <= src_kernel_win_2_va_20_fu_1353_p3;
        src_kernel_win_2_va_21_reg_2654 <= src_kernel_win_2_va_21_fu_1371_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2564 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_24_reg_2616 <= src_kernel_win_0_va_15_fu_242;
        src_kernel_win_1_va_24_reg_2638 <= src_kernel_win_1_va_15_fu_266;
        src_kernel_win_2_va_27_reg_2660 <= src_kernel_win_2_va_15_fu_290;
        tmp40_reg_2621[18 : 10] <= tmp40_fu_1042_p2[18 : 10];
        tmp48_reg_2643[18 : 10] <= tmp48_fu_1243_p2[18 : 10];
        tmp56_reg_2665[18 : 10] <= tmp56_fu_1426_p2[18 : 10];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond462_i_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond462_i_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1525)) begin
        if (((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_243_0_1_reg_2469 == 1'd1) & (icmp_reg_2460 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1525)) begin
        if (((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_31_reg_2465 == 1'd1) & (icmp_reg_2460 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1525)) begin
        if (((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1))) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if (((tmp_243_0_1_reg_2469 == 1'd1) & (icmp_reg_2460 == 1'd0))) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1525)) begin
        if (((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1))) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if (((tmp_31_reg_2465 == 1'd1) & (icmp_reg_2460 == 1'd0))) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1525)) begin
        if (((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1))) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if (((tmp_243_0_1_reg_2469 == 1'd1) & (icmp_reg_2460 == 1'd0))) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1525)) begin
        if (((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1))) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if (((tmp_31_reg_2465 == 1'd1) & (icmp_reg_2460 == 1'd0))) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op189_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op177_read_state5 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op238_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op226_read_state5 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op281_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state5 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_27_fu_607_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond462_i_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_719_p2 = ($signed(8'd255) + $signed(t_V_4_cast_fu_687_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op281_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op272_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op238_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op226_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op189_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op177_read_state5 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op281_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op272_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op238_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op226_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op189_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op177_read_state5 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op281_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op272_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op238_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op226_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op189_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op177_read_state5 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op281_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op272_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op238_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op226_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op189_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op177_read_state5 == 1'b1)));
end

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter3 = (((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2564_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1525 = ((or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_operation_112 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_114 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_116 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_127 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_129 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_131 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_141 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_143 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_145 = (exitcond461_i_fu_691_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_168 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_171 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_174 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_178 = (ap_predicate_op178_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_180 = (ap_predicate_op180_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_182 = (ap_predicate_op182_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_187 = (ap_predicate_op187_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_188 = (ap_predicate_op188_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_190 = (ap_predicate_op190_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_217 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_220 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_223 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_227 = (ap_predicate_op227_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_229 = (ap_predicate_op229_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_231 = (ap_predicate_op231_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_236 = (ap_predicate_op236_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_237 = (ap_predicate_op237_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_239 = (ap_predicate_op239_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_263 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_266 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_269 = (exitcond461_i_reg_2507 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_273 = (ap_predicate_op273_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_275 = (ap_predicate_op275_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_277 = (ap_predicate_op277_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_279 = (ap_predicate_op279_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_280 = (ap_predicate_op280_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_282 = (ap_predicate_op282_store_state5 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter0_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op177_read_state5 = ((or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op178_store_state5 = ((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_store_state5 = ((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op182_store_state5 = ((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op187_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op188_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op189_read_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op190_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op226_read_state5 = ((or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op227_store_state5 = ((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op229_store_state5 = ((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op231_store_state5 = ((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op236_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op237_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op238_read_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op239_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op272_read_state5 = ((or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op273_store_state5 = ((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op275_store_state5 = ((tmp_243_0_1_reg_2469 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op277_store_state5 = ((tmp_31_reg_2465 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (icmp_reg_2460 == 1'd0) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op279_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op280_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op281_read_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

always @ (*) begin
    ap_predicate_op282_store_state5 = ((tmp_29_reg_2451 == 1'd1) & (icmp_reg_2460 == 1'd1) & (or_cond_i_i_reg_2516 == 1'd1) & (exitcond461_i_reg_2507 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign brmerge_fu_815_p2 = (tmp_36_fu_739_p2 | tmp_199_0_0_not_reg_2455);

assign col_assign_4_fu_809_p2 = (tmp_81_fu_801_p1 ^ 2'd3);

assign col_buf_0_val_0_0_fu_876_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_40_fu_865_p5);

assign col_buf_0_val_1_0_fu_894_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_41_fu_883_p5);

assign col_buf_0_val_2_0_fu_912_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_42_fu_901_p5);

assign col_buf_1_val_0_0_fu_1077_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_46_fu_1066_p5);

assign col_buf_1_val_1_0_fu_1095_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_47_fu_1084_p5);

assign col_buf_1_val_2_0_fu_1113_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_48_fu_1102_p5);

assign col_buf_2_val_0_0_fu_1269_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_52_fu_1258_p5);

assign col_buf_2_val_1_0_fu_1287_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_53_fu_1276_p5);

assign col_buf_2_val_2_0_fu_1305_p3 = ((brmerge_reg_2533[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_54_fu_1294_p5);

assign deleted_zeros_1_fu_2144_p2 = (tmp_92_fu_2136_p3 | rev2_fu_2130_p2);

assign deleted_zeros_2_fu_2188_p2 = (tmp_98_fu_2180_p3 | rev3_fu_2174_p2);

assign deleted_zeros_fu_2100_p2 = (tmp_86_fu_2092_p3 | rev1_fu_2086_p2);

assign exitcond461_i_fu_691_p2 = ((t_V_3_reg_590 == 7'd102) ? 1'b1 : 1'b0);

assign exitcond462_i_fu_613_p2 = ((t_V_reg_579 == 7'd102) ? 1'b1 : 1'b0);

assign i_V_fu_619_p2 = (t_V_reg_579 + 7'd1);

assign icmp2_fu_713_p2 = ((tmp_78_fu_703_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_fu_647_p2 = ((tmp_fu_637_p4 != 6'd0) ? 1'b1 : 1'b0);

assign j_V_fu_697_p2 = (t_V_3_reg_590 + 7'd1);

assign k_buf_0_val_3_address0 = tmp_39_fu_820_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_2546;

assign k_buf_0_val_4_address0 = tmp_39_fu_820_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_2552;

assign k_buf_0_val_5_address0 = tmp_39_fu_820_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_2558;

assign k_buf_1_val_3_address0 = tmp_39_fu_820_p1;

assign k_buf_1_val_3_address1 = k_buf_1_val_3_addr_reg_2568;

assign k_buf_1_val_4_address0 = tmp_39_fu_820_p1;

assign k_buf_1_val_4_address1 = k_buf_1_val_4_addr_reg_2574;

assign k_buf_1_val_5_address0 = tmp_39_fu_820_p1;

assign k_buf_1_val_5_address1 = k_buf_1_val_5_addr_reg_2580;

assign k_buf_2_val_3_address0 = tmp_39_fu_820_p1;

assign k_buf_2_val_3_address1 = k_buf_2_val_3_addr_reg_2586;

assign k_buf_2_val_4_address0 = tmp_39_fu_820_p1;

assign k_buf_2_val_4_address1 = k_buf_2_val_4_addr_reg_2592;

assign k_buf_2_val_5_address0 = tmp_39_fu_820_p1;

assign k_buf_2_val_5_address1 = k_buf_2_val_5_addr_reg_2598;

assign or_cond_i_fu_833_p2 = (icmp_reg_2460 & icmp2_fu_713_p2);

assign or_cond_i_i_fu_745_p2 = (tmp_36_fu_739_p2 & rev_fu_733_p2);

assign p_Val2_13_fu_2074_p2 = (p_Val2_12_reg_2675 + tmp_i_cast_i_fu_2071_p1);

assign p_Val2_15_fu_1799_p2 = (tmp54_cast_fu_1795_p1 + tmp52_fu_1773_p2);

assign p_Val2_17_fu_2118_p2 = (p_Val2_16_reg_2690 + tmp_i_cast_i1_fu_2115_p1);

assign p_Val2_19_fu_1975_p2 = (tmp62_cast_fu_1971_p1 + tmp60_fu_1949_p2);

assign p_Val2_21_fu_2162_p2 = (p_Val2_20_reg_2705 + tmp_i_cast_i2_fu_2159_p1);

assign p_Val2_s_fu_1623_p2 = (tmp46_cast_fu_1619_p1 + tmp44_fu_1597_p2);

assign p_assign_9_fu_759_p2 = (8'd1 - t_V_4_cast_fu_687_p1);

assign p_assign_s_fu_779_p2 = ($signed(8'd198) - $signed(p_p2_i_i_fu_765_p3));

assign p_dst_data_stream_0_V_din = ((deleted_zeros_fu_2100_p2[0:0] === 1'b1) ? p_Val2_13_fu_2074_p2 : 8'd255);

assign p_dst_data_stream_1_V_din = ((deleted_zeros_1_fu_2144_p2[0:0] === 1'b1) ? p_Val2_17_fu_2118_p2 : 8'd255);

assign p_dst_data_stream_2_V_din = ((deleted_zeros_2_fu_2188_p2[0:0] === 1'b1) ? p_Val2_21_fu_2162_p2 : 8'd255);

assign p_p2_i_i_0_p_assign_s_fu_785_p3 = ((tmp_38_fu_773_p2[0:0] === 1'b1) ? p_p2_i_i_fu_765_p3 : p_assign_s_fu_779_p2);

assign p_p2_i_i_fu_765_p3 = ((tmp_80_fu_751_p3[0:0] === 1'b1) ? p_assign_9_fu_759_p2 : ImagLoc_x_fu_719_p2);

assign r_V_4_0_0_1_fu_1483_p3 = {{src_kernel_win_0_va_24_reg_2616}, {11'd0}};

assign r_V_4_0_0_2_fu_1030_p3 = {{src_kernel_win_0_va_19_fu_1005_p3}, {10'd0}};

assign r_V_4_0_1_1_fu_1529_p3 = {{src_kernel_win_0_va_13_fu_234}, {12'd0}};

assign r_V_4_0_1_2_fu_1541_p3 = {{src_kernel_win_0_va_18_reg_2610}, {11'd0}};

assign r_V_4_0_1_fu_1507_p3 = {{src_kernel_win_0_va_14_fu_238}, {11'd0}};

assign r_V_4_0_2_1_fu_1564_p3 = {{src_kernel_win_0_va_fu_226}, {11'd0}};

assign r_V_4_0_2_2_fu_1576_p3 = {{src_kernel_win_0_va_17_reg_2604}, {10'd0}};

assign r_V_4_0_2_fu_1552_p3 = {{src_kernel_win_0_va_12_fu_230}, {10'd0}};

assign r_V_4_1_0_1_fu_1659_p3 = {{src_kernel_win_1_va_24_reg_2638}, {11'd0}};

assign r_V_4_1_0_2_fu_1231_p3 = {{src_kernel_win_1_va_19_fu_1206_p3}, {10'd0}};

assign r_V_4_1_1_1_fu_1705_p3 = {{src_kernel_win_1_va_13_fu_258}, {12'd0}};

assign r_V_4_1_1_2_fu_1717_p3 = {{src_kernel_win_1_va_18_reg_2632}, {11'd0}};

assign r_V_4_1_1_fu_1683_p3 = {{src_kernel_win_1_va_14_fu_262}, {11'd0}};

assign r_V_4_1_2_1_fu_1740_p3 = {{src_kernel_win_1_va_fu_250}, {11'd0}};

assign r_V_4_1_2_2_fu_1752_p3 = {{src_kernel_win_1_va_17_reg_2626}, {10'd0}};

assign r_V_4_1_2_fu_1728_p3 = {{src_kernel_win_1_va_12_fu_254}, {10'd0}};

assign r_V_4_1_fu_1219_p3 = {{src_kernel_win_1_va_16_fu_270}, {10'd0}};

assign r_V_4_2_0_1_fu_1835_p3 = {{src_kernel_win_2_va_27_reg_2660}, {11'd0}};

assign r_V_4_2_0_2_fu_1414_p3 = {{src_kernel_win_2_va_22_fu_1389_p3}, {10'd0}};

assign r_V_4_2_1_1_fu_1881_p3 = {{src_kernel_win_2_va_13_fu_282}, {12'd0}};

assign r_V_4_2_1_2_fu_1893_p3 = {{src_kernel_win_2_va_21_reg_2654}, {11'd0}};

assign r_V_4_2_1_fu_1859_p3 = {{src_kernel_win_2_va_14_fu_286}, {11'd0}};

assign r_V_4_2_2_1_fu_1916_p3 = {{src_kernel_win_2_va_fu_274}, {11'd0}};

assign r_V_4_2_2_2_fu_1928_p3 = {{src_kernel_win_2_va_20_reg_2648}, {10'd0}};

assign r_V_4_2_2_fu_1904_p3 = {{src_kernel_win_2_va_12_fu_278}, {10'd0}};

assign r_V_4_2_fu_1402_p3 = {{src_kernel_win_2_va_16_fu_294}, {10'd0}};

assign r_V_4_fu_1018_p3 = {{src_kernel_win_0_va_16_fu_246}, {10'd0}};

assign rev1_fu_2086_p2 = (tmp_85_fu_2079_p3 ^ 1'd1);

assign rev2_fu_2130_p2 = (tmp_91_fu_2123_p3 ^ 1'd1);

assign rev3_fu_2174_p2 = (tmp_97_fu_2167_p3 ^ 1'd1);

assign rev_fu_733_p2 = (tmp_79_fu_725_p3 ^ 1'd1);

assign row_assign_12_0_1_t_fu_675_p2 = (tmp_77_fu_671_p1 ^ 2'd1);

assign row_assign_12_0_2_t_fu_681_p2 = ($signed(2'd2) - $signed(tmp_77_fu_671_p1));

assign src_kernel_win_0_va_17_fu_969_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_43_fu_958_p5 : col_buf_0_val_0_0_fu_876_p3);

assign src_kernel_win_0_va_18_fu_987_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_44_fu_976_p5 : col_buf_0_val_1_0_fu_894_p3);

assign src_kernel_win_0_va_19_fu_1005_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_45_fu_994_p5 : col_buf_0_val_2_0_fu_912_p3);

assign src_kernel_win_1_va_17_fu_1170_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_49_fu_1159_p5 : col_buf_1_val_0_0_fu_1077_p3);

assign src_kernel_win_1_va_18_fu_1188_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_50_fu_1177_p5 : col_buf_1_val_1_0_fu_1095_p3);

assign src_kernel_win_1_va_19_fu_1206_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_51_fu_1195_p5 : col_buf_1_val_2_0_fu_1113_p3);

assign src_kernel_win_2_va_20_fu_1353_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_55_fu_1342_p5 : col_buf_2_val_0_0_fu_1269_p3);

assign src_kernel_win_2_va_21_fu_1371_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_56_fu_1360_p5 : col_buf_2_val_1_0_fu_1287_p3);

assign src_kernel_win_2_va_22_fu_1389_p3 = ((tmp_32_reg_2473[0:0] === 1'b1) ? tmp_57_fu_1378_p5 : col_buf_2_val_2_0_fu_1305_p3);

assign start_out = real_start;

assign sum_V_0_0_2_cast_fu_1503_p1 = sum_V_0_0_2_fu_1497_p2;

assign sum_V_0_0_2_fu_1497_p2 = (tmp40_cast_fu_1494_p1 + tmp_285_0_0_1_cast_fu_1490_p1);

assign sum_V_0_1_cast_fu_1525_p1 = sum_V_0_1_fu_1519_p2;

assign sum_V_0_1_fu_1519_p2 = (sum_V_0_0_2_cast_fu_1503_p1 + tmp_285_0_1_cast_fu_1515_p1);

assign sum_V_1_0_2_cast_fu_1679_p1 = sum_V_1_0_2_fu_1673_p2;

assign sum_V_1_0_2_fu_1673_p2 = (tmp48_cast_fu_1670_p1 + tmp_285_1_0_1_cast_fu_1666_p1);

assign sum_V_1_1_cast_fu_1701_p1 = sum_V_1_1_fu_1695_p2;

assign sum_V_1_1_fu_1695_p2 = (sum_V_1_0_2_cast_fu_1679_p1 + tmp_285_1_1_cast_fu_1691_p1);

assign sum_V_2_0_2_cast_fu_1855_p1 = sum_V_2_0_2_fu_1849_p2;

assign sum_V_2_0_2_fu_1849_p2 = (tmp56_cast_fu_1846_p1 + tmp_285_2_0_1_cast_fu_1842_p1);

assign sum_V_2_1_cast_fu_1877_p1 = sum_V_2_1_fu_1871_p2;

assign sum_V_2_1_fu_1871_p2 = (sum_V_2_0_2_cast_fu_1855_p1 + tmp_285_2_1_cast_fu_1867_p1);

assign t_V_4_cast_fu_687_p1 = t_V_3_reg_590;

assign tmp40_cast_fu_1494_p1 = tmp40_reg_2621;

assign tmp40_fu_1042_p2 = (tmp_285_0_0_cast_ca_fu_1026_p1 + tmp_285_0_0_2_cast_c_fu_1038_p1);

assign tmp44_fu_1597_p2 = (tmp45_cast_fu_1593_p1 + sum_V_0_1_cast_fu_1525_p1);

assign tmp45_cast_fu_1593_p1 = tmp45_fu_1587_p2;

assign tmp45_fu_1587_p2 = (tmp_285_0_1_1_cast_c_fu_1537_p1 + tmp_285_0_2_1_cast_c_fu_1572_p1);

assign tmp46_cast_fu_1619_p1 = tmp46_fu_1613_p2;

assign tmp46_fu_1613_p2 = (tmp47_cast_fu_1609_p1 + tmp_285_0_1_2_cast_c_fu_1548_p1);

assign tmp47_cast_fu_1609_p1 = tmp47_fu_1603_p2;

assign tmp47_fu_1603_p2 = (tmp_285_0_2_cast_ca_fu_1560_p1 + tmp_285_0_2_2_cast_c_fu_1583_p1);

assign tmp48_cast_fu_1670_p1 = tmp48_reg_2643;

assign tmp48_fu_1243_p2 = (tmp_285_1_0_cast_ca_fu_1227_p1 + tmp_285_1_0_2_cast_c_fu_1239_p1);

assign tmp52_fu_1773_p2 = (tmp53_cast_fu_1769_p1 + sum_V_1_1_cast_fu_1701_p1);

assign tmp53_cast_fu_1769_p1 = tmp53_fu_1763_p2;

assign tmp53_fu_1763_p2 = (tmp_285_1_1_1_cast_c_fu_1713_p1 + tmp_285_1_2_1_cast_c_fu_1748_p1);

assign tmp54_cast_fu_1795_p1 = tmp54_fu_1789_p2;

assign tmp54_fu_1789_p2 = (tmp55_cast_fu_1785_p1 + tmp_285_1_1_2_cast_c_fu_1724_p1);

assign tmp55_cast_fu_1785_p1 = tmp55_fu_1779_p2;

assign tmp55_fu_1779_p2 = (tmp_285_1_2_cast_ca_fu_1736_p1 + tmp_285_1_2_2_cast_c_fu_1759_p1);

assign tmp56_cast_fu_1846_p1 = tmp56_reg_2665;

assign tmp56_fu_1426_p2 = (tmp_285_2_0_cast_ca_fu_1410_p1 + tmp_285_2_0_2_cast_c_fu_1422_p1);

assign tmp60_fu_1949_p2 = (tmp61_cast_fu_1945_p1 + sum_V_2_1_cast_fu_1877_p1);

assign tmp61_cast_fu_1945_p1 = tmp61_fu_1939_p2;

assign tmp61_fu_1939_p2 = (tmp_285_2_1_1_cast_c_fu_1889_p1 + tmp_285_2_2_1_cast_c_fu_1924_p1);

assign tmp62_cast_fu_1971_p1 = tmp62_fu_1965_p2;

assign tmp62_fu_1965_p2 = (tmp63_cast_fu_1961_p1 + tmp_285_2_1_2_cast_c_fu_1900_p1);

assign tmp63_cast_fu_1961_p1 = tmp63_fu_1955_p2;

assign tmp63_fu_1955_p2 = (tmp_285_2_2_cast_ca_fu_1912_p1 + tmp_285_2_2_2_cast_c_fu_1935_p1);

assign tmp_199_0_0_not_fu_631_p2 = (tmp_29_fu_625_p2 ^ 1'd1);

assign tmp_243_0_1_fu_659_p2 = ((t_V_reg_579 == 7'd0) ? 1'b1 : 1'b0);

assign tmp_26_fu_601_p2 = (tmp_25_reg_568 + 2'd1);

assign tmp_27_fu_607_p2 = ((tmp_25_reg_568 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_285_0_0_1_cast_fu_1490_p1 = r_V_4_0_0_1_fu_1483_p3;

assign tmp_285_0_0_2_cast_c_fu_1038_p1 = r_V_4_0_0_2_fu_1030_p3;

assign tmp_285_0_0_cast_ca_fu_1026_p1 = r_V_4_fu_1018_p3;

assign tmp_285_0_1_1_cast_c_fu_1537_p1 = r_V_4_0_1_1_fu_1529_p3;

assign tmp_285_0_1_2_cast_c_fu_1548_p1 = r_V_4_0_1_2_fu_1541_p3;

assign tmp_285_0_1_cast_fu_1515_p1 = r_V_4_0_1_fu_1507_p3;

assign tmp_285_0_2_1_cast_c_fu_1572_p1 = r_V_4_0_2_1_fu_1564_p3;

assign tmp_285_0_2_2_cast_c_fu_1583_p1 = r_V_4_0_2_2_fu_1576_p3;

assign tmp_285_0_2_cast_ca_fu_1560_p1 = r_V_4_0_2_fu_1552_p3;

assign tmp_285_1_0_1_cast_fu_1666_p1 = r_V_4_1_0_1_fu_1659_p3;

assign tmp_285_1_0_2_cast_c_fu_1239_p1 = r_V_4_1_0_2_fu_1231_p3;

assign tmp_285_1_0_cast_ca_fu_1227_p1 = r_V_4_1_fu_1219_p3;

assign tmp_285_1_1_1_cast_c_fu_1713_p1 = r_V_4_1_1_1_fu_1705_p3;

assign tmp_285_1_1_2_cast_c_fu_1724_p1 = r_V_4_1_1_2_fu_1717_p3;

assign tmp_285_1_1_cast_fu_1691_p1 = r_V_4_1_1_fu_1683_p3;

assign tmp_285_1_2_1_cast_c_fu_1748_p1 = r_V_4_1_2_1_fu_1740_p3;

assign tmp_285_1_2_2_cast_c_fu_1759_p1 = r_V_4_1_2_2_fu_1752_p3;

assign tmp_285_1_2_cast_ca_fu_1736_p1 = r_V_4_1_2_fu_1728_p3;

assign tmp_285_2_0_1_cast_fu_1842_p1 = r_V_4_2_0_1_fu_1835_p3;

assign tmp_285_2_0_2_cast_c_fu_1422_p1 = r_V_4_2_0_2_fu_1414_p3;

assign tmp_285_2_0_cast_ca_fu_1410_p1 = r_V_4_2_fu_1402_p3;

assign tmp_285_2_1_1_cast_c_fu_1889_p1 = r_V_4_2_1_1_fu_1881_p3;

assign tmp_285_2_1_2_cast_c_fu_1900_p1 = r_V_4_2_1_2_fu_1893_p3;

assign tmp_285_2_1_cast_fu_1867_p1 = r_V_4_2_1_fu_1859_p3;

assign tmp_285_2_2_1_cast_c_fu_1924_p1 = r_V_4_2_2_1_fu_1916_p3;

assign tmp_285_2_2_2_cast_c_fu_1935_p1 = r_V_4_2_2_2_fu_1928_p3;

assign tmp_285_2_2_cast_ca_fu_1912_p1 = r_V_4_2_2_fu_1904_p3;

assign tmp_29_fu_625_p2 = ((t_V_reg_579 < 7'd100) ? 1'b1 : 1'b0);

assign tmp_31_fu_653_p2 = ((t_V_reg_579 == 7'd1) ? 1'b1 : 1'b0);

assign tmp_32_fu_665_p2 = ((t_V_reg_579 > 7'd100) ? 1'b1 : 1'b0);

assign tmp_36_fu_739_p2 = (($signed(ImagLoc_x_fu_719_p2) < $signed(8'd100)) ? 1'b1 : 1'b0);

assign tmp_38_fu_773_p2 = (($signed(p_p2_i_i_fu_765_p3) < $signed(8'd100)) ? 1'b1 : 1'b0);

assign tmp_39_fu_820_p1 = $unsigned(x_cast_fu_805_p1);

assign tmp_77_fu_671_p1 = t_V_reg_579[1:0];

assign tmp_78_fu_703_p4 = {{t_V_3_reg_590[6:1]}};

assign tmp_79_fu_725_p3 = ImagLoc_x_fu_719_p2[32'd7];

assign tmp_80_fu_751_p3 = ImagLoc_x_fu_719_p2[32'd7];

assign tmp_81_fu_801_p1 = x_fu_793_p3[1:0];

assign tmp_85_fu_2079_p3 = p_Val2_s_reg_2670[32'd21];

assign tmp_86_fu_2092_p3 = p_Val2_13_fu_2074_p2[32'd7];

assign tmp_91_fu_2123_p3 = p_Val2_15_reg_2685[32'd21];

assign tmp_92_fu_2136_p3 = p_Val2_17_fu_2118_p2[32'd7];

assign tmp_97_fu_2167_p3 = p_Val2_19_reg_2700[32'd21];

assign tmp_98_fu_2180_p3 = p_Val2_21_fu_2162_p2[32'd7];

assign tmp_fu_637_p4 = {{t_V_reg_579[6:1]}};

assign tmp_i_cast_i1_fu_2115_p1 = tmp_90_reg_2695;

assign tmp_i_cast_i2_fu_2159_p1 = tmp_96_reg_2710;

assign tmp_i_cast_i_fu_2071_p1 = tmp_84_reg_2680;

assign x_cast_fu_805_p1 = x_fu_793_p3;

assign x_fu_793_p3 = ((or_cond_i_i_fu_745_p2[0:0] === 1'b1) ? ImagLoc_x_fu_719_p2 : p_p2_i_i_0_p_assign_s_fu_785_p3);

always @ (posedge ap_clk) begin
    tmp40_reg_2621[9:0] <= 10'b0000000000;
    tmp48_reg_2643[9:0] <= 10'b0000000000;
    tmp56_reg_2665[9:0] <= 10'b0000000000;
    p_Val2_s_reg_2670[9:0] <= 10'b0000000000;
    p_Val2_15_reg_2685[9:0] <= 10'b0000000000;
    p_Val2_19_reg_2700[9:0] <= 10'b0000000000;
end

endmodule //Filter2D_1
